### ISSUE TITLE
UnsupportedOperationException on PeepholeOptimizer

### ISSUE THREAD

**Issue by Janmm14** [java-deobfuscator/deobfuscator#10]
Transformer: ```general.peephole.PeepholeOptimizer```
```
Deobfuscation failed. Please open a ticket on GitHub
java.lang.UnsupportedOperationException
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.execute(DeadCodeRemover.java:797)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.execute(DeadCodeRemover.java:241)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$null$49(DeadCodeRemover.java:85)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover$$Lambda$28/729214165.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$transform$50(DeadCodeRemover.java:46)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover$$Lambda$26/1207755460.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:45)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer.transform(PeepholeOptimizer.java:38)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:152)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

**Comment by samczsun** [comment]
Please send the obfuscated jar to submit@javadeobfuscator.com with the subject "Issue #10"

**Comment by Janmm14** [comment]
```
submit@javadeobfuscator.com:
SMTP error from remote server for TEXT command, host: aspmx.l.google.com (74.125.133.26) reason: 552-5.7.0 This message was blocked because its content presents a potentia
l
552-5.7.0 security issue. Please visit
552-5.7.0 https://support.google.com/mail/answer/6590 to review our messa
ge
552 5.7.0 content and attachment content guidelines. p1si5250067wjx.81 - g
smtp
```

**Comment by Janmm14** [comment]
Issue got solved using other transformers before.

**Comment by samczsun** [comment]
Order of transformers does matter. Invokedynamic typically comes first.

**Comment by Janmm14** [comment]
Okay, thanks for the information.
