### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zionekkk** [java-deobfuscator/deobfuscator#1003]
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at org.objectweb.asm.Frame.merge(Frame.java:1269)
        at org.objectweb.asm.Frame.merge(Frame.java:1245)
        at org.objectweb.asm.CurrentFrame.execute(CurrentFrame.java:53)
        at org.objectweb.asm.MethodWriter.visitInvokeDynamicInsn(MethodWriter.java:1080)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2475)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
        at org.objectweb.asm.ClassWriter.replaceAsmInstructions(ClassWriter.java:777)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:740)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:675)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:457)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:455)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
        
        
 input: input.jar
output: output.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer

**Comment by Janmm14** [comment]
invalid class file inside input
or
try add
```yaml
path:
  - C:/path/to/java8/rt.jar
```
similar with other libraries of input jar.
