### ISSUE TITLE
deobfuscation error

### ISSUE THREAD

**Issue by Relvl** [java-deobfuscator/deobfuscator#1004]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException: Cannot invoke "String.replace(char, char)" because "className" is null
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:300)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.pullFromRuntime(Deobfuscator.java:511)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:487)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:571)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:540)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:634)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer.lambda$remap$0(DuplicateRenamer.java:66)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer.remap(DuplicateRenamer.java:65)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

path:
  - rt.jar
  - tools.jar
  - jconsole.jar
  - ext\jfxrt.jar
  - jogl-all.jar
  - servlet-api-2.5.jar

**Comment by Janmm14** [comment]
likely some invalid class in input jar
