### ISSUE TITLE
deobfuscation error

### ISSUE THREAD

**Issue by duykhongphai** [java-deobfuscator/deobfuscator#1005]
java.lang.IllegalArgumentException: Unsupported class file major version 66
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:298)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.pullFromRuntime(Deobfuscator.java:511)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:487)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:571)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:540)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:634)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.isAssignableFrom(Deobfuscator.java:745)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass0(Deobfuscator.java:721)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass1(Deobfuscator.java:705)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass(Deobfuscator.java:698)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm.Frame.merge(Frame.java:1300)
	at org.objectweb.asm.Frame.merge(Frame.java:1198)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1611)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1547)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:468)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:650)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:457)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:455)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by Janmm14** [comment]
update asm version locally and build deobfuscator yourself
