### ISSUE TITLE
deobfuscator error

### ISSUE THREAD

**Issue by Sneaky1337x8** [java-deobfuscator/deobfuscator#1006]
** DO NOT OPEN AN ISSUE ON GITHUB **
Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException: org/bukkit/event/Listener
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:491)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:590)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:540)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:634)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$remap$0(MethodNormalizer.java:38)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.remap(MethodNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

**Comment by Sneaky1337x8** [comment]
my config.yml

input: FunSeller.jar
output: FunSeller-leaked.jar
path:
  - C:/Program Files/Java/jdk1.8.0_341/jre/lib/rt.jar
  - path/to/bukkit.jar
  - C:/Users\Mr Fox/server.jar
libraries:
  - path/to/bukkit.jar
  - C:/Program Files/Java/jdk1.8.0_341/jre/lib/rt.jar
  - C:/Users\Mr Fox/server.jar
transformers:
  - normalizer.SourceFileClassNormalizer
  - normalizer.MethodNormalizer: {}

**Comment by Sneaky1337x8** [comment]
my config.yml

input: FunSeller.jar
output: FunSeller-leaked.jar
path:
  - C:/Program Files/Java/jdk1.8.0_341/jre/lib/rt.jar
  - C:/Users/Mr Fox/MinecraftServerCore/server.jar
libraries:
  - C:/Users/Mr Fox/MinecraftServerCore/server.jar
transformers:
  - normalizer.SourceFileClassNormalizer
  - normalizer.MethodNormalizer: {}

**Comment by Janmm14** [comment]
@Sneaky1337x8 Are you like dumb? Reread the first line of what you wrote.

**Comment by Sneaky1337x8** [comment]
oh, sorry

**Comment by Sneaky1337x8** [comment]
iI just don't know how to fix it
