### ISSUE TITLE
Deobfuscation issue

### ISSUE THREAD

**Issue by zacharycram** [java-deobfuscator/deobfuscator#1009]
Couldn't deobfuscate a jar alongside the deobfuscator GUI

`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
    at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:449)
    at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
    at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:785)
    at java.util.HashMap$Values.forEach(Unknown Source)
    at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:114)
    at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
    at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
    at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
    at java.lang.Thread.run(Unknown Source)`

**Comment by Janmm14** [comment]
zelix newer obfuscation, especially with certian options, cannot be deobfuscated with this tool. try https://github.com/narumii/Deobfuscator/
