### ISSUE TITLE
Zkm error 

### ISSUE THREAD

**Issue by theo33410** [java-deobfuscator/deobfuscator#101]
Hey!!!

i want to deobfuscate some code 

But this error happened when i try to deobfuscate 

Error while removing dead code from net/minecraft/h a(Lnet/minecraft/ah;)V
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:403)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:267)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:221)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$null$2(DeadCodeRemover.java:42)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$transform$3(DeadCodeRemover.java:40)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:39)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer.transform(PeepholeOptimizer.java:45)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:155)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
Deobfuscation failed. Please open a ticket on GitHub
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.LinkedList.checkPositionIndex(LinkedList.java:560)
	at java.util.LinkedList.add(LinkedList.java:507)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:490)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$11(StringEncryptionTransformer.java:233)
	at java.util.HashMap$Values.forEach(HashMap.java:980)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:198)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

Help me please ... 

 Thanks

**Comment by theo33410** [comment]
Sorry ... its 3AM i really search for that error but none found

**Comment by theo33410** [comment]
Ask me for jar

**Comment by FireMasterK** [comment]
Jar?

**Comment by theo33410** [comment]
Gona test thanks

**Comment by theo33410** [comment]
Do you have skype ? my machine is not too powerfull for deob ... i can pay

**Comment by theo33410** [comment]
Same error java.lang.IndexOutOfBoundException: Index: 2, Size: 1

**Comment by FireMasterK** [comment]
Send the Jar!

**Comment by theo33410** [comment]
http://www.fileconvoy.com/dfl.php?id=g964b5479a26107d8999978519d17702ea3864d3f9

**Comment by theo33410** [comment]
jar is 1.7.10.jar , lib is a.jar b.jar d.jar to h.jar :)

**Comment by theo33410** [comment]
Thanks for your help ! :) you are a good man :D

**Comment by FireMasterK** [comment]
K I'll check it out after I come back from school.

**Comment by theo33410** [comment]
Thanks you man !

**Comment by FireMasterK** [comment]
I will try updating the transformer later on :)

**Comment by FireMasterK** [comment]
Zelix became way better than I last saw it....

**Comment by theo33410** [comment]
Thanks , i really need this ...

**Comment by theo33410** [comment]
can  i talk to you on skype or other ?,

**Comment by FireMasterK** [comment]
Discord?

**Comment by theo33410** [comment]
Yes of course, https://discord.gg/TqTW4u2

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
