### ISSUE TITLE
How can i ignore classes under a whole folder

### ISSUE THREAD

**Issue by neilhuang007** [java-deobfuscator/deobfuscator#1010]
as the question stated, i do not want to deobfuscate classfiles for the libraries included in the jar file, please help

**Comment by neilhuang007** [comment]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.LdcSwapInvokeSwapPopRemover.lambda$null$1(LdcSwapInvokeSwapPopRemover.java:42)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.LdcSwapInvokeSwapPopRemover.lambda$transform$2(LdcSwapInvokeSwapPopRemover.java:34)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.LdcSwapInvokeSwapPopRemover.transform(LdcSwapInvokeSwapPopRemover.java:33)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.ja

va:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.lang.Thread.run(Thread.java:750)
also an issue with this file its the cleaned jar in here
[vape.zip](https://github.com/user-attachments/files/17028853/vape.zip)
this is my comfig:
![image](https://github.com/user-attachments/assets/148cc377-043e-4c5c-b183-f02936a9a9c0)

**Comment by Janmm14** [comment]
you made the mistake of just adding everything

many transformers can fail (or sometimes even produce wrong results) when used on different obfuscation

if the detection can not find out what you should use:
maybe you can post a sample decompiled method of what is obfuscated, maybe some1 or me recogizes it. (do not upload complete jar file here unless you have the expliit rights to share/publish it)

otherwise you are on your own, this project is unmaintained

**Comment by CrazyMentos** [comment]
> you made the mistake of just adding everything
> 
> many transformers can fail (or sometimes even produce wrong results) when used on different obfuscation
> 
> if the detection can not find out what you should use: maybe you can post a sample decompiled method of what is obfuscated, maybe some1 or me recogizes it. (do not upload complete jar file here unless you have the expliit rights to share/publish it)
> 
> otherwise you are on your own, this project is unmaintained

Hi, I have a question about deobfuscation could you message me in discord here is nickname Mentos8156

**Comment by Janmm14** [comment]
nope
