### ISSUE TITLE
Deobf Issue

### ISSUE THREAD

**Issue by Vxrtrauter** [java-deobfuscator/deobfuscator#1012]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Unexpected opcode! Mode 0, opcode 167 at cc/legitlauncher/a23
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:779)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:114)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

**Comment by Janmm14** [comment]
reason for this is one of these:
- the obfuscated program did use any kind of recent zkm version (very likely I guess)
- not obfuscated with zkm
- wrong order of zkm transformers
- other obfuscation is on top of zkm and needs to be handled first

As this project is not actively worked on by anyone, good luck.
