### ISSUE TITLE
Stringer decrypt String failed

### ISSUE THREAD

**Issue by libYo** [java-deobfuscator/deobfuscator#103]
Reading complete. Loading hierachy

Transforming

[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 6932 encrypted strings
Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for xij/eyt/v <init>(I)V @ com/jack/a/h/c$c <clinit>()V
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Unknown Source)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Unknown Source)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(Unknown Source)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(Unknown Source)

Please help

**Comment by FFY00** [comment]
What version of stringer are you trying to decrypt? What version of the deobfuscator are you using?

**Comment by libYo** [comment]
i'm using deobfuscator latest source code build with eclipse, file protect with Stringer v3.0.9

**Comment by FFY00** [comment]
I tested it with 3.0.9. I'll have a look when I can.

**Comment by libYo** [comment]
New error

Reading complete. Loading hierachy


Transforming

[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 6932 encrypted strings
Deobfuscation failed. Please open a ticket on GitHub
java.lang.NullPointerException
	at java.lang.reflect.Array.get(Native Method)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:106)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:462)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:213)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:60)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:172)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:105)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by FFY00** [comment]
Are you sure your jar only has stringer obfuscation?

**Comment by libYo** [comment]
I'm not sure jar protect with only stringer, try to repack jar without touch any file, jar not running throw error.

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
