### ISSUE TITLE
Allatori decryption issue.

### ISSUE THREAD

**Issue by LynxIsAWeirdo** [java-deobfuscator/deobfuscator#105]
```
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.isAllatoriMethod(StringEncryptionTransformer.java:121)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$null$1(StringEncryptionTransformer.java:92)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$transform$2(StringEncryptionTransformer.java:57)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:56)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:172)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

I am using this deobfuscator version: http://rgho.st/6QFHZZhqJ?r=3117

I get this error when I attempt to deobfuscate a jar obfuscated by Allatori DEMO v6.1

I have set the class path to include several jars from the jre library, as well as lots of necessary jars.

However, I doubt this is an issue with the class path. All help is appreciated.

Thank you.

**Comment by FFY00** [comment]
We need to update the allatori deobfuscation, there are some issues (maybe caused when we updated to stringer 3?). Unfortunately I haven't had much time lately. If someome wants to help, it would be apreciated.

**Comment by Janmm14** [comment]
The heuristic whether a method is an alltori method which got added by coolman seems to be totally unefficient

**Comment by netindev** [comment]
This last commit worked perfectly with me in version 6.2

**Comment by c001man** [comment]
https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java#L121
I forget the null-check.

Honestly, I'm not ready yet to merge my code to upstream, but someone did it for me.
The transformer for Allatori might be not compatible with older versions of Allatori.

**Comment by LynxIsAWeirdo** [comment]
@c001man Will it be fine for Allatori DEMO v6.1?

**Comment by c001man** [comment]
@LynxIsAWeirdo AFAIK the obfuscation of the two version is the same.

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
