### ISSUE TITLE
Deobfuscation issue

### ISSUE THREAD

**Issue by Swedz** [java-deobfuscator/deobfuscator#106]
When I run `java -jar deobfuscator.jar -input ModDetector.jar -output ModDetector-deobf.jar -transformer general.SyntheticBridgeTransformer -path C:\spigot-1.8.8.jar`
I get this error:
```
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: java/lang/Object
at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:203)
at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:236)
at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:213)
at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:162)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(Deobfuscator.java:105)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(Deobfuscator.java:26)
```
Only reason why I posted this here is because this is just a normal Java class (Object). I'm just confused why it thinks I should have to supply the default Java classes...

**Comment by FFY00** [comment]
The rt.jar (runtime library) path depends on each instalation so you need to provide the it to be added in the classpath.

**Comment by Swedz** [comment]
And how do I find that?

**Comment by FireMasterK** [comment]
Step 1: install jdk from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
Step 2: Change your command to `java -jar deobfuscator.jar -input ModDetector.jar -output ModDetector-deobf.jar -transformer general.SyntheticBridgeTransformer -path "%java_home%/jre/lib/rt.jar" -path C:\spigot-1.8.8.jar`
