### ISSUE TITLE
Stringer Reflection Obfuscation Failed

### ISSUE THREAD

**Issue by ThisTestUser** [java-deobfuscator/deobfuscator#107]
The strings were decrypted, but not the reflection. 
`
[Stringer] [ReflectionObfuscationTransformer] Starting
[Stringer] [ReflectionObfuscationTransformer] Found 319 reflection obfuscation calls
Deobfuscation failed. Please open a ticket on GitHub
java.lang.ArrayIndexOutOfBoundsException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:106)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:471)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.executor.defined.DictionaryMethodProvider.invokeMethod(DictionaryMethodProvider.java:49)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1204)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.executor.defined.DictionaryMethodProvider.invokeMethod(DictionaryMethodProvider.java:49)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1204)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$null$10(ReflectionObfuscationTransformer.java:202)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$decrypt$11(ReflectionObfuscationTransformer.java:118)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.decrypt(ReflectionObfuscationTransformer.java:117)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:67)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:172)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
`

**Comment by FireMasterK** [comment]
Use stringer.HideAccessObfuscationTransformer

**Comment by ThisTestUser** [comment]
It works, thank you so much!
