### ISSUE TITLE
NoSuchComparisonHandlerException java/lang/String and [C

### ISSUE THREAD

**Issue by Janmm14** [java-deobfuscator/deobfuscator#11]
Transformer: ```zelix.ReflectionObfuscationTransformer```
```
Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchComparisonHandlerException: No comparator found for java/lang/String
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:865)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:79)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:32)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:764)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:79)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.lambda$null$275(ReflectionObfuscationTransformer.java:160)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer$$Lambda$76/965674262.accept(Unknown Source)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.lambda$inlineReflection$276(ReflectionObfuscationTransformer.java:116)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer$$Lambda$75/1318395825.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:115)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:63)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:152)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

**Comment by Janmm14** [comment]
Zelix not used.

**Comment by Janmm14** [comment]
Actually zelix seems to be used at the level of deobfuscation I am at now.

Decompilation shows a(a("somerandomstring")) methods as well as reflection obfuscation referring to the same class with a static method which has a long as argument.

Zelix flow obfuscation/string obfuscation might have such a behaviour.

All other transformers have been tried, but they report no changes / no found calls anymore.

Error with ```zelix.StringEncryptionTransformer```:
```
Rearranged 0 goto blocks
Removed 0 continous gotos
Removed 0 unconditional switches
Removed 445 dead instructions
Removed 0 nops
Removed 0 goto unconditional jumps
Removed 0 redundant traps
Removed 0 ldc-pop patterns
Removed 0 ldc-swap-invoke-swap-pop patterns
Rearranged 427 goto blocks
Removed 0 continous gotos
Removed 0 unconditional switches
Removed 0 dead instructions
Removed 0 nops
Removed 0 goto unconditional jumps
Removed 0 redundant traps
Removed 0 ldc-pop patterns
Removed 0 ldc-swap-invoke-swap-pop patterns
Rearranged 0 goto blocks
Removed 0 continous gotos
Removed 0 unconditional switches
Removed 0 dead instructions
Removed 0 nops
Removed 0 goto unconditional jumps
Removed 0 redundant traps
Removed 0 ldc-pop patterns
Removed 0 ldc-swap-invoke-swap-pop patterns
Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchComparisonHandlerException: No comparator found for [C
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:865)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:79)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:32)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:764)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:79)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$119(StringEncryptionTransformer.java:171)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer$$Lambda$150/627157722.accept(Unknown Source)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:151)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:152)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Error with ```zelix.ReflectionObfuscationTransformer```:
```
[Zelix] [ReflectionObfuscationTransformer] Starting
[Zelix] [ReflectionObfuscationTransformer] Finding reflection obfuscation
[Zelix] [ReflectionObfuscationTransformer] Found 905 reflection obfuscation instructions
Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchComparisonHandlerException: No comparator found for java/lang/String
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:865)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:79)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:32)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:764)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:79)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.lambda$null$275(ReflectionObfuscationTransformer.java
:160)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer$$Lambda$76/515244925.accept(Unknown Source)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.lambda$inlineReflection$276(ReflectionObfuscationTran
sformer.java:116)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer$$Lambda$75/44007732.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.jav
a:115)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:63)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:152)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

**Comment by samczsun** [comment]
Please send the obfuscated jar either by attaching or via a file sharing website like Dropbox to submit@javadeobfuscator.com with the subject "Issue #11".
