### ISSUE TITLE
Hide Access Deobfuscation (Stringer) failed

### ISSUE THREAD

**Issue by ThisTestUser** [java-deobfuscator/deobfuscator#111]
[Stringer] [HideAccessTransformer] Starting
[Stringer] [HideAccessTransformer] Found 7 decryptors
Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.executor.exceptions.ExecutionException: java.lang.UnsupportedOperationException @ a/a/a/a Hi(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1296)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$null$5(HideAccessObfuscationTransformer.java:126)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$6(HideAccessObfuscationTransformer.java:108)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:107)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:172)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
Caused by: java.lang.UnsupportedOperationException
        ... 26 more

I looked in the code, and it looks like the code uses an "invokedynamic" instruction at MethodExecutor.
Note that I ran this after the string encryption transformer, if I ran this first it would throw another error.

**Comment by FireMasterK** [comment]
https://github.com/java-deobfuscator/deobfuscator/blob/src/main/java/com/javadeobfuscator/deobfuscator/executor/MethodExecutor.java#L1296
There is the error

**Comment by MoofMonkey** [comment]
InvokeDynamic aren't supported now ._.

**Comment by ThisTestUser** [comment]
Yeah, but it seems that Retroindy can create INDY_xx equivalents of those methods.
So is it possible to create a program that deobfuscates those statements?

**Comment by Janmm14** [comment]
Retroindy will probably cause stringer obfuscation to fail deobfuscating.
