### ISSUE TITLE
Error(allatori)

### ISSUE THREAD

**Issue by maxim19116** [java-deobfuscator/deobfuscator#117]
java -jar deobf.jar -input IN.jar -output output1.jar -transformer allatori.StringEncryptionTransformer -path rt.jar

Reading complete. Loading hierachy

Transforming

[Allatori] [StringEncryptionTransformer] Starting
Deobfuscation failed. Please open a ticket on GitHub
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$1(StringEncryptionTransformer.java:81)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$0(StringEncryptionTransformer.java:57)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:56)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:172)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by FireMasterK** [comment]
Jar?

**Comment by maxim19116** [comment]
Yes

**Comment by ThisTestUser** [comment]
Same as #120, partially fixed with my fork.

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
