### ISSUE TITLE
Allatori problem x 2(Deobfuscator Bugx2)

### ISSUE THREAD

**Issue by CrackFileso** [java-deobfuscator/deobfuscator#130]
https://workupload.com/file/ebVVRVN
PW:WhiteWizard

Try this jar file

**Comment by CrackFileso** [comment]
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
dee ALLATORIxDEMOxè§?è§?è§????è§?è§????????????????è§?è§?è§???????è§???????è§????è§????è§?è§????è§????è§???????è§????è§?è§????è§?è§????è§?è§????è§?è§?è§????è§??????????è§???????è§?è§?è§?è§????è§?è§????è§?è§?è§?(Lkrb;Lat;)Lry; krb ALLATORIxDEMOxè§?è§?è§????è§?è§????????????????è§?è§?è§???????è§???????è§????è§????è§?è§????è§????è§???????è§????è§?è§????è§?è§????è§?è§????è§?è§?è§????è§??????????è§???????è§?è§?è§?è§????è§?è§????è§?è§?è§?(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.ExecutionException: getField failed @ krb v(Ljava/lang/String;)B
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.getField(DelegatingProvider.java:74)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1020)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1080)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1080)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$2(StringEncryptionTransformer.java:97)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$0(StringEncryptionTransformer.java:57)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:56)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:177)

**Comment by ThisTestUser** [comment]
https://workupload.com/file/6ZNKQ2u
Deobbed with the deobfuscator in my PR.

**Comment by CrackFileso** [comment]
Emmm.I think no:
The main class is still in obfu
http://prntscr.com/gmf13o

**Comment by ThisTestUser** [comment]
I'll work on it tomorrow. I probably just have to update the detector.

**Comment by ThisTestUser** [comment]
Fixed it: https://workupload.com/file/p73SLPN

**Comment by CrackFileso** [comment]
File no Find pro

**Comment by CrackFileso** [comment]
But i think this more like a Bug.

**Comment by CrackFileso** [comment]
Emmm..New version may be a Bug version

Transforming

Rearranged 0 goto blocks
Removed 0 continous gotos
Removed 0 unconditional switches
Removed 0 dead instructions
Removed 0 nops
Removed 0 goto unconditional jumps
Removed 0 ldc-pop patterns
Removed 0 dup-pop like instructions
Removed 0 ldc-swap-invoke-swap-pop patterns
Removed 0 redundant traps
Rearranged 0 goto blocks
Removed 0 continous gotos
Removed 0 unconditional switches
Removed 0 dead instructions
Removed 0 nops
Removed 0 goto unconditional jumps
Removed 0 ldc-pop patterns
Removed 0 dup-pop like instructions
Removed 0 ldc-swap-invoke-swap-pop patterns
Removed 0 redundant traps
[Allatori] [StringEncryptionTransformer] Starting
Exception in thread "main" java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$2(StringEncryptionTransformer.java:81)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$0(StringEncryptionTransformer.java:57)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:56)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:177)

**Comment by CrackFileso** [comment]
thanks pro,I do it by myself with your Fixed transformers

**Comment by CrackFileso** [comment]
Close
