### ISSUE TITLE
Class Version Trick

### ISSUE THREAD

**Issue by CrackFileso** [java-deobfuscator/deobfuscator#134]
```
Exception in thread "main" java.lang.IllegalArgumentException
	at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:154)
	at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:431)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:94)
```

        if (readShort(off + 6) > Opcodes.V1_8) {
            throw new IllegalArgumentException();
        }

Stack trace:
readShort(off + 6) --->53

**Comment by ThisTestUser** [comment]
What are you trying to deobfuscate?

**Comment by CrackFileso** [comment]
a jar file
The jar is working.

**Comment by ThisTestUser** [comment]
If you set the version to java 9, the jar wouldn't be able to run on java 8.

**Comment by FireMasterK** [comment]
Use this jar : [https://github.com/FireMasterK/deobfuscator/releases/download/1.0.9/deobfuscator-1.0.0.jar](url)

**Comment by ThisTestUser** [comment]
If your JAR was obfuscated with the "Smoke" obfuscator JAR, it's better to delete those classes, as Smoke injects Java 9 garbage classes.

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists, preferably with a sample attached
