### ISSUE TITLE
NPE in zelix.StringEncryptionTransformer

### ISSUE THREAD

**Issue by rmueller83** [java-deobfuscator/deobfuscator#14]
```
Deobfuscation failed. Please open a ticket on GitHub
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$249(StringEncryptionTransformer.java:89)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:57)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:152)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Could this even work at all? In https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/zelix/StringEncryptionTransformer.java#L78 the `while` is left due to `next == null`, so calling `next.getNext()` in https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/zelix/StringEncryptionTransformer.java#L89 fails.

**Comment by samczsun** [comment]
Right. I seem to have forgotten to add a nullcheck. That portion of the transformer is pretty volatile hence the fixme note

**Comment by samczsun** [comment]
Unfortunately, it would appear that specific bytecode patterns used is different here. Because of how volatile the transformer is there's really no point in expanding it to handle every edge case. Instead, I'd rather create a catch-all (see MethodAnalyzer) which can adapt to different variations of this obfuscation in general

**Comment by Djamana** [comment]
Got some simulare error:

```
Error while fully initializing burp/opc
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:942)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$11(StringEncryptionTransformer.java:250)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:198)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```
and 'argument type mismatch'
```
Error while fully initializing burp/s5g
java.lang.IllegalArgumentException: argument type mismatch
	at java.lang.reflect.Array.set(Native Method)
...
Error while fully initializing burp/zdh
java.lang.IllegalArgumentException: argument type mismatch
	at java.lang.reflect.Array.set(Native Method)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayStore(MethodExecutor.java:167)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:472)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$11(StringEncryptionTransformer.java:250)
...
```
That's how I run deobfuscator:
```
@set InFile=burpP1.7.03.jar
::@set InPath=..\!sample\

deobfuscator-1.0.0.jar ^
	-input %InPath%%InFile% ^
	-output %InPath%DeObfu_%InFile% ^
	-transformer zelix.StringEncryptionTransformer ^
	-path "%Java_Home%/jre/lib/rt.jar"
```
Here's a sample to easy reproduce these errors:
[Zelix-Sample.zip.txt](https://github.com/java-deobfuscator/deobfuscator/files/390401/Zelix-Sample.zip.txt)
_^-rename to .zip before opening!_ 
(^-That github somehow don't work with zip - even if it mention it as allow extension.)

Btw the sample is taken from 'Burpsuite_pro_v1.7.03' that uses Zelix KlassMaster Obfuscation

**Comment by koxu1996** [comment]
I encountered same problem:
```
java.lang.IllegalArgumentException: argument type mismatch                                            
        at java.lang.reflect.Array.set(Native Method)                                                 
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayStore(MethodExecutor.java:172)                                                                                              
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:495) 
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)  
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$11(StringEncryptionTransformer.java:250)                                                        
        at java.util.HashMap$Values.forEach(HashMap.java:980)                                         
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:198)                                                                  
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:172)                
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:105)          
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

**Comment by ThisTestUser** [comment]
https://github.com/java-deobfuscator/deobfuscator/pull/121 fixes this.
