### ISSUE TITLE
Allatori string transformer issue

### ISSUE THREAD

**Issue by Propriate** [java-deobfuscator/deobfuscator#148]
Hello, i'm getting a ArrayIndexOutOfBoundsException when i try to decompile JAR with the Allatori transformers.

Here is the error,

```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
[Allatori] [StringEncryptionTransformer] Starting





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.javadeobfuscator.org.objectweb.asm.Type.getReturnType(Type.java:382)
        at com.javadeobfuscator.org.objectweb.asm.Type.getReturnType(Type.java:609)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:797)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:268)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$null$2(StringEncryptionTransformer.java:57)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$transform$3(StringEncryptionTransformer.java:56)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:55)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:266)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:226)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

And here the configuration i use, 

```
input: input.jar
output: output.jar
transformers:
  - allatori.StringEncryptionTransformer
```

Tried with the latest build pushed.

[JAR.zip](https://github.com/java-deobfuscator/deobfuscator/files/1366551/JAR.zip)

**Comment by ThisTestUser** [comment]
Its probably an error with ASM 6...
The only to fix it is to use an older build.

**Comment by samczsun** [comment]
Ah, that's a copy/paste issue. ASM 5 was lenient so I didn't notice it, but I've been fixing them as I go along since ASM 6 complains
