### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error

### ISSUE THREAD

**Issue by TheQmaks** [java-deobfuscator/deobfuscator#154]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ClassCastException: com.javadeobfuscator.org.objectweb.asm.tree.LabelNode cannot be cast to com.javadeobfuscator.org.objectweb.asm.tree.LdcInsnNode
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.lambda$null$7(ReflectionObfuscationTransformer.java:220)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.lambda$inlineReflection$8(ReflectionObfuscationTransformer.java:133)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:132)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:63)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Unknown Source)

**Comment by TheQmaks** [comment]
Target file -> http://rgho.st/8zm6hwh2z

**Comment by TheQmaks** [comment]
@samczsun what you can say about it?

**Comment by Janmm14** [comment]
chill

**Comment by samczsun** [comment]
@TheQmaks I'll take a look on saturday/sunday, when I have some free time. My applying the label is my acknowledging that you opened an issue, but that doesn't mean I have time to actually look at it

**Comment by TheQmaks** [comment]
Ok, thx

**Comment by samczsun** [comment]
@TheQmaks what transformers are you using, and in what order? I can't seem to reproduce this

**Comment by TheQmaks** [comment]
@samczsun I do not remember any more, I tried a lot of combinations in order to achieve complete decompilation of reflection calls.

**Comment by samczsun** [comment]
It might be that the newer versions of Zelix aren't supported yet. Fixing that will take significantly longer

**Comment by TheQmaks** [comment]
@samczsun but you can try

**Comment by ThisTestUser** [comment]
http://rgho.st/7zK9JY97v

**Comment by TheQmaks** [comment]
@ThisTestUser you can remove? Thx, if you can - write me pls ur discord

**Comment by ThisTestUser** [comment]
discord.gg/4kxT2Ju
