### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

### ISSUE THREAD

**Issue by letruongthinh** [java-deobfuscator/deobfuscator#156]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.ClassNormalizer.lambda$remap$0(ClassNormalizer.java:29)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.ClassNormalizer.remap(ClassNormalizer.java:28)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50) @samczsun

**Comment by FireMasterK** [comment]
Ok this is an easy fix
