### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by demkom58** [java-deobfuscator/deobfuscator#160]
Jar: https://drive.google.com/open?id=0B7FrXyCz1EKwemtJVVN2dVNqWTg

**stringer.InvokedynamicTransformer** (_I'm not sure if this is obfuscated with Stringer_)
```Java
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer
[Stringer] [InvokedynamicTransformer] Starting
[Stringer] [InvokedynamicTransformer] Finding invokedynamic instructions

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.lambda$null$0(InvokedynamicTransformer.java:75)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.lambda$findInvokeDynamic$1(InvokedynamicTransformer.java:70)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.findInvokeDynamic(InvokedynamicTransformer.java:69)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.transform(InvokedynamicTransformer.java:51)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
**Also when i use**
  - general.remover.LocalVariableRemover
  - general.remover.IllegalSignatureRemover
  - general.remover.IllegalVarargsRemover
  - general.remover.LineNumberRemover
  - general.remover.SyntheticBridgeRemover

```Java
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.javadeobfuscator.deobfuscator.transformers.Transformer` from String "general.remover.LocalVariableRemover": Could not locate specified transformer
 at [Source: (File); line: 4, column: 5] (through reference chain: com.javadeobfuscator.deobfuscator.config.Configuration["transformers"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1535)
        at com.javadeobfuscator.deobfuscator.config.TransformerConfigDeserializer.getById(TransformerConfigDeserializer.java:99)
        at com.javadeobfuscator.deobfuscator.config.TransformerConfigDeserializer.deserialize(TransformerConfigDeserializer.java:69)
        at com.javadeobfuscator.deobfuscator.config.TransformerConfigDeserializer.deserialize(TransformerConfigDeserializer.java:34)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:80)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
I apologize if I misuse it.

**Comment by FireMasterK** [comment]
The transformer `general.remover.LocalVariableRemover` was removed in the latest version so thats why you got the second exception

**Comment by FireMasterK** [comment]
```
general.removers.LocalVariableRemover
general.removers.IllegalSignatureRemover
general.removers.IllegalVarargsRemover
general.removers.LineNumberRemover
general.removers.SyntheticBridgeRemover
```
Its messed up in the guide

**Comment by samczsun** [comment]
Thanks, I'll take a look later and see if it's a custom obfuscator or not

**Comment by samczsun** [comment]
late update: I swear I've seen this before but can't quite place my finger on it. weird
