### ISSUE TITLE
Deobufscation Failed!

### ISSUE THREAD

**Issue by rafedup27** [java-deobfuscator/deobfuscator#161]
Whenever i try the option "zelix.StringEncryptionTransformer" I receive the error that is below.
I really need this to work as I want to remove something from it.
Thank you!
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:333)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1020)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:261)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$13(StringEncryptionTransformer.java:188)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:182)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

**Comment by rafedup27** [comment]
BUMP

**Comment by samczsun** [comment]
Please provide the file you're trying to deobfuscate

**Comment by rafedup27** [comment]
Here is the file! It is using ZKM 5(.1)
http://www37.zippyshare.com/v/HX62btjJ/file.html

**Comment by rafedup27** [comment]
the magical shoe bump

**Comment by ThisTestUser** [comment]
[BotDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1443428/BotDeob.zip)
Rename to JAR

**Comment by ThisTestUser** [comment]
[BotDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1443436/BotDeob.zip)
Rename to JAR

**Comment by rafedup27** [comment]
How have you managed to deoubfuscate it?

**Comment by ThisTestUser** [comment]
Private deobfuscator

**Comment by rafedup27** [comment]
I got one question. Could you remove 2 methods that are in the Bot.class and xb.class which are in the de.me.death pacakelge which are "Server is blacklisted". Thank you

**Comment by FireMasterK** [comment]
Use jbytemod

**Comment by rafedup27** [comment]
I have tried with jbytemod and there is no delete in it, implemented yet!

**Comment by Janmm14** [comment]
simply deleting those methods would not help you anyway, you would need to replace / edit the instructions

**Comment by FireMasterK** [comment]
Right click on method and then click clear!

**Comment by rafedup27** [comment]
Still, no way to clear it... It only shows Delete. But it is locked

**Comment by samczsun** [comment]
Assuming this is resolved since a deobfuscated sample was provided
