### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by 1582421598** [java-deobfuscator/deobfuscator#165]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 11560
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readConst(ClassReader.java:2747)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1582)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:169)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Thread.java:745)

file：http://www.mediafire.com/file/h3y3ahkab0dhxtb

**Comment by samczsun** [comment]
Looks like a corrupt class file, but I'll take a look once I'm back on a computer

**Comment by samczsun** [comment]
Well... it's been a while but unfortunately I didn't get a chance to download the file and now it's gone sooooooooo
