### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by Kaxyn** [java-deobfuscator/deobfuscator#166]
```Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.transformers.dasho.StringEncryptionTransformer.lambda$null$1(StringEncryptionTransformer.java:87)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.dasho.StringEncryptionTransformer.lambda$transform$2(StringEncryptionTransformer.java:53)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.dasho.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:52)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by FireMasterK** [comment]
The DashO transformer was updated more than a year ago

**Comment by samczsun** [comment]
Please provide the input file
