### ISSUE TITLE
I have a problem help!!!!!

### ISSUE THREAD

**Issue by Ellidium** [java-deobfuscator/deobfuscator#174]
[Stringer] [HideAccessTransformer] Starting
[Stringer] [HideAccessTransformer] Found 36 decryptors
Exception in thread "Thread-3" com.javadeobfuscator.deobfuscator.executor.exceptions.ExecutionException: java.lang.NullPointerException @ rip/anticheat/anticheat/checks/combat/FastBow$Regen o(ILjava/lang/Object;)V
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1517)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1231)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaThread.lambda$start$1(JavaThread.java:52)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:106)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:478)
        ... 7 more
Exception in thread "Thread-4" com.javadeobfuscator.deobfuscator.executor.exceptions.ExecutionException: java.lang.NullPointerException @ rip/anticheat/anticheat/checks/combat/FastBow$Regen o(ILjava/lang/Object;)V
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1517)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1231)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaThread.lambda$start$1(JavaThread.java:52)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:106)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:478)
        ... 7 more

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NumberFormatException: For input string: "??????????"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$1$42.lambda$new$0(JVMMethodProvider.java:490)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$Function3.applyUnchecked(JVMMethodProvider.java:710)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider.invokeMethod(JVMMethodProvider.java:627)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1231)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$1(HideAccessObfuscationTransformer.java:114)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:110)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by Ellidium** [comment]
Help to decrypt the plugin!!!!

[AntiCheat.zip](https://github.com/java-deobfuscator/deobfuscator/files/1464933/AntiCheat.zip)

**Comment by ThisTestUser** [comment]
Use stringer.stringencryptiontransformer first

**Comment by Ellidium** [comment]
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 2230 encrypted strings
[Stringer] [StringEncryptionTransformer] Done 10%
[Stringer] [StringEncryptionTransformer] Done 20%
[Stringer] [StringEncryptionTransformer] Done 30%
[Stringer] [StringEncryptionTransformer] Done 40%
[Stringer] [StringEncryptionTransformer] Done 50%
[Stringer] [StringEncryptionTransformer] Done 60%
[Stringer] [StringEncryptionTransformer] Done 70%
[Stringer] [StringEncryptionTransformer] Done 80%
[Stringer] [StringEncryptionTransformer] Done 90%
[Stringer] [StringEncryptionTransformer] Done 100%
[Stringer] [StringEncryptionTransformer] Decrypted 2230 encrypted strings
[Stringer] [StringEncryptionTransformer] Removed 78 decryption classes
[Stringer] [StringEncryptionTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer
[Stringer] [InvokedynamicTransformer] Starting
[Stringer] [InvokedynamicTransformer] Finding invokedynamic instructions





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.lambda$null$0(InvokedynamicTransformer.java:75)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.lambda$findInvokeDynamic$1(InvokedynamicTransformer.java:70)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.findInvokeDynamic(InvokedynamicTransformer.java:69)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.transform(InvokedynamicTransformer.java:51)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

C:\Users\roman\Desktop\ggg>pause

**Comment by ThisTestUser** [comment]
Use string encryption transformer (stringer), and then hideaccessobfuscation (stringer).

**Comment by Ellidium** [comment]
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 2230 encrypted strings
[Stringer] [StringEncryptionTransformer] Done 10%
[Stringer] [StringEncryptionTransformer] Done 20%
[Stringer] [StringEncryptionTransformer] Done 30%
[Stringer] [StringEncryptionTransformer] Done 40%
[Stringer] [StringEncryptionTransformer] Done 50%
[Stringer] [StringEncryptionTransformer] Done 60%
[Stringer] [StringEncryptionTransformer] Done 70%
[Stringer] [StringEncryptionTransformer] Done 80%
[Stringer] [StringEncryptionTransformer] Done 90%
[Stringer] [StringEncryptionTransformer] Done 100%
[Stringer] [StringEncryptionTransformer] Decrypted 2230 encrypted strings
[Stringer] [StringEncryptionTransformer] Removed 78 decryption classes
[Stringer] [StringEncryptionTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer
[Stringer] [HideAccessTransformer] Starting
[Stringer] [HideAccessTransformer] Found 36 decryptors





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$1$19.lambda$new$16(JVMMethodProvider.java:304)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$Function3.applyUnchecked(JVMMethodProvider.java:710)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider.invokeMethod(JVMMethodProvider.java:627)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1097)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$null$15(HideAccessObfuscationTransformer.java:282)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$16(HideAccessObfuscationTransformer.java:156)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:155)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

C:\Users\roman\Desktop\ggg>pause

**Comment by ThisTestUser** [comment]
[Anti.ProDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1465043/Anti.ProDeob.zip)

**Comment by Ellidium** [comment]
how?

**Comment by ThisTestUser** [comment]
You may be using an old version of deobfuscator.jar.

**Comment by Ellidium** [comment]
Can you please throw the new version.

**Comment by FireMasterK** [comment]
No it's supposed to be private

**Comment by ThisTestUser** [comment]
Since I always my stringer transformers, the error probably comes from an older deobfuscator.jar from months ago. Grabbing the newer version from https://ci.samczsun.com/job/java-deobfuscator/job/Deobfuscator/ should work

**Comment by Ellidium** [comment]
I have this version and use it!

**Comment by ThisTestUser** [comment]
If you downloaded it before, you need to redownload it.

**Comment by Ellidium** [comment]
Please please decode two plugins will be very grateful.
[2Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/1465059/2Plugin.zip)

**Comment by Ellidium** [comment]
And I'll seek what I have a problem while decrypting...

**Comment by Janmm14** [comment]
To everyone: Please do not deobfuscate premium plugins thanks.

To Ellidium: Just NO!

**Comment by Ellidium** [comment]
I want to combine them to get a powerful anti cheat.

**Comment by Janmm14** [comment]
That is not, how it is expected to be.
Beside the fact that you steal them through blackspigotmc and you think developers get their stuff for free too, it is senseless to choose Antiaura since AAC is much better.

You will not be able to have a better anticheat than using the plugins splitted.
