### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by masste** [java-deobfuscator/deobfuscator#175]
```java
java -jar deobfuscator.jar --config config.yaml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 178
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:171)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:167)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:235)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)```

input: obfuscated.jar
output: deobfuscated.jar
transformers:
  - normalizer.ClassNormalizer: {}
path:
  - rt.jar

**Comment by ThisTestUser** [comment]
Please provide the JAR file you tried to deobfuscate.

**Comment by masste** [comment]
Can I get your mail? I don't want to send it public.

**Comment by ThisTestUser** [comment]
Do you have discord? You could send it to me there.

**Comment by masste** [comment]
maste#3992

**Comment by ThisTestUser** [comment]
Added you as a friend, accept it to see my PM.
