### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by THERALWEAN231** [java-deobfuscator/deobfuscator#176]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:106)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:466)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:85)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:361)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:47)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
You need to send your JAR file.

**Comment by samczsun** [comment]
Assuming it's stringer, try the latest commit. Otherwise provide the sample next time
