### ISSUE TITLE
New problem help!!!!!

### ISSUE THREAD

**Issue by Ellidium** [java-deobfuscator/deobfuscator#177]
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - The specified output JAR already exists!
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 0 source filenames

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.StringIndexOutOfBoundsException: String index out of range: 10
        at java.lang.String.charAt(Unknown Source)
        at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:177)
        at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:110)
        at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:166)
        at com.javadeobfuscator.org.objectweb.asm.commons.ClassRemapper.visit(ClassRemapper.java:70)
        at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:400)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:283)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:243)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

C:\Users\roman\Desktop\ggg>pause

Help to decipher file:
[Pleeezzzz.zip](https://github.com/java-deobfuscator/deobfuscator/files/1486397/Pleeezzzz.zip)

**Comment by samczsun** [comment]
Try using [general.removers.IllegalSignatureRemover](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/general/removers/IllegalSignatureRemover.java)
