### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by sennyy** [java-deobfuscator/deobfuscator#178]
`Transforming

[Stringer] [HideAccessTransformer] Starting
[Stringer] [HideAccessTransformer] Found 1 decryptors
Deobfuscation failed. Please open a ticket on GitHub
java.lang.ArrayIndexOutOfBoundsException: 6
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.Type.getType(Type
.java:474)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.Type.getReturnTyp
e(Type.java:380)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.Type.getReturnTyp
e(Type.java:600)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObf
uscationTransformer.lambda$null$18(HideAccessObfuscationTransformer.java:233)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObf
uscationTransformer.lambda$transform$19(HideAccessObfuscationTransformer.java:21
4)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Sour
ce)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknow
n Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObf
uscationTransformer.transform(HideAccessObfuscationTransformer.java:214)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:172)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)`

file: 
http://www120.zippyshare.com/v/7anyeLoS/file.html

already used Stringer.StringEncryptionTransformer 
i tried to use
stringer.HideAccessObfuscationTransformer and errors at the top

**Comment by ThisTestUser** [comment]
[SimpleObf-0.1.1 (1).zip](https://github.com/java-deobfuscator/deobfuscator/files/1504637/SimpleObf-0.1.1.1.zip)
You may be using an older version of deobfuscator.jar, or the builds may be outdated.

**Comment by sennyy** [comment]
@ThisTestUser why the strings are still obfuscated? can you do something for deobfuscate them please??

**Comment by FireMasterK** [comment]
Rename it to a .jar File.....

**Comment by samczsun** [comment]
FYI: try the latest transformers: `stringer.v3.HideAccessTransformer`, `stringer.v3.InvokedynamicTransformer`, `stringer.v3.StringEncryptionTransformer`, `stringer.v3.ResourceEncryptionTransformer`
