### ISSUE TITLE
Invalid access flags

### ISSUE THREAD

**Issue by NoChanceSD** [java-deobfuscator/deobfuscator#18]
I got this error while attempting to deobfuscate, don't really know what is causing it, i think the classes have some checks against modifications?
`java.lang.IllegalArgumentException: Invalid access flags: 56
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.util.CheckClassAdapter.checkAccess(CheckClassAdapter.java:599)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.util.CheckClassAdapter.visit(CheckClassAdapter.java:377)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:622)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:322)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$5(Deobfuscator.java:179)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:177)
        at Main.main(Main.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)`

**Comment by samczsun** [comment]
Please send the obfuscated jar to submit@javadeobfuscator.com with the subject "Issue #18"

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists
