### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by onemoreplays** [java-deobfuscator/deobfuscator#183]
Hello,
so today I tried to deobfuscate and deobfuscator threw me this error.

`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.transformers.smoke.StringEncryptionTransformer.lambda$null$2(StringEncryptionTransformer.java:84)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.smoke.StringEncryptionTransformer.lambda$transform$3(StringEncryptionTransformer.java:50)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.smoke.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:49)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:302)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Unknown Source)`

**Comment by ThisTestUser** [comment]
Send us your file.

**Comment by onemoreplays** [comment]
[deob-input.zip](https://github.com/java-deobfuscator/deobfuscator/files/1585939/deob-input.zip)

**Comment by ThisTestUser** [comment]
The file doesn't use smoke, it only uses name obfuscation.

**Comment by onemoreplays** [comment]
Oh okay and can that obfuscation be removed?

**Comment by Janmm14** [comment]
No, name obfuscation can't be reversed because the original information is not present anymore.
