### ISSUE TITLE
NPE Allatori 4.7 DEMO  CLI and GUI 

### ISSUE THREAD

**Issue by rucko24** [java-deobfuscator/deobfuscator#185]
Hi, good project
trying to use this throws me _NPE_  testing on LINUX

```
public class Deobfuscators {
    private static final String JRE_RT_JAR = "/opt/jdk1.8.0_92/jre/lib/rt.jar";
    private static final String JRE_JCE_JAR = "/opt/jdk1.8.0_92/jre/lib/jce.jar";
    private static final String JRE_JFXRT_JAR = "/opt/jdk1.8.0_92/jre/lib/ext/jfxrt.jar";
    private static final String LIB_TOOLS_JAR = "/opt/jdk1.8.0_92/lib/tools.jar";

    private static final String INPUT_JAR  = "/home/rubn/TEST.jar";
    private static final String OUTPUT_JAR = "/home/rubn/test2.jar";

    public Deobfuscators() {
        Configuration config = new Configuration();
        config.setInput(new File(INPUT_JAR));
        config.setOutput(new File(OUTPUT_JAR));
        config.setPath(Arrays.asList(
                new File(JRE_RT_JAR),
                new File(JRE_JCE_JAR),
                new File(JRE_JFXRT_JAR),
                new File(LIB_TOOLS_JAR)
        ));

        List<TransformerConfig> transformers = new ArrayList<TransformerConfig>();
        transformers.add(TransformerConfig.configFor(Transformers.Allatori.STRING_ENCRYPTION));
        config.setTransformers(transformers);
        //config.setTransformers(Arrays.asList(TransformerConfig.configFor(PeepholeOptimizer.class)));
        try {
            new Deobfuscator(config).start();
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }
    }
    public static void main(String... args) {
        new Deobfuscators();
    }
}
```

```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
[Allatori] [StringEncryptionTransformer] Starting
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$null$2(StringEncryptionTransformer.java:61)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$transform$3(StringEncryptionTransformer.java:55)
	at java.util.HashMap$Values.forEach(HashMap.java:980)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:54)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:302)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:262)
	at cracks.Unecrom2.Deobfuscators.<init>(Deobfuscators.java:52)
	at cracks.Unecrom2.Deobfuscators.main(Deobfuscators.java:61)


```

**GUI**

```
Thread-0] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-0] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-0] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-0] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-0] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
[Allatori] [StringEncryptionTransformer] Starting

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$null$2(StringEncryptionTransformer.java:61)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$transform$3(StringEncryptionTransformer.java:55)
	at java.util.HashMap$Values.forEach(HashMap.java:980)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:54)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:302)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by ThisTestUser** [comment]
You need to provide your JAR file for us to fix it.

**Comment by rucko24** [comment]
HI , 

here https://drive.google.com/file/d/1KYHppXos5m2LCD0QiLAF-GWcKr3jNVWK/view?usp=sharing

**Comment by samczsun** [comment]
Thanks. I'll take a look later if I have time

**Comment by samczsun** [comment]
```java
    public static void main(String[] args) throws Throwable {
        System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "DEBUG");
        Configuration config = new Configuration();
        config.setInput(sample("allatori", "TEST.jar"));
        config.setOutput(output(sample("allatori", "TEST.jar")));
        config.setPath(Arrays.asList(
                new File("C:\\Program Files\\Java\\jdk_8\\jre\\lib\\rt.jar"),
                new File("C:\\Program Files\\Java\\jdk_8\\jre\\lib\\jce.jar")
        ));
        config.setVerify(true);
        config.setTransformers(Arrays.asList(
                TransformerConfig.configFor(com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.class)
        ));
        new Deobfuscator(config).start();
    }
```

```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
[Allatori] [StringEncryptionTransformer] Starting
[Allatori] [StringEncryptionTransformer] Decrypted 7191 encrypted strings
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
[Allatori] [StringEncryptionTransformer] Removed 7 decryption methods
[Allatori] [StringEncryptionTransformer] Done
```

Works fine for me

**Comment by rucko24** [comment]
**works** for me too. thanks a lot.  

Please close this.

**Comment by ThisTestUser** [comment]
[TESTDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1607901/TESTDeob.zip)
And here is the file with Allatori's flow obfuscation removed.
