### ISSUE TITLE
stringer.StringEncryptionTransformer: Deobfuscation failed

### ISSUE THREAD

**Issue by HernanMora** [java-deobfuscator/deobfuscator#186]
Hi
I'm trying to deobfuscate an internal jar with Stringer but i getting this exception and fails

```
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for org/apache/commons/lang/ArrayUtils remove(Ljava/lang/Object;I)Ljava/lang/Object; @ org/apache/commons/lang/ArrayUtils remove([Ljava/lang/Object;I)[Ljava/lang/Object;
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1356)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$null$8(ReflectionObfuscationTransformer.java:192)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$decrypt$9(ReflectionObfuscationTransformer.java:108)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.decrypt(ReflectionObfuscationTransformer.java:107)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:57)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:302)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:262)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

Regards

**Comment by samczsun** [comment]
You need to provide the sample

**Comment by HernanMora** [comment]
Unfortunately I can not publish the jar file ... that's how I was trying

```
public static void main(String[] args) throws Throwable {
        System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "DEBUG");
        Configuration config = new Configuration();
        config.setInput(new File("/tmp/obfuscated.jar"));
        config.setOutput(new File("/tmp/output.jar"));
        config.setPath(Arrays.asList(
                new File("/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/rt.jar"),
                new File("/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/jce.jar"),
                ...
        ));
        config.setVerify(true);
        config.setTransformers(Arrays.asList(
                TransformerConfig.configFor(Transformers.Stringer.STRING_ENCRYPTION),
                TransformerConfig.configFor(Transformers.Stringer.INVOKEDYNAMIC),
                TransformerConfig.configFor(Transformers.Stringer.HIDEACCESS_OBFUSCATION),
                TransformerConfig.configFor(Transformers.Stringer.REFLECTION_OBFUSCATION),
                TransformerConfig.configFor(Transformers.Stringer.RESOURCE_ENCRYPTION)
        ));
        new Deobfuscator(config).start();    
}
```

**Comment by samczsun** [comment]
There's not much I can do without access to the sample. You could try using the newer Stringer transformers (`com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer`) or you could try writing your own

**Comment by samczsun** [comment]
Closing due to inactivity
