### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: 35

### ISSUE THREAD

**Issue by kangarko** [java-deobfuscator/deobfuscator#187]
De-obfuscation failed completely.

Contact me at kangarkoo(at)gmail.com for the program. It's a small 295kb resource used for malicious purposes such as cracking digitally sold resources.

Config:
```
input: program.jar
output: program_deobf.jar
path:
  - "C:\\Program Files\\Java\\jre1.8.0_152\\lib\\rt.jar"
transformers:
  #- stringer.StringEncryptionTransformer
  - normalizer.ClassNormalizer: {}
    normalizer.FieldNormalizer: {}
```

The error:
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following e
rror:
java.lang.StringIndexOutOfBoundsException: String index out of range: 35
        at java.lang.String.charAt(Unknown Source)
        at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.pars
eType(SignatureReader.java:177)
        at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.acce
pt(SignatureReader.java:108)
        at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapSignature(
Remapper.java:166)
        at com.javadeobfuscator.org.objectweb.asm.commons.ClassRemapper.visit(Cl
assRemapper.java:70)
        at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNod
e.java:400)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNor
malizer.lambda$transform$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNor
malizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:311)
        at com.javadeobfuscator.deobfuscator.transformers.DelegatingTransformer.
transform(DelegatingTransformer.java:28)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:311)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:271)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)
```

**Comment by samczsun** [comment]
Try running `IllegalSignatureRemover` as the very first transformer. If that doesn't work, let me know and I'll reach out

**Comment by kangarko** [comment]
```
Thanks, I experimented a bit and found a solution that works:

input: program.jar
output: program_deobf.jar
path:
  - "C:\\Program Files\\Java\\jre1.8.0_152\\lib\\rt.jar"
transformers:
  - dasho.StringEncryptionTransformer
  #- zelix.ReflectionObfuscationTransformer
  #- zelix.FlowObfuscationTransformer
  - general.removers.SyntheticBridgeRemover
  - general.removers.IllegalVarargsRemover
  - general.removers.IllegalSignatureRemover
  - general.removers.LocalVariableRemover
  #- normalizer.PackageNormalizer
  #- normalizer.MethodNormalizer
  #- normalizer.SourceFileClassNormalizer
  #- normalizer.DuplicateRenamer
  - general.peephole.PeepholeOptimizer
```
