### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by MoweME** [java-deobfuscator/deobfuscator#188]
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.String.substring(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:147)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:140)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapMethodName(CustomRemapper.java:48)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$null$9(MethodNormalizer.java:194)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer$$Lambda$16/219473051.accept(Unknown Source)
        at java.util.HashMap$KeySet.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$remap$10(MethodNormalizer.java:193)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer$$Lambda$11/2072948307.accept(Unknown Source)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.remap(MethodNormalizer.java:36)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:325)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:112)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

What can i do now?

**Comment by samczsun** [comment]
Provide the sample in case there's a bug, or increase the max heap space

**Comment by MoweME** [comment]
I've used this start command: java -XX:-UseGCOverheadLimit -jar deobfuscator.jar --config config.yml
Normally, it should work like that.

**Comment by samczsun** [comment]
No, you need to use `-Xmx`

**Comment by MoweME** [comment]
Thank you, can you post an example command with that?

**Comment by samczsun** [comment]
https://stackoverflow.com/questions/5374455/what-does-java-option-xmx-stand-for
