### ISSUE TITLE
Stringer v3 indy Transformer fails with "call site initialization exception"

### ISSUE THREAD

**Issue by MiniDigger** [java-deobfuscator/deobfuscator#189]
using build 44 from the ci.  it is confirmed that stringer 3.0 was used from the sample. It's also claimed that the default settings were used.  
config
```
input: BSE.jar
output: BSE-deobf.jar
path:
 - C:\Program Files\Java\jre1.8.0_151\lib\rt.jar
detect: false
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.v3.InvokedynamicTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.v3.HideAccessTransformer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.v3.CleanupTransformer
```
log
```
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - The specified output JAR already exists!
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 131ms
[main] INFO com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer - Decrypted 371 strings
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.v3.InvokedynamicTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 30ms

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.javavm.exceptions.StacktraceException: Thread: 1 main Message: call site initialization exception
        at java.lang.Object.<init>(Unknown Source)
        at java.lang.Throwable.<init>(Unknown Source)
        at java.lang.Error.<init>(Unknown Source)
        at java.lang.LinkageError.<init>(Unknown Source)
        at java.lang.BootstrapMethodError.<init>(Unknown Source)
        at java.lang.invoke.CallSite.makeSite(Unknown Source)
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(Unknown Source)
        at java.lang.invoke.MethodHandleNatives.linkCallSite(Unknown Source)
        at me.JordanDev.BSE.premium.cmc.Decrypt0(cmc.java)
```
sample (zip so that github can upload it, just remove .zip)
[BSE.jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/1606088/BSE.jar.zip)

while you are looking at that sample it also might be worth to look at the stringn encryption transformer, it spits out chinese symbols and unknown code points.

**Comment by samczsun** [comment]
Thanks. Will take a look later today

**Comment by ThisTestUser** [comment]
It looks like the JAR file has been corrupted, which means that the plugin won't even run in a server.

**Comment by samczsun** [comment]
^ Unfortunately JavaVM doesn't print all exceptions properly yet

**Comment by FasterSpeed** [comment]
Dzieki za plugin cioto NARA frajerze

**Comment by Janmm14** [comment]
Lol this is one year old and the plugin jar confirmed totally broken and undeobfuscatable and therefore useless.
