### ISSUE TITLE
NoClassInPathException: java/lang/Object

### ISSUE THREAD

**Issue by JackDn** [java-deobfuscator/deobfuscator#19]
I'm getting this error message when trying to deobfuscate something:
`com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: java/lang/Object
	at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:230)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)`

I've tried multiple transformers, none of them worked.
I am running OpenJDK 8 on Ubuntu 16.04.

**Comment by samczsun** [comment]
Did you add the jre to the path?

**Comment by JackDn** [comment]
Sorry, I read too quickly. It worked fine after adding rt.jar.
