### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Artuto** [java-deobfuscator/deobfuscator#197]
Hi, I'm getting a `com.javadeobfuscator.javavm.exceptions.ExecutionException: UnsatisfiedLinkError: java/io/UnixFileSystem initIDs()V` error. I have enabled the following transformers:

```
 - com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
 - com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer
```

Complete error: https://gist.github.com/ArtutoGamer/518229c91b1374816dc2e9fd95d76ad0

I also tried to swtich the positions and nothing. And the first transformer (EnchancedString...) works fine... (runs before)

**Comment by samczsun** [comment]
Ah, my bad. JavaVM has been updated to address this already but I haven't had the time to update the deobfuscator itself. Perhaps this weekend I'll be able to get that done

**Comment by ArtutoGamer** [comment]
If it was only updating a dep on the pom file I could make a PR if you wan't

**Comment by HolyRSPS** [comment]
Is it fixed yet?

**Comment by ArtutoGamer** [comment]
nope

El 10/02/2018 10:58 a.m., "HolyRSPS" <notifications@github.com> escribió:

Is it fixed yet?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/java-deobfuscator/deobfuscator/issues/197#issuecomment-364671752>,
or mute the thread

**Comment by joshuashaffer** [comment]
The version of deobfuscator-javavm that's in maven doesn't have the file 'nativeimpls/java_io_UnixFileSystem.class'. Forcing it to use git version of javavm fixes this.

**Comment by Janmm14** [comment]
@joshuashaffer he basically said that already

**Comment by joshuashaffer** [comment]
Vielen dank für die Blumen, @Janmm14.

**Comment by l29ah** [comment]
Gist link is dead. Is this the same problem?
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.javavm.exceptions.ExecutionException: UnsatisfiedLinkError: sun/misc/Unsafe isBigEndian0()Z
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1209)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.VirtualMachine.initialize(VirtualMachine.java:897)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:94)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.VirtualMachine.initialize(VirtualMachine.java:897)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:94)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.VirtualMachine.initialize(VirtualMachine.java:897)
	at com.javadeobfuscator.javavm.VirtualMachine.initialize(VirtualMachine.java:883)
	at com.javadeobfuscator.javavm.VirtualMachine.initialize(VirtualMachine.java:883)
	at com.javadeobfuscator.javavm.VirtualMachine.fullInitialization(VirtualMachine.java:138)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:168)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer.transform(SimpleStringEncryptionTransformer.java:74)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
	Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
		at sun.misc.Unsafe.<clinit>(Unsafe.java:1233)
		at sun.misc.SharedSecrets.<clinit>(SharedSecrets.java:47)
		at java.lang.ref.Reference.<clinit>(Reference.java:235)
```
