### ISSUE TITLE
Error on trying deobfuscate jar

### ISSUE THREAD

**Issue by DavidNery** [java-deobfuscator/deobfuscator#198]
I am trying deobfuscate a jar with Allatori String Obfuscation, but I am get the next error:

> [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at org.apache.commons.io.output.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:366)
        at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:722)
        at com.javadeobfuscator.deobfuscator.utils.Utils.loadBytes(Utils.java:396)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:155)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

My run.bat is:
`java -Xss2G -jar deobfuscator.jar --config config.yml
pause`

**Comment by ThisTestUser** [comment]
You have to send the JAR file.

**Comment by zFork** [comment]
[Jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/1665389/Jar.zip)

**Comment by ThisTestUser** [comment]
[TintaPunirDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1665442/TintaPunirDeob.zip)I used an older version of the deobfuscator.

**Comment by zFork** [comment]
What's version you have used?
