### ISSUE TITLE
OutOfMemoryError Problem

### ISSUE THREAD

**Issue by MrGriefer** [java-deobfuscator/deobfuscator#200]
I'm trying to deobfuscate a jar with SourceFileClassNormalizer which I got from the detect thing.
And when trying to deobfuscate it. It gave me the error OutOfMemoryError error:
`java.lang.OutOfMemoryError: Java heap space
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1157)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:94)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:113)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

I've tried increasing the ram but still no luck, the command I used to run:
`"C:\Program Files\Java\jre1.8.0_151\bin\java" -Xmx1024m -jar deobfuscator-1.0.0.jar --config config.yml`
I'm using Java 8 64bit version and tried it on my other laptop 32bit system and still the same error.

**Comment by Janmm14** [comment]
Try 2 or 3 gb ram maybe

**Comment by Wetitpig** [comment]
This also applies to GC Overhead error
