### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by xRetrox** [java-deobfuscator/deobfuscator#202]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:495)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.DictionaryMethodProvider.invokeMethod(DictionaryMethodProvider.java:48)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.DictionaryMethodProvider.invokeMethod(DictionaryMethodProvider.java:48)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.DictionaryMethodProvider.invokeMethod(DictionaryMethodProvider.java:48)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$null$8(ReflectionObfuscationTransformer.java:192)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$decrypt$9(ReflectionObfuscationTransformer.java:108)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.decrypt(ReflectionObfuscationTransformer.java:107)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:57)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

Bat file:
 java -Xmx1024m -jar deobfuscator.jar --config detect.yml
PAUSE

detect.yml: 
input: file.jar
output: fileDE.jar
detect: false
transformers:
  - stringer.StringEncryptionTransformer
  - stringer.ReflectionObfuscationTransformer (This transformer makes the problem)

**Comment by xRetrox** [comment]
Bat file:
 java -Xmx1024m -jar deobfuscator.jar --config detect.yml
PAUSE

detect.yml: 
input: BullGuard.jar
output: BullGuardDE.jar
detect: false
transformers:
  - stringer.InvokedynamicTransformer
  - stringer.StringEncryptionTransformer
  - stringer.ReflectionObfuscationTransformer

**Comment by Janmm14** [comment]
Try updating.

**Comment by xRetrox** [comment]
Update what? I am using the latest version.

**Comment by Janmm14** [comment]
Oh, I thought everything was updated to the new javavm executor.

**Comment by ThisTestUser** [comment]
Try using HideAccessObfuscation transformer instead of reflectionobfuscationtransfromer.
