### ISSUE TITLE
Deobfuscation failed while detecting after first deobfuscation

### ISSUE THREAD

**Issue by jcweaver997** [java-deobfuscator/deobfuscator#203]
[deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1697173/deob.zip)
First, I detected, and found com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer as a transformer. 
Second I deobfuscated, and ran out of heap. So i switched to 64 bit java and gave it a custom Xmx. It then deobfuscated correctly. 
Third, following the guide, I detected the output.jar, and I got this error:
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 251
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1162)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
Both files before and after obfuscation are zipped and attached

**Comment by FireMasterK** [comment]
There's no point using SourceFileClassNormalizer as the source names are changed.
