### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by fuwwy** [java-deobfuscator/deobfuscator#205]
```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.visitVarInsn(MethodNode.java:433)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1476)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:94)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:113)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
```
input: input.jar
output: output.jar
transformers:
 - normalizer.PackageNormalizer
path:
 - C:\Program Files\Java\jre1.8.0_144\lib\rt.jar
 - spigot-api-1.8.8-R0.1-SNAPSHOT-latest.jar
 - spigot-1.7.10-SNAPSHOT-b1657.jar
 - spigot-1.7.2-R0.4-SNAPSHOT-1339.jar
 - spigot-1.7.9-R0.2-SNAPSHOT-1486.jar
 - spigot-1.7.5-R0.1-SNAPSHOT-1387.jar
 - BungeeCord-1290.jar
 - spigot-1.10.2-R0.1-SNAPSHOT (1).jar
 - spigot-1.9.2-R1.jar
```

I'm having this error when trying to deobfuscate a file, I'm already using -Xmx2G so I don't think it would be a memory problem. Here's the file I'm trying to deobfuscate: https://cdn.discordapp.com/attachments/378243976261533697/411218477366509569/NetinAuth_v4.5_-_Full-Edition.jar
I'm not sure if that URL is accessible to please let me know if it's isn't.

**Comment by samczsun** [comment]
Looks like I might need to rework the whole classpath situation since you're running out of memory while loading all the jars specified in path. Bit busy this week and the following week however so this'll have to wait

**Comment by Enteerman** [comment]
#642
