### ISSUE TITLE
NoClassInPathException: com/google/common/base/Predicate

### ISSUE THREAD

**Issue by guerryer** [java-deobfuscator/deobfuscator#21]
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: com/google/common/base/Predicate
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:240)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

`` java -jar deobfuscator.jar -input input.jar -output output.jar -transformer general.SyntheticBridgeTransformer -path "C:\Program Files\Java\jre1.8.0_91\lib\rt.jar" ``

* Java 8 Update 91 (64-bit)
* Windows 10

**Comment by samczsun** [comment]
maybe read the docs and add it to your path

**Comment by guerryer** [comment]
:(

**Comment by Janmm14** [comment]
?
