### ISSUE TITLE
An issue with Zelix string...

### ISSUE THREAD

**Issue by gabe56f** [java-deobfuscator/deobfuscator#210]
If i use: com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer

I always get this error:

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1157)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1015)
        at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:162)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:39)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

I don't know why it is happening...

**Comment by FireMasterK** [comment]
You are not allocating enough ram

**Comment by ThisTestUser** [comment]
You have to attach your file.

**Comment by Enteerman** [comment]
Since it's an old issue, I will close this. If you still have the problem, you can open another issue.
