### ISSUE TITLE
StringIndexOutOfBoundsException Error

### ISSUE THREAD

**Issue by MrGriefer** [java-deobfuscator/deobfuscator#212]
For some reason I'm getting an StringIndexOutOfBoundsException when deobfuscating:

> Deobfuscation failed. Please open a ticket on GitHub and provide the following e
rror:
java.lang.StringIndexOutOfBoundsException: String index out of range: 37
        at java.lang.String.charAt(Unknown Source)
        at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.pars
eType(SignatureReader.java:177)
        at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.acce
pt(SignatureReader.java:108)
        at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapSignature(
Remapper.java:166)
        at com.javadeobfuscator.org.objectweb.asm.commons.ClassRemapper.visit(Cl
assRemapper.java:70)
        at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNod
e.java:400)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNor
malizer.lambda$transform$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNor
malizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

**Comment by Janmm14** [comment]
use IllegalSignatureRemover before
