### ISSUE TITLE
Stringer (3.0.3) & ZKM (idk but not 9 I think)

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator#213]
Hello, I try to deobf a file with Stringer & ZKM so I do `stringer.v3.CleanupTransformer` then `zelix.FlowObfuscationTransformer` then `zelix.string.EnhancedStringEncryptionTransformer` but it gives me that : 

`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.javavm.exceptions.ExecutionException: Expecting to find Array on type, instead found class java.lang.Object on JavaUnknown(type=Ljava/lang/Object;,cause=Invocation on kn C(I)Ljava/lang/Object;)
        at com.javadeobfuscator.javavm.instructions.ArrayLoadInstruction.execute(ArrayLoadInstruction.java:34)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1111)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1044)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1025)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:131)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
        Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
                at E.b(E.java)
                at E.Decryptor(E.java)`

I launch with that `java -Xmx4096m -jar deobfuscator-1.0.0.jar --config config.yml`

**Comment by ThisTestUser** [comment]
You have to attach your file.

**Comment by bksrbv** [comment]
Attach my file ? Hum how ?

**Comment by bksrbv** [comment]
[DM.zip](https://github.com/java-deobfuscator/deobfuscator/files/1741780/DM.zip)

**Comment by masste** [comment]
fucking skiddo @bksrbv

**Comment by ThisTestUser** [comment]
[dmDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1748272/dmDeob.zip)
(Only deobbed JAR)

**Comment by bksrbv** [comment]
How did you do ?

**Comment by bksrbv** [comment]
Can you explain ?
