### ISSUE TITLE
Cannot deobfuscate file

### ISSUE THREAD

**Issue by deobproblems** [java-deobfuscator/deobfuscator#215]
Unable to deobfuscate the included file.
It's obfuscated with ZKM.

Exception in thread "main" java.lang.RuntimeException: Method code too large!
	at com.javadeobfuscator.org.objectweb.asm.MethodWriter.getSize(MethodWriter.java:2059)
	at com.javadeobfuscator.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:861)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:504)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$7(Deobfuscator.java:308)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$$Lambda$276/528011943.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:306)
	at Main.main(Main.java:66)

Also if I try using Zelix SimpleStringEncryptionTransformer on it:

Exception in thread "main" com.javadeobfuscator.javavm.exceptions.ExecutionException: UnsatisfiedLinkError: java/lang/ClassLoader$NativeLibrary findBuiltinLib(Ljava/lang/String;)Ljava/lang/String;
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1209)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.VirtualMachine.fullInitialization(VirtualMachine.java:140)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:168)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer.transform(SimpleStringEncryptionTransformer.java:74)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at Main.main(Main.java:66)
	Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
		at java.lang.ClassLoader.loadLibrary0(Unknown Source)
		at java.lang.ClassLoader.loadLibrary(Unknown Source)
		at java.lang.Runtime.loadLibrary0(Unknown Source)

**Comment by deobproblems** [comment]
[PSClient.zip](https://github.com/java-deobfuscator/deobfuscator/files/1764864/PSClient.zip)
The extension is .jar but had to change it to be able to upload it

**Comment by ThisTestUser** [comment]
[PSClientDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1764929/PSClientDeob.zip)

**Comment by deobproblems** [comment]
Mind explaining me how you managed to?

**Comment by ByteCode-InfiniteLeaks** [comment]
> Exception in thread "main" java.lang.RuntimeException: Method code too large!

lol

Just disable the check in ASM for too large methods.
