### ISSUE TITLE
Told to Post issue (won't deob)

### ISSUE THREAD

**Issue by LandyLane** [java-deobfuscator/deobfuscator#217]
**_Detection:_**
`java -jar deober.jar --config detect.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleStringDecryptorWithThread: Stringer's string encryption
 classes are very complex. One variety uses multithreading in order to make emulation difficult
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found possible string decryption class d$d
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    com.javadeobfuscator.deobfuscator.transformers.stringer.
v3.StringEncryptionTransformer
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleSuspiciousClinit: Zelix Klassmaster typically embeds de
cryption code in <clinit>. This sample may have been obfuscated with Zelix Klassmaster
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found suspicious <clinit> in d$B
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    None
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleEnhancedStringEncryption: Zelix Klassmaster has several
 modes of string encryption. This mode is similar to the simple mode, but adds an additional layer of decryption by call
ing a method with signature (II)Ljava/lang/String;
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found potential enhanced string encrypted class d$M
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    com.javadeobfuscator.deobfuscator.transformers.zelix.str
ing.EnhancedStringEncryptionTransformer`

**_Deob Attempt:_**
`java -jar "deober.jar" --config config.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stri
nger.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 76 encrypted strings
Could not find classnode java.lang.Class
Exception in thread "Thread-2" com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException: java.lang.Class
        at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaClass.<init>(JavaClass.java:61)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:405)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.jav
a:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:
35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.jav
a:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:
35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaThread.lambda$start$1(JavaThread.java:52)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-4" Exception in thread "Thread-3" java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:474)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.jav
a:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:
35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaThread.lambda$start$1(JavaThread.java:52)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:474)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.jav
a:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:
35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaThread.lambda$start$1(JavaThread.java:52)
        at java.lang.Thread.run(Unknown Source)

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:474)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionT
ransformer.java:331)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptio
nTransformer.java:50)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

Files: (includes jar to deob, config and detect files).
If you do post a deobed version, let me know my mistakes. Thanks!
[deober.zip](https://github.com/java-deobfuscator/deobfuscator/files/1799041/deober.zip)

**Comment by ItzSomebody** [comment]
add the appropriate libraries to the path

**Comment by LandyLane** [comment]
@ItzSomebody The jar is standalone and doesn't require any additional libraries to run if thats what your inferring to.

**Comment by Janmm14** [comment]
you need to include standard java libraries too

**Comment by LandyLane** [comment]
Thanks have it working but a new issue:

> [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
> 	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1157)
> 	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
> 	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
> 	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
> 	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:94)
> 	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:113)
> 	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
> 	at deob.RunDeob.main(RunDeob.java:24)

Tried giving more memory as well in eclipse by adding the VM arguments: -Xss190m as well as 128 initially shown in the main page.

**Comment by ThisTestUser** [comment]
[launcherDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1799791/launcherDeob.zip)
Requires some JByteMod editing to fully deobfuscate

**Comment by LandyLane** [comment]
@ThisTestUser Thanks, but it seems the results are similar to jd-gui; was hoping for more readable code. Thanks anyways.

**Comment by ThisTestUser** [comment]
Use FernFlower (Bytecode viewer)
