### ISSUE TITLE
obfustication failed?

### ISSUE THREAD

**Issue by vip3r011** [java-deobfuscator/deobfuscator#220]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
        at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
        at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
        at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
        at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.invokedynamic.Invokedynamic2Transformer.transform(Invokedynamic2Transformer.java:44)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

[pt.zip](https://github.com/java-deobfuscator/deobfuscator/files/1821923/pt.zip)

**Comment by vip3r011** [comment]
wrong java version used, i had 9 on, 8 works 100%
