### ISSUE TITLE
Deobfuscation failed.

### ISSUE THREAD

**Issue by Revelacyjny** [java-deobfuscator/deobfuscator#224]
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(Unknown Source)
	at java.util.zip.ZipFile.getZipEntry(Unknown Source)
	at java.util.zip.ZipFile.access$900(Unknown Source)
	at java.util.zip.ZipFile$ZipEntryIterator.next(Unknown Source)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(Unknown Source)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:167)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
You're sure the input file isnot corrupted?
