### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Imperdible** [java-deobfuscator/deobfuscator#229]
java.lang.StringIndexOutOfBoundsException: String index out of range: 11
	at java.lang.String.charAt(Unknown Source)
	at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:177)
	at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.acceptType(SignatureReader.java:130)
	at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:164)
	at com.javadeobfuscator.org.objectweb.asm.commons.MethodRemapper.visitLocalVariable(MethodRemapper.java:214)
	at com.javadeobfuscator.org.objectweb.asm.tree.LocalVariableNode.accept(LocalVariableNode.java:109)
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:821)
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
	at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Unknown Source)

**Comment by ThisTestUser** [comment]
Use IllegalSignatureRemover first.

**Comment by Imperdible** [comment]
ok
