### ISSUE TITLE
Errors in deobfuscation

### ISSUE THREAD

**Issue by Wetitpig** [java-deobfuscator/deobfuscator#231]
There is an error in deobfuscating [this](https://file.town/download/n7pxjb2fu2rajmjpdr56dkbaf) file:
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:419)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1022)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1022)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1036)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1036)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:277)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.ConstantFolder.lambda$null$2(ConstantFolder.java:43)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.ConstantFolder.lambda$transform$3(ConstantFolder.java:39)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.ConstantFolder.transform(ConstantFolder.java:38)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

COnfig:
`input: ../classes-1.jar`
`path:`
`        - ../android.jar`
`        - ../com.google.anroid.maps.jar`
`        - ../org.apache.http.legacy.jar`
`output: ../classes-2.jar`
`transformers:`
`        - general.peephole.ConstantFolder`
`        - general.peephole.GotoRearranger`
`        - general.peephole.UnconditionalSwitchRemover`
`        - general.peephole.RedundantTrapRemover`
`        - general.peephole.PeepholeOptimizer`
`        - general.peephole.TrapHandlerMerger`
 `       - general.peephole.DeadCodeRemover`
`        - general.peephole.LdcSwapInvokeSwapPopRemover`
`        - general.removers.IllegalSignatureRemover`
`        - general.removers.IllegalVarargsRemover`
`        - general.removers.LineNumberRemover`
`        - general.removers.LocalVariableRemover`
`        - general.removers.SyntheticBridgeRemover`

What has happened? Thanks

**Comment by Janmm14** [comment]
The peepholeoptimizer does call all other peephole transformers.

**Comment by ThisTestUser** [comment]
[liteloader-1.7.10Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1934016/liteloader-1.7.10Deob.zip)

**Comment by ThisTestUser** [comment]
Your file was originally an android file, and when it was converted into a jar file it got corrupted.

**Comment by Wetitpig** [comment]
But I only received this error when deobfuscating the already deobfuscated jar. (i.e. a second round of deobfuscation).

**Comment by ThisTestUser** [comment]
There isn't anything to deobfuscate.

**Comment by Wetitpig** [comment]
But the dedexifier showed no errors in  changing from dex to jar.

**Comment by Wetitpig** [comment]
So u mean the code is originally written in smali?

**Comment by ThisTestUser** [comment]
Well, the JAR you gave isn't obfuscated anymore.

**Comment by Wetitpig** [comment]
This is the deobfuscated version already...

**Comment by Wetitpig** [comment]
I mean the description said that layering obfusxation is possible, so I want to see if I can deobfuscate once more...

**Comment by ThisTestUser** [comment]
Actually, peephole transformers don't work well with converted JAR files, so the version you gave is the most deobfuscated it can get.

**Comment by Wetitpig** [comment]
So what transformer can the converted jar work with?

**Comment by Janmm14** [comment]
Your jar can't be fixed by java-deobfuscator. As ThisTestUser said, the jar is already deobfuscated.

**Comment by Wetitpig** [comment]
Thanks

**Comment by ThisTestUser** [comment]
In that case, the deobfuscation is done then. The deobfuscated JAR you gave is most it can deobfuscate.

**Comment by Wetitpig** [comment]
Thanks
