### ISSUE TITLE
AnalyzerException: Error at instruction 18: Illegal LDC constant 5000

### ISSUE THREAD

**Issue by GitPotTime** [java-deobfuscator/deobfuscator#232]
Sorry for my english, i'm french and don't speak English very well..

I try to deobfuscate the file [liteloader-1.7.10.jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/1931763/liteloader-1.7.10.jar.zip) using the gui.
My config is ```java -jar C:\Users\Antoine\Desktop\deobuscator\deobfuscator.jar -input C:\Users\Antoine\Desktop\vape-V2-launcher\liteloader-1.7.10.jar -output C:\Users\Antoine\Desktop\vape-v2-launcher-deobf.jar -transformer allatori.string.StringEncryptionTransformer -transformer general.peephole.PeepholeOptimizer -transformer general.peephole.RedundantTrapRemover -transformer general.peephole.GotoRearranger -transformer general.peephole.DeadCodeRemover -transformer general.peephole.ConstantFolder -transformer general.peephole.UnconditionalSwitchRemover -transformer general.peephole.TrapHandlerMerger -transformer general.peephole.LdcSwapInvokeSwapPopRemover -transformer general.removers.IllegalVarargsRemover -transformer general.removers.LineNumberRemover -transformer general.removers.SyntheticBridgeRemover -transformer general.removers.LocalVariableRemover -transformer general.removers.IllegalSignatureRemover -transformer normalizer.SourceFileClassNormalizer -path D:\Devellopement\jdk1.8.0_131\lib\tools.jar -path D:\Devellopement\jdk1.8.0_131\jre\lib\rt.jar -path D:\Devellopement\jdk1.8.0_131\jre\lib\jce.jar -path D:\Devellopement\jdk1.8.0_131\jre\lib\ext\jfxrt.jar -path D:\Devellopement\jdk1.8.0_131\jre\lib\ext\zipfs.jar -path D:\Devellopement\jdk1.8.0_131\lib\dt.jar -path D:\Devellopement\jdk1.8.0_131\lib\visualvm\visualvm\core\locale\core_visualvm.jar```

The error log is 
```[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 5521ms
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main$1 run()V: Launcher update available
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main$1 run()V: Update?
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main$1 h(Ljava/lang/String;Ljavafx/scene/control/ButtonType;)V: RunDll32.exe "
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main$1 h(Ljava/lang/String;Ljavafx/scene/control/ButtonType;)V: ",main
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main$2 run()V: .jar
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main$2 run()V: .dll
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main$2 run()V: java -jar "
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main$2 run()V: "
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main h(Ljava/lang/String;Ljava/lang/String;)V: User-Agent
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main h(Ljava/lang/String;Ljava/lang/String;)V: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main h(Ljava/lang/String;Ljava/lang/String;)V: Content-Length
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main h(Ljava/lang/String;Ljava/lang/String;)V: Error code 
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main h(Ljava/lang/String;)[B: MD5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main m(Ljava/lang/String;)Ljava/lang/String;: GET
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main m(Ljava/lang/String;)Ljava/lang/String;: User-Agent
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main m(Ljava/lang/String;)Ljava/lang/String;: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: http://
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: /download.php?check=true&version=
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: http://
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: /download.php?update=true&type=jar&version=
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: http://
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: /download.php?update=true&type=dll&version=
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: More than two files in folder.
Move files into own folder or Vape may not work properly.
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: Warning
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: .dll
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: No dll found.
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: Warning
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: Using dll: 
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: RunDll32.exe "
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main main([Ljava/lang/String;)V: ",main
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main h()Z: More than two files in folder.
Vape will not update.
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main h()Z: Error
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in c/Main h()Z: .jar
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted 33 strings
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer
Removed 0 redundant traps
Rearranged 0 goto blocks
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover - Removed 16 dead instructions
Removed 0 unconditional switches
Removed 0 ldc-swap-invoke-swap-pop patterns
Folded 16 constants
Removed 0 redundant traps
Rearranged 0 goto blocks





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 18: Illegal LDC constant 5000
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:298)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:35)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer.transform(PeepholeOptimizer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Illegal LDC constant 5000
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.BasicInterpreter.newOperation(BasicInterpreter.java:145)
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.BasicInterpreter.newOperation(BasicInterpreter.java:52)
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:270)
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:200)
	... 11 more
```
Thanks

**Comment by ThisTestUser** [comment]
https://github.com/java-deobfuscator/deobfuscator/files/1934016/liteloader-1.7.10Deob.zip

**Comment by Janmm14** [comment]
You also used an outdated version of the deobfuscator. Current version works with config files.

**Comment by ThisTestUser** [comment]
I used my version of the string encryption transformer and a custom allatori flow fixer.
https://github.com/ThisTestUser/deobfuscator/tree/master
