### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Imperdible** [java-deobfuscator/deobfuscator#234]
java.lang.ArrayIndexOutOfBoundsException: 6842
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readStringish(ClassReader.java:2659)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readClass(ClassReader.java:2676)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1628)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Unknown Source)

**Comment by Wetitpig** [comment]
Do you use config.yml or java? Can you post the config source?

**Comment by Imperdible** [comment]
im just using the gui(s)

**Comment by Wetitpig** [comment]
So what did u input?

**Comment by Wetitpig** [comment]
Sorry I use the CLI

**Comment by Imperdible** [comment]
i inputted the jar i wanted to deobfuscate (ofc) and then i used the transformers i wanted which is for zkm

**Comment by Janmm14** [comment]
error basically says a file in the jar is corrupted- alternatively its an error in the bytecode library used.

**Comment by Wetitpig** [comment]
do u hv the source jar?
