### ISSUE TITLE
another error

### ISSUE THREAD

**Issue by Imperdible** [java-deobfuscator/deobfuscator#235]
java.lang.OutOfMemoryError: Java heap space
	at java.lang.String.substring(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:133)
	at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapType(Remapper.java:80)
	at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapType(Remapper.java:92)
	at com.javadeobfuscator.org.objectweb.asm.commons.MethodRemapper.visitFieldInsn(MethodRemapper.java:118)
	at com.javadeobfuscator.org.objectweb.asm.tree.FieldInsnNode.accept(FieldInsnNode.java:101)
	at com.javadeobfuscator.org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
	at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer$$Lambda$59/19747853.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.lang.Thread.run(Unknown Source)

**Comment by Wetitpig** [comment]
Use `java -Xmx<memory>`.

See java vm usage for details.
