### ISSUE TITLE
cant deobfuscate allatori

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator#236]
com.javadeobfuscator.javavm.exceptions.ExecutionException: Unexpected value: JavaUnknown(type=Ljava/lang/String;,cause=Invocation on vL ALLATORIxDEMO(Ljava/lang/String;)Ljava/lang/String;)
        at com.javadeobfuscator.javavm.values.JavaWrapper.asObject(JavaWrapper.java:161)
        at com.javadeobfuscator.javavm.VirtualMachine.convertJavaObjectToString(VirtualMachine.java:471)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:91)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
You have to send your jar file.

**Comment by xDarqus** [comment]
Please, give me your email. I can't send this jar by public way.

**Comment by xDarqus** [comment]
I added you on discord, but you must accept my invitation.
