### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lunarenzox** [java-deobfuscator/deobfuscator#245]
`
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
	at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
	at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
	at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:39)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.thistestuser.DeobfuscatorFrame$13$1.run(DeobfuscatorFrame.java:599)
	at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by ItzSomebody** [comment]
Can you attach your jar?

**Comment by lunarenzox** [comment]
@ItzSomebody i already put the input and output jar, and i also put the rt.jar on libraries, im using the gui version

**Comment by ItzSomebody** [comment]
I meant can you upload your jar to this issue thread?

**Comment by lunarenzox** [comment]
its just a plugin from minecraft that i want to deobfuscate, need to see something

**Comment by ItzSomebody** [comment]
Well we can't help you without seeing the jar you are trying to deobfuscate.

**Comment by lunarenzox** [comment]
[http://www.filedropper.com/removelag_1](url)

**Comment by FireMasterK** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/2042677/output.zip)

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/2042774/output.zip)

@lunarenzox that's allatori, not stringer.

**Comment by lunarenzox** [comment]
@ItzSomebody teach me on how you deobfuscate it plss? @FireMasterK ???

**Comment by lunarenzox** [comment]
so that i will not ask help on how to do it,
and btw that plugin has a backdoored, they give me that they say it will remove lag

**Comment by FireMasterK** [comment]
@lunarenzox you use `allatori.string.StringEncryptionTransformer` instead of `stringer.v3.StringEncryptionTransformer` because this file is obfuscated with Allatori and not Stringer

**Comment by lunarenzox** [comment]
@FireMasterK how i will know what transformer i will use?

**Comment by FireMasterK** [comment]
You need to use a decompiler and identify the obfuscator based on the decryptor method. You need to identify the pattern which you understand from experience.
