### ISSUE TITLE
The deobfuscator can't handle empty package names

### ISSUE THREAD

**Issue by Janmm14** [java-deobfuscator/deobfuscator#25]
Example jar: https://www.spigotmc.org/resources/anothercheat-anti-cheat.24323/

```
java.lang.IllegalArgumentException: Invalid class name (must be a fully qualified class name in internal form): /ç?´ç??äººç?´ç??ç??ç??/è¦?ç?´/ç?´ç??è¦
?/ä¸?/äººä¸?ç??ç?´/ä¸?/ç?´ç??ç?¼äººç?¼/ç?¼/äºº/è¦?è¦?ä¸?äººç?¼ç??ç??ç?´äººç?¼/ç?´è¦?/è¦?ç?¼ä¸?äºº/ç??ç?¼è¦?/ç??/ç?¼ä¸?ç?´ä¸?ç?¼ä¸?/ç??ç??ç??äººè¦?/é??
ç?´ç?´ç?´ç?¼ç??è¦?é??ç?´ä¸?ç??é??ä¸?ç??è§?äººç??é??äººç?´ç??è¦?è§?ç??äººäººäººè§?ç??ç??äººä¸?äººè¦?ç?¼ç??è§?è¦?è§?ç??ç??ç?¼ç??ç??ç??ç?¼ç??ç?´ç??äººé??
äººç??ç??ç??ç??äººç?¼ç??è§?äººç??ç?´ç?¼ç??è¦?ä¸?é??ç?´äººç?´ç??è¦?ç??ä¸?ç??è¦?ç??ç?´ç??HA
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.util.CheckMethodAdapter.checkInternalName(CheckMethodAdapter.java:1351)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.util.CheckMethodAdapter.checkInternalName(CheckMethodAdapter.java:1318)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.util.CheckClassAdapter.visit(CheckClassAdapter.java:383)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:622)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:322)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$5(Deobfuscator.java:179)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:177)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

**Comment by Janmm14** [comment]
Can't all the normalizations lead to isues when trying to deobfuscate strings if the string obfuscation is using exceptions as the caller class is changed by the normalization?

**Comment by samczsun** [comment]
Probably. Use with caution
