### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by Igor-Yavych** [java-deobfuscator/deobfuscator#251]
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer.transform(SimpleStringEncryptionTransformer.java:78)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
jar: https://www26.zippyshare.com/v/WkAhXuEl/file.html
Original: jar (before anything was used on it)  in case someone would be kind enough to deobfuscate it properly for me https://www21.zippyshare.com/v/qifJBSfu/file.html
Whole package, in case needed: https://goo.gl/WPAgtU (jar is at \web\WEB-INF\lib)

**Comment by ThisTestUser** [comment]
[serverDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2109319/serverDeob.zip)

**Comment by Igor-Yavych** [comment]
Thanks a lot, @ThisTestUser . If you don't mind, few questions:
- Was it in fact ZKM that was used to obfuscate this jar?
- What tools you've used and are they available publicly? 
- Can you tell me the order of what you did?
I've tried quite a few times with different tools but I've never arrived at as good results as you. It'd be great if I knew what you did for the future releases of this thing.
Once again, thank you very much.

**Comment by ThisTestUser** [comment]
1. Yes.
2. I used my own private analyzer, which requires some manual work and is not public.

**Comment by Igor-Yavych** [comment]
I see. Thank you once again.

**Comment by ThisTestUser** [comment]
[serverDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2287793/serverDeob.zip)
