### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by awesomennguy** [java-deobfuscator/deobfuscator#257]
m.javadeobfuscator.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 271: Illegal LDC constant 6
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:298)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:35)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:66)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Illegal LDC constant 6
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.BasicInterpreter.newOperation(BasicInterpreter.java:145)
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.BasicInterpreter.newOperation(BasicInterpreter.java:52)
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:270)
	at com.javadeobfuscator.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:200)
	... 10 more

**Comment by awesomennguy** [comment]
Can someone help me with this?

**Comment by ThisTestUser** [comment]
You need to send your JAR.

**Comment by Enteerman** [comment]
Open a new issue if you own the program and still have the problem.
