### ISSUE TITLE
Not working, GC overhead limit

### ISSUE THREAD

**Issue by Puyodead1** [java-deobfuscator/deobfuscator#258]
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readUTF(ClassReader.java:2645)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2596)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1596)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1016)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

I'm trying to deobfuscate  a premium SpigotMC plugin

**Comment by Puyodead1** [comment]
https://www.dl.dropboxusercontent.com/s/znlsnwgedp7hqq6/RandomPackage.zip

**Comment by ThisTestUser** [comment]
You have discord? It's risky to post premium plugins in public domain.

**Comment by Puyodead1** [comment]
RandomPackage.jar is...

**Comment by ThisTestUser** [comment]
I looked and there wasn't any obfuscation.

**Comment by Puyodead1** [comment]
when i decompile it and import into eclipse, there are a bunch of errors

**Comment by ItzSomebody** [comment]
@Puyodead1 that doesn't mean it's obfuscated.

**Comment by Puyodead1** [comment]
How can I go about decompiling it to eclipse?

**Comment by ItzSomebody** [comment]
There are plenty cases when decompiled code isn't Eclipse ready. Often, you have to correct mistakes the decompiler made in order to make the code compiler ready.
