### ISSUE TITLE
Deobfuscation failed.

### ISSUE THREAD

**Issue by Fals3R** [java-deobfuscator/deobfuscator#259]
java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:474)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:331)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:50)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

===
Config.yml:

input: TeslaCraft.jar
output: TeslaCraftDEOBF.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer

===
Detect info:

[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleStringDecryptorWithThread: Stringer's string encryption classes are very complex. One variety uses multithreading in order to make emulation difficult
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found possible string decryption class qiy/vmj/b
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer

===

**Comment by Fals3R** [comment]
https://www.upload.ee/files/8606920/TeslaCraft.jar.html

**Comment by ThisTestUser** [comment]
You didn't attach the libraries. (rt.jar)
[TeslaCraftDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2138730/TeslaCraftDeob.zip)

**Comment by Fals3R** [comment]
All classes are empty

**Comment by ThisTestUser** [comment]
Use bytecode viewer, and use Fernflower decompiler.

**Comment by Fals3R** [comment]
can you rename this jar to random fields, please. Because all fields and class names are 'LoLkeKChEbUREk' and i cant understand :c

**Comment by ThisTestUser** [comment]
[TeslaCraftDeob1.zip](https://github.com/java-deobfuscator/deobfuscator/files/2139387/TeslaCraftDeob1.zip)
