### ISSUE TITLE
Allatori issue

### ISSUE THREAD

**Issue by SinnicK** [java-deobfuscator/deobfuscator#26]
#When I try to deob Allatori jar file ofuscated I get:

```
> java -jar deobfuscator.jar -input test.jar -output output.jar -transformer allatori.StringEncryptionTransformer
> Warning! Output file already exists
> 
> Reading complete. Loading hierachy
> 
> Deobfuscation failed. Please open a ticket on GitHub
> com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: java/lang/Object
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:230)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
>         at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
>         at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Hope u can fix it soon, if you need I can upload the test file.

**Comment by samczsun** [comment]
Add jre to path

**Comment by SinnicK** [comment]
@samczsun hi bro, thanks for your support. The same problem....
I've added the jre path like this: (maybe is wrong way)

`java -jar deob.jar -input input.jar -output output.jar -transformer allatori.StringEncryptionTransformer -path "C:\Program Files\Java\jre1.8.0_91"`

**Comment by samczsun** [comment]
You can only add individual JAR files or a directory (which will include all JAR files in that directory, non recursive)

**Comment by SinnicK** [comment]
@samczsun oh I got it, now I used this code:
`java -jar deob.jar -input input.jar -output output.jar -transformer allatori.StringEncryptionTransformer -path lib/`

Where "lib" is the directory that contains all *.jars but same error...

```
java -jar deob.jar -input input.jar -output output.jar -transformer allatori.StringEncryptionTransformer -path lib/
Warning! Output file already exists

Reading complete. Loading hierachy

Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: java/lang/Object
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:230)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```
Do you want the jar file to see it? Thanks.

**Comment by Janmm14** [comment]
Try to add the rt.jar in the lib folder of the jre installation for now. it includes the base of java classes and should normally be enough.

**Comment by SinnicK** [comment]
Great @Janmm14, that works! Thanks to both.
