### ISSUE TITLE
 -> stringer.v3.StringEncryptionTransformer -> Can't decompile completely

### ISSUE THREAD

**Issue by TheNamedMeFilip** [java-deobfuscator/deobfuscator#263]
Hello, i want to deobfuscate two plugins.

One is MiniAnni - some things are decompiled but some not.
One si Anni        - it stuck at Initialization of VM took XXXms

These two plugins are from another developers but they are using
same obfuscation protection
-------------------------------------------------------------------

Can you please deobfuscate it for me ? 

Thanks, 
Filip.

[plugins.zip](https://github.com/java-deobfuscator/deobfuscator/files/2154584/plugins.zip)

**Comment by ThisTestUser** [comment]
It's recommended to use stringer.StringEncryptionTransformer and then stringer.HideAccessObfuscationTransformer for large files.
[Plugins.zip](https://github.com/java-deobfuscator/deobfuscator/files/2155503/Plugins.zip)

**Comment by TheNamedMeFilip** [comment]
i canť open the file you sended. Please send it again. Thanks very much

**Comment by TheNamedMeFilip** [comment]
Can you btw explain why i'm stuck here?:

**Comment by TheNamedMeFilip** [comment]
C:\Users\F JAKO FRAJER\Desktop\deob>java -jar deobfuscator-1.0.0.jar --config config.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 134 source filenames
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 287ms

**Comment by ThisTestUser** [comment]
You have to use SourceFileClassNormalizer after you use string encryption transformer.

**Comment by TheNamedMeFilip** [comment]
I don't understand.

my config:

input: input.jar // im setting another names
output: output.jar // im setting another names
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.stringer.v3.StringEncryptionTransformer

my detect:

input: input.jar // im setting another names
detect: true

Send me good config :D thanks

**Comment by ThisTestUser** [comment]
Switch the positions of SourceFile normalizer and string encryption transformer.

**Comment by TheNamedMeFilip** [comment]
Thanks. I cant deobfuscate this plugin: 
[plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/2156020/plugin.zip)
`[Thread-79] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-79] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-79] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-79] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-79] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 1413 encrypted strings
[Stringer] [StringEncryptionTransformer] Done 10%
[Stringer] [StringEncryptionTransformer] Done 20%
[Stringer] [StringEncryptionTransformer] Done 30%
[Stringer] [StringEncryptionTransformer] Done 40%
[Stringer] [StringEncryptionTransformer] Done 50%
[Stringer] [StringEncryptionTransformer] Done 60%
[Stringer] [StringEncryptionTransformer] Done 70%
[Stringer] [StringEncryptionTransformer] Done 80%
[Stringer] [StringEncryptionTransformer] Done 90%
[Stringer] [StringEncryptionTransformer] Done 100%
[Stringer] [StringEncryptionTransformer] Decrypted 1413 encrypted strings
[Stringer] [StringEncryptionTransformer] Removed 18 decryption classes
[Stringer] [StringEncryptionTransformer] Done
[Thread-79] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer
[Stringer] [HideAccessTransformer] Starting
[Stringer] [HideAccessTransformer] Found 7 decryptors
Could not find classnode java.lang.System





** DO NOT OPEN AN ISSUE ON GITHUB **
Could not locate a class file.
Have you added the necessary files to the -libraries argument?
The error was:
com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException: java.lang.System
	at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaClass.<init>(JavaClass.java:61)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$1$24.lambda$new$0(JVMMethodProvider.java:353)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$Function3.applyUnchecked(JVMMethodProvider.java:768)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider.invokeMethod(JVMMethodProvider.java:685)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$null$4(HideAccessObfuscationTransformer.java:138)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$5(HideAccessObfuscationTransformer.java:120)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:119)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)
`

yeah i know its by not added library but i dont know what library to add.... i will be really happy if you will 
decompile it for me... :D or explain what im doing bad

**Comment by ThisTestUser** [comment]
[LuckyRaceDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2156086/LuckyRaceDeob.zip)

**Comment by TheNamedMeFilip** [comment]
I'm sorry that i'm annoying you--> but i can't edit it because it's class...

can you deobfuscate it and send me just the plugin? Please.

**Comment by ThisTestUser** [comment]
You have to use a Java decompiler yourself.

**Comment by TheNamedMeFilip** [comment]
so put the zip in decompiler ?

**Comment by ThisTestUser** [comment]
Download Bytecode viewer, and click file and decompile and save all classes.

**Comment by TheNamedMeFilip** [comment]
it have so much errors

**Comment by TheNamedMeFilip** [comment]
can you make me source code for eclipse without errors?

**Comment by ThisTestUser** [comment]
You have to add the libraries for the project yourself. Most of the errors are not because of the code.

**Comment by TheNamedMeFilip** [comment]
I added all libraries such as bukkit and vault, but it makes some errors

**Comment by ThisTestUser** [comment]
You probably need Java knowledge to fix the rest of the classes.

**Comment by TheNamedMeFilip** [comment]
Can you just make from jar i sended you create jar without obfuscation please? thanks a lot for helping me.
[LuckyRace Plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/2160137/LuckyRace.Plugin.zip)

**Comment by ThisTestUser** [comment]
I already did that, it's called LuckyRaceDeob.zip.

**Comment by TheNamedMeFilip** [comment]
Ok. thanks. 

Btw. Can you send me folder with files and configs you used for these plugins? (like in zip and there will be deobfuscator and config + optionaly detect).. i will really appreciate.

**Comment by ThisTestUser** [comment]
I used Deobfuscator-GUI (https://github.com/java-deobfuscator/deobfuscator-gui/releases), and used stringer.StringEncryptionTransformer and then stringer.HideAccessTransformer. I also added all the required libraries, like Vault, rt.jar, and the spigot jars.

**Comment by TheNamedMeFilip** [comment]
stringer.HideAccessTransformer.. i dont found that... i found stringet.v3.HideAccesTransformer
