### ISSUE TITLE
Can't run detector

### ISSUE THREAD

**Issue by flamingLion** [java-deobfuscator/deobfuscator#266]
I need to deobfuscate a file. But whenever I try to use the detect feature to find which transformers I need to use, it says it's detecting, then just stops. No error report, nothing for me to go off of, and no clue which transformers to use.

**Comment by flamingLion** [comment]
http://www.filedropper.com/xursor006pre-alpha here is the file

**Comment by ThisTestUser** [comment]
Use PackageNormalizer and ClassNormalizer to fix the long names.

**Comment by flamingLion** [comment]
Are the only ones I need to use?

**Comment by flamingLion** [comment]
The obfuscator they used makes some files just become null. Are there any other transformers I can use to fix that?

**Comment by flamingLion** [comment]
Also, when I try to decompile with fernflower, I get this error:
java.lang.NullPointerException
        at g.a(Unknown Source)
        at bK.<init>(Unknown Source)
        at bW.a(Unknown Source)
        at bW.<init>(Unknown Source)
        at bW.<init>(Unknown Source)
        at i.a(Unknown Source)
        at i.a(Unknown Source)
        at i.a(Unknown Source)
        at de.fernflower.main.decompiler.ConsoleDecompiler.addSpace(Unknown Sour
ce)
        at de.fernflower.main.decompiler.ConsoleDecompiler.main(Unknown Source)

I decompiled it the first time with JDcore and most of the cecompiled files only contained null.

**Comment by flamingLion** [comment]
Also, when I try to decompile with fernflower, I get this error:
java.lang.NullPointerException
at g.a(Unknown Source)
at bK.(Unknown Source)
at bW.a(Unknown Source)
at bW.(Unknown Source)
at bW.(Unknown Source)
at i.a(Unknown Source)
at i.a(Unknown Source)
at i.a(Unknown Source)
at de.fernflower.main.decompiler.ConsoleDecompiler.addSpace(Unknown Sour
ce)
at de.fernflower.main.decompiler.ConsoleDecompiler.main(Unknown Source)

I decompiled it the first time with JDcore and most of the decompiled files only contained null.

**Comment by ThisTestUser** [comment]
Use Bytecode viewer.

**Comment by flamingLion** [comment]
Thanks, worked like a charm.
