### ISSUE TITLE
com.javadeobfuscator.javavm.exceptions.ExecutionException: Unexpected value

### ISSUE THREAD

**Issue by WhoJoinGitHub** [java-deobfuscator/deobfuscator#268]
**Hi, my code below:**
`
Configuration config = new Configuration();
        config.setInput(new File("/Users/hellboy/Developer/jeesite4/jeesite-framework-4.0.4-SNAPSHOT.jar"));
        config.setOutput(new File("/Users/hellboy/Developer/jeesite4/jeesite-framework-4.0.4-SNAPSHOT.jar-out.jar"));
        config.setPath(Arrays.asList(new File("/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/lib/jre/lib/rt.jar"),
                new File("/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/lib/jre/lib/jce.jar"),
                new File("/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/lib/jre/lib/ext/jfxrt.jar"),
                new File("/Users/hellboy/Developer/jeesite4/jeesite-common-4.0.4-SNAPSHOT.jar"),
                new File("/Users/hellboy/Developer/jeesite4/beetl-2.7-SNAPSHOT.jar"),
                new File("/Users/hellboy/Developer/jeesite4/shiro-spring-1.4.0.jar"),
                new File("/Users/hellboy/Developer/jeesite4/spring-beans-4.3.14.RELEASE.jar"),
                new File("/Users/hellboy/Developer/jeesite4/spring-core-4.3.14.RELEASE.jar"),
                new File("/Users/hellboy/Developer/jeesite4/spring-context-4.3.14.RELEASE.jar"),
                new File("/Users/hellboy/Developer/jeesite4/quartz-2.3.0.jar"),
                new File("/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/lib/jre/lib/tools.jar")));

        config.setTransformers(Arrays.asList(
                TransformerConfig.configFor(SourceFileClassNormalizer.class),
                TransformerConfig.configFor(StringEncryptionTransformer.class), 
                TransformerConfig.configFor(ClassNormalizer.class)
        ));

        new Deobfuscator(config).start();
`

When run this code, throw an exception:

        Exception in thread "main" com.javadeobfuscator.javavm.exceptions.ExecutionException: Unexpected value: JavaUnknown(type=Ljava/lang/String;,cause=Invocation on com/jeesite/common/io/ResourceUtils getResourceFileContent(Ljava/lang/String;)Ljava/lang/String;)
    at com.javadeobfuscator.javavm.values.JavaWrapper.asObject(JavaWrapper.java:161)
    at com.javadeobfuscator.javavm.VirtualMachine.convertJavaObjectToString(VirtualMachine.java:471)
    at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:92)
    at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
    at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
    at com.example.Main.main(Main.java:36)

My files can download from this link:https://www.filedropper.com/deobfuscator-files

**Comment by ThisTestUser** [comment]
[jeesite-framework-4.0.4-SNAPSHOTDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2159863/jeesite-framework-4.0.4-SNAPSHOTDeob.zip)

**Comment by WhoJoinGitHub** [comment]
Thanks
