### ISSUE TITLE
Deobfuscation failed :(

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator#269]
I have error
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse .class (is it a class file?)
java.lang.IllegalArgumentException
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:185)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 43697
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:171)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:185)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

**Comment by fikawka** [comment]
https://www30.zippyshare.com/v/rSeCK1kO/file.html

**Comment by ThisTestUser** [comment]
Yeah, it appears that the classes are fake. One way to fix this would be to catch the exception that is causing the error, as the class wouldn't be loaded anyway.

**Comment by ThisTestUser** [comment]
Also, are you sure that your file is runnable?

**Comment by fikawka** [comment]
This is the Minecraft security client and fps client.
https://www1.zippyshare.com/v/zblydmsK/file.html

**Comment by fikawka** [comment]
yes work

**Comment by ThisTestUser** [comment]
So what is Test.jar?

**Comment by ThisTestUser** [comment]
Do the JARs need to be together to run?

**Comment by fikawka** [comment]
I think so, but I'm not sure.

**Comment by ItzSomebody** [comment]
Sigma client is doing something similar, I'm guessing some class encryption is involved.

**Comment by ThisTestUser** [comment]
I'll try running this in a VM to see if this works.

**Comment by fikawka** [comment]
I found one strange class that did not have a name, but after removing it, the game stopped working

**Comment by ThisTestUser** [comment]
Do you have a crash report or something similar to that? Also, try removing some other "broken" classes to see if it still works.

**Comment by ThisTestUser** [comment]
I've done a bit of digging, and it seems that the classes are probably decrypted via a native library.

**Comment by fikawka** [comment]
new version: https://www85.zippyshare.com/v/jBQydnba/file.html
