### ISSUE TITLE
Deobfuscation failed.

### ISSUE THREAD

**Issue by Fals3R** [java-deobfuscator/deobfuscator#270]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.javavm.exceptions.VMException: java.lang.Throwable
 at com.javadeobfuscator.javavm.VirtualMachine.newThrowable(VirtualMachine.java:1849)
 at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:48)
 at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
 at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
 at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
 at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
 at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1111)
 at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1044)
 at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1025)
 at com.javadeobfuscator.deobfuscator.transformers.stringer.v3_1.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:76)
 at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
 at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
 at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
 at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Throwable
 at com.javadeobfuscator.javavm.exceptions.VMException.<init>(VMException.java:28)
 ... 19 more

Obfuscation:  Stringer 3.1.3
File: https://www.upload.ee/files/8649937/checker-1.8.9-obf.jar.html

**Comment by ItzSomebody** [comment]
[deobbed.zip](https://github.com/java-deobfuscator/deobfuscator/files/2172466/deobbed.zip)

That's allatori and stringer combined.

**Comment by Janmm14** [comment]
Well there's apparantly not that much can be looked at easily cuz of the dll's.
Also avira says its adware: https://www.virustotal.com/#/file-analysis/OTZiNzllZGFiYzJkZTM2NDg4OTliYWVmNjZjOGFmNWI6MTUzMDk3NTcxOQ==
