### ISSUE TITLE
Deobfuscation failed.

### ISSUE THREAD

**Issue by CustomETB** [java-deobfuscator/deobfuscator#273]
```javascript
java -Xss1G -jar deobfuscator.jar --config config.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.visitInsn(MethodNode.java:423)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1466)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:94)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:118)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

```

**Comment by CustomETB** [comment]
´´´
java -Xss2000M -jar deobfuscator.jar --config config.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.visitFieldInsn(MethodNode.java:444)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1598)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:94)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:118)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
´´´

**Comment by CustomETB** [comment]
```
java -Xss2000M -jar deobfuscator.jar --config config.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readUTF(ClassReader.java:2645)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2596)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1595)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:94)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:113)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

**Comment by ItzSomebody** [comment]
Increase the allocated memory size using -Xmx

**Comment by Janmm14** [comment]
Yes, Xss is the wrong memory size you're increasing.

**Comment by CustomETB** [comment]
with 2000mb of ram, same problem

**Comment by ItzSomebody** [comment]
Consider allocating some more ram

**Comment by CoderMarido** [comment]
Run it on a virtual private server or something because it does clearly need more RAM.

**Comment by ItzSomebody** [comment]
If you attach the jar here, I'll take a crack at deobfing it.

**Comment by Janmm14** [comment]
It probably doesn't need more ram, it looks more like deobfuscation with existing transformers just doesn't work.

**Comment by ItzSomebody** [comment]
To me, it looks more like the JVM runs out of heap space when loading the classpath.

**Comment by CustomETB** [comment]
[mamapap.zip](https://github.com/java-deobfuscator/deobfuscator/files/2243011/mamapap.zip)

**Comment by Enteerman** [comment]
#642
