### ISSUE TITLE
Deobfuscation failed :\

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#277]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Unknown Source)
	at java.lang.String.<init>(Unknown Source)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readUTF(ClassReader.java:2645)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2596)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1595)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1016)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

Obfuscation: Allatori
File: https://www.upload.ee/files/8731931/JSC_Front_Mod__OBF_.jar.html

**Comment by ThisTestUser** [comment]
Try using JVMMethodProvider.java from here:
https://github.com/ThisTestUser/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/executor/defined/JVMMethodProvider.java
Also take other files if you have compile errors.

**Comment by ThisTestUser** [comment]
[JSC_Front_Mod__OBF_Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2233720/JSC_Front_Mod__OBF_Deob.zip)
