### ISSUE TITLE
NoSuchMethodHandlerException - java/lang/reflect/Method hashCode()I

### ISSUE THREAD

**Issue by SchoolsCool** [java-deobfuscator/deobfuscator#28]
While deobfuscating stringer with your program, I found an error, which as follows ------
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 6342 encrypted strings
Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/reflect/Method hashCode()I
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1060)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:33)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1131)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:53)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:33)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1131)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:203)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:61)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

(Newest version of stringer, I have a dl if you want it)

**Comment by Janmm14** [comment]
This looks like a simple code change, we just have to tell the deobfuscator that its allowed to call hashcode.

**Comment by SchoolsCool** [comment]
Alright, thanks for the response.

**Comment by samczsun** [comment]
Please send the obfuscated jar to submit@javadeobfuscator.com with the subject "Issue #28"

**Comment by SchoolsCool** [comment]
Did you get the file?

**Comment by samczsun** [comment]
Yes. Many things changed so this may take a while

**Comment by SchoolsCool** [comment]
Oh okay, can you give me an estimate?

**Comment by samczsun** [comment]
Expect an update in a few days
