### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by BolaBLG** [java-deobfuscator/deobfuscator#281]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.visitLineNumber(MethodNode.java:601)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1422)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by fikawka** [comment]
give your jar

**Comment by Janmm14** [comment]
Only in case you are allowed to share it
Like no spigotmc premium plugins

**Comment by rettlsteiner** [comment]
@BolaBLG Please start your deobfuscator like this: java **-Xmx6144M** -jar DECOMPILER.jar --config CONFIG.yml

**Comment by rettlsteiner** [comment]
@Janmm14 He could send the name of the plugin. There're websites that do that for us, like BSMC, or DL.

**Comment by Janmm14** [comment]
I'm sure everyone has 6gb of ram free. Not. Try to start with -Xmx2G

**Comment by Enteerman** [comment]
#642
