### ISSUE TITLE
OutOfMemoryError - GC overhead limit exceeded

### ISSUE THREAD

**Issue by MrGriefer** [java-deobfuscator/deobfuscator#285]
I'm getting this error when trying to deobfuscate:
`Deobfuscation failed. Please open a ticket on GitHub and provide the following e
rror:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readUTF(ClassReade
r.java:2645)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readUTF8(ClassRead
er.java:2596)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readStringish(Clas
sReader.java:2659)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readClass(ClassRea
der.java:2676)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassRe
ader.java:981)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader
.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader
.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deob
fuscator.java:94)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfusc
ator.java:113)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:246)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)`

And this is my config.yml:
`input: deobf.jar
output: plugin-deobf.jar
path:
 - C:\Program Files\Java\jre1.8.0_151\lib\rt.jar
 - C:\Users\\Desktop\1.12\spigot-1.12.2.jar
 - C:\Users\\Desktop\My Folder\All Spigot Versions\spigot-1.11.2.jar
transformers:
 - general.removers.IllegalSignatureRemover
 - normalizer.SourceFileClassNormalizer`

I used this code to run:
`"C:\Program Files\Java\jre1.8.0_151\bin\java" -Xmx2g -jar deobfuscator-1.0.0.jar --config config.yml`

**Comment by ItzSomebody** [comment]
Increase the Xmx flag.

**Comment by MrGriefer** [comment]
I tried -Xmx3g and I got OutOfMemoryError: Java heap space
