### ISSUE TITLE
Deobfuscation failed allatori ThisTestUser version

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator#286]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
Why u removed a part of the error?

**Comment by fikawka** [comment]
Allatori string deobfuscation

**Comment by ItzSomebody** [comment]
Check if the error persists when you don’t use deobfuscator-gui
