### ISSUE TITLE
Deobfuscation failed :C

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#289]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.visitFieldInsn(MethodNode.java:444)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1598)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1016)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.invokedynamic.Invokedynamic2Transformer.transform(Invokedynamic2Transformer.java:44)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

Obfuscation: Allatori, Stringer
File: https://www.upload.ee/files/8827293/Launcher_OBF.jar.html

**Comment by Janmm14** [comment]
Try with -Xmx1G or -Xmx2G (not more)

**Comment by ThisTestUser** [comment]
[Launcher_OBFDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2297639/Launcher_OBFDeob.zip)
