### ISSUE TITLE
Allatori Deobfuscation problem

### ISSUE THREAD

**Issue by MarioDraghi** [java-deobfuscator/deobfuscator#29]
I tried to deobfuscate allatori but that's the result :+1: 

`C:\Users\x0r\Desktop>java -jar deob.jar -input andro.jar -output fanis.jar -transformer allatori.StringEncryptionTransformer

Reading complete. Loading hierachy

Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: javax/swing/JFrame
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:230)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)`

maybe because i haven't set the -path ? if yes , could you explain me which file should i put in the -path ? i don't understand very well ! sorry i'm korean.

**Comment by Janmm14** [comment]
See #19 or #26.
You need to find the path of your java installation, usually thats `"C:\Program Files\Java\jre1.x_xx\"`
After that path, you usually just need to reference to the `rt.jar` file inside the `lib` folder. If you see this error and the error message starting with `java/`, `javax/`, `com/sum`, `sun/` (maybe I missed some), try adding more jar files of the lib folder through additional `-path `.

**Comment by MarioDraghi** [comment]
Ok as i thought i missed the -path parameter but i've just added it and the problem it's always there :

that's my command

C:\Users\x0r\Desktop>java -jar deob.jar -input andro.jar -output fanis.jar -transformer allatori.StringEncryptionTransformer -path C:\Program Files (x86)\Java\jre1.8.0_91\
Warning! Output file already exists
Could not find classpath file C:\Program

Reading complete. Loading hierachy

Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: javax/swing/JFrame
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:230)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)



that's probably because ( as you can see in the log ) it can't ready the blank space in the path of java !
 

"Could not find classpath file C:\Program" <========== it stucks here !

how can i solve ? should i install the x64 version to avoid that directory ?

**Comment by Janmm14** [comment]
You need to use double quotes `"` around a path with spaces.

**Comment by MarioDraghi** [comment]
Many thanks and sorry for my noobness ! now it seems to work but i have another problem !

C:\Users\x0r\Desktop>java -jar deob.jar -input andro.jar -output fanis.jar -transformer allatori.StringEncryptionTransformer -path "C:\Program Files (x86)\Java\jre1.8.0_91\lib\rt.jar"

Reading complete. Loading hierachy


Transforming

Deobfuscation failed. Please open a ticket on GitHub
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$null$1(StringEncryptionTransformer.java:63)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$transform$2(StringEncryptionTransformer.java:51)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:50)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by Janmm14** [comment]
If you are using the latest version (I assume), this is a case where @samczsun might be needed.
For me it looks like a method of a class which can't be found is referenced. Maybe you need to add some more -path.

**Comment by MarioDraghi** [comment]
Sure ! i'm using the last version.
instead , the version of allatori it's 5.6.

Could you explain me what do you mean for "add some more -path" ? can i upload the jar file somewhere to let you check personally ? ( if its not a problem ! )

**Comment by Janmm14** [comment]
I don't eant to check jar files, but @samczsun does it. However you should wait until he replies here.

You could still take a look at it with a java decompiler gui like Helios (download: https://ci.samczsun.com/job/Bootstrapper/ )

**Comment by MarioDraghi** [comment]
Thanks @Janmm14  ,

Unfortunately i already tried using Bootstrapper without any success.

I will wait for @samczsun  to understand better :)

regards

**Comment by Janmm14** [comment]
I just got the same issue as https://github.com/java-deobfuscator/deobfuscator/issues/29#issuecomment-227393158 and I'm going to create a new issue for that, because the jar I have seems to not be obfuscated by allatori.

**Comment by Janmm14** [comment]
@MarioDraghi
Are you sure its allatori string obfuscation?
I just digged a bit and noticed this error happens if any other class is referenced inside the deobfuscation method, which allatori normally doesn't do.

**Comment by MarioDraghi** [comment]
@Janmm14 

Yes , navigating with dirty joe it's clear to see functions called "allatoriXdemo" so i think the jar it's obfuscated by allatori

**Comment by samczsun** [comment]
@MarioDraghi Please send an email to submit@javadeobfuscator.com with the subject "Issue #29" and the JAR file which you cannot deobfuscate

**Comment by samczsun** [comment]
It appears the JAR is obfuscated using Stringer. Please try the stringer.InvokeDynamicTransformer and stringer.StringEncryptionTransformer instead

**Comment by MarioDraghi** [comment]
Tried but all the strings are still obfuscated. What can i do ?

**Comment by MarioDraghi** [comment]
C:\Users\x0r\Desktop>java -jar deob.jar -input andro.jar -output fanis1.jar -transformer stringer.InvokedynamicTransformer -path "C:\Program Files (x86)\Java\jre1.8.0_91\lib\rt.jar"
Warning! Output file already exists

Reading complete. Loading hierachy


Transforming

[Stringer] [InvokedynamicTransformer] Starting
[Stringer] [InvokedynamicTransformer] Finding invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Found 8793 invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Inlining invokedynamic
[Stringer] [InvokedynamicTransformer] Done 10%
[Stringer] [InvokedynamicTransformer] Done 20%
Could not find classnode javax.crypto.Cipher
main/eB
Deobfuscation failed. Please open a ticket on GitHub
java.lang.NoClassDefFoundError: javax.crypto.Cipher
        at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaClass.<init>(JavaClass.java:68)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$1$14.lambda$new$0(JVMMethodProvider.java:205)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$Function3.applyUnchecked(JVMMethodProvider.java:382)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider.invokeMethod(JVMMethodProvider.java:336)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:36)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1136)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.lambda$null$5(InvokedynamicTransformer.java:156)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.lambda$inlineInvokeDynamic$6(InvokedynamicTransformer.java:135)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.inlineInvokeDynamic(InvokedynamicTransformer.java:134)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.transform(InvokedynamicTransformer.java:62)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)


########################################################
C:\Users\x0r\Desktop>java -jar deob.jar -input fanis1.jar -output fanis1.jar -transformer stringer.StringEncryptionTransformer -path "C:\Program Files (x86)\Java\jre1.8.0_91\lib\rt.jar"

Reading complete. Loading hierachy


Transforming

[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 1694 encrypted strings
[Stringer] [StringEncryptionTransformer] Done 10%
[Stringer] [StringEncryptionTransformer] Done 20%
[Stringer] [StringEncryptionTransformer] Done 30%
[Stringer] [StringEncryptionTransformer] Done 40%
[Stringer] [StringEncryptionTransformer] Done 50%
[Stringer] [StringEncryptionTransformer] Done 60%
[Stringer] [StringEncryptionTransformer] Done 70%
[Stringer] [StringEncryptionTransformer] Done 80%
[Stringer] [StringEncryptionTransformer] Done 90%
[Stringer] [StringEncryptionTransformer] Done 100%
[Stringer] [StringEncryptionTransformer] Decrypted 1694 encrypted strings
[Stringer] [StringEncryptionTransformer] Removed 0 decryption classes
[Stringer] [StringEncryptionTransformer] Done

Transforming complete. Writing to file

Error: de/javasoft/plaf/synthetica/SyntheticaBlueLightLookAndFeel could not be found while writing main/FrameMain. Using COMPUTE_MAXS

**Comment by Janmm14** [comment]
You did not added all needed libraries. Use additional `-path` arguments.
I can tell you that you need the `jce.jar` from the directory where `rt.jar` is. But you need also a jar containing `de/javasoft/plaf/synthetica/SyntheticaBlueLightLookAndFeel`.

**Comment by MarioDraghi** [comment]
thanks @Janmm14  it worked but it's still obfuscated

Reading complete. Loading hierachy


Transforming

[Stringer] [InvokedynamicTransformer] Starting
[Stringer] [InvokedynamicTransformer] Finding invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Found 8793 invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Inlining invokedynamic
[Stringer] [InvokedynamicTransformer] Done 10%
[Stringer] [InvokedynamicTransformer] Done 20%
[Stringer] [InvokedynamicTransformer] Done 30%
[Stringer] [InvokedynamicTransformer] Done 40%
[Stringer] [InvokedynamicTransformer] Done 50%
[Stringer] [InvokedynamicTransformer] Done 60%
[Stringer] [InvokedynamicTransformer] Done 70%
[Stringer] [InvokedynamicTransformer] Done 80%
[Stringer] [InvokedynamicTransformer] Done 90%
[Stringer] [InvokedynamicTransformer] Done 100%
[Stringer] [InvokedynamicTransformer] Removed 8793 invokedynamic instructions, took 51s
[Stringer] [InvokedynamicTransformer] Cleaning up bootstrap methods
[Stringer] [InvokedynamicTransformer] Removed 0 bootstrap methods
[Stringer] [InvokedynamicTransformer] Done

Transforming complete. Writing to file


and after i've used the 2° command "stringer.StringEncryptionTransformer" with successfull decryption of 1694 strings.

still obfuscated :(

**Comment by Janmm14** [comment]
Then you maybe have to decrypt it again as it was maybe encrypted multiple times.

**Comment by MarioDraghi** [comment]
tried several times , without success. i hope @samczsun will be able to do this, coz i really tried everything :(

**Comment by MarioDraghi** [comment]
Any news @samczsun  ?

**Comment by samczsun** [comment]
Taking a look

**Comment by MarioDraghi** [comment]
@samczsun  do i have to use stringer multiple times or only one ?

**Comment by MarioDraghi** [comment]
SOLVED ! thanks to @samczsun  and @Janmm14  love you guys !

**Comment by Rujtex** [comment]
I don know what i doing this ?? help plzz
How does this work??
http://prntscr.com/lv13i9
