### ISSUE TITLE
[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occur red while parsing the configuration file

### ISSUE THREAD

**Issue by lunarenzox** [java-deobfuscator/deobfuscator#290]
I have this error while deobfuscating a jar file

[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occur
red while parsing the configuration file
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize va
lue of type `com.javadeobfuscator.deobfuscator.transformers.Transformer` from St
ring "allatori.StringEncryptionTransformer": Could not locate specified transfor
mer
 at [Source: (File); line: 7, column: 5] (through reference chain: com.javadeobf
uscator.deobfuscator.config.Configuration["transformers"]->java.util.ArrayList[1
])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(Invali
dFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringExce
ption(DeserializationContext.java:1535)
        at com.javadeobfuscator.deobfuscator.config.TransformerConfigDeserialize
r.getById(TransformerConfigDeserializer.java:99)
        at com.javadeobfuscator.deobfuscator.config.TransformerConfigDeserialize
r.deserialize(TransformerConfigDeserializer.java:69)
        at com.javadeobfuscator.deobfuscator.config.TransformerConfigDeserialize
r.deserialize(TransformerConfigDeserializer.java:34)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deser
ialize(CollectionDeserializer.java:285)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deser
ialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deser
ialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeA
ndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserial
ize(BeanDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Bea
nDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMa
pper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.ja
va:2890)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:80)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

**Comment by lunarenzox** [comment]
I use the detect.yml and it says i need to use the "zelix.string.EnhancedStringEncryptionTransformer" transformer, now i use it and it gaves me this error
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeo
bfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransfo
rmer
java.nio.file.NoSuchFileException: C:\Program Files\Java\jre-10\lib\rt.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown
Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown
 Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Sour
ce)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)

        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at com.javadeobfuscator.deobfuscator.utils.Utils.loadBytes(Utils.java:39
1)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:160)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedS
tringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51
)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)
java.nio.file.NoSuchFileException: C:\Program Files\Java\jre-10\lib\jce.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown
Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown
 Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Sour
ce)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)

        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at com.javadeobfuscator.deobfuscator.utils.Utils.loadBytes(Utils.java:39
1)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:161)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedS
tringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51
)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)
java.nio.file.NoSuchFileException: C:\Program Files\Java\jre-10\lib\jsse.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown
Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown
 Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Sour
ce)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)

        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at com.javadeobfuscator.deobfuscator.utils.Utils.loadBytes(Utils.java:39
1)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:162)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedS
tringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51
)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)





Deobfuscation failed. Please open a ticket on GitHub and provide the following e
rror:
java.lang.NullPointerException
        at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:1
78)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:
219)
        at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandli
ngHook(HookGenerator.java:73)
        at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registe
rNatives(sun_misc_URLClassPath.java:28)
        at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMac
hine.java:500)
        at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java
:124)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:167)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedS
tringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51
)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

**Comment by lunarenzox** [comment]
`I use the detect.yml and it says i need to use the "zelix.string.EnhancedStringEncryptionTransformer" transformer, now i use it and it gaves me this error
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeo
bfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransfo
rmer
java.nio.file.NoSuchFileException: C:\Program Files\Java\jre-10\lib\rt.jar
at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown
Source)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown
Source)
at java.base/java.nio.file.Files.readAttributes(Unknown Source)
at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
at java.base/java.util.zip.ZipFile$CleanableResource.(Unknown Sour
ce)
at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)

    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at com.javadeobfuscator.deobfuscator.utils.Utils.loadBytes(Utils.java:39
 at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:160)
at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedS
tringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51
)
at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)
java.nio.file.NoSuchFileException: C:\Program Files\Java\jre-10\lib\jce.jar
at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown
Source)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown
Source)
at java.base/java.nio.file.Files.readAttributes(Unknown Source)
at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
at java.base/java.util.zip.ZipFile$CleanableResource.(Unknown Sour
ce)
at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)

    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at com.javadeobfuscator.deobfuscator.utils.Utils.loadBytes(Utils.java:39
 at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:161)
at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedS
tringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51
)
at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)
java.nio.file.NoSuchFileException: C:\Program Files\Java\jre-10\lib\jsse.jar
at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown
Source)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown So
urce)
at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(U
nknown Source)
at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown
Source)
at java.base/java.nio.file.Files.readAttributes(Unknown Source)
at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
at java.base/java.util.zip.ZipFile$CleanableResource.(Unknown Sour
ce)
at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)

    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at com.javadeobfuscator.deobfuscator.utils.Utils.loadBytes(Utils.java:39
 at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:162)
at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedS
tringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51
)
at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

Deobfuscation failed. Please open a ticket on GitHub and provide the following e
rror:
java.lang.NullPointerException
at com.javadeobfuscator.javavm.mirrors.JavaClass.(JavaClass.java:1
78)
at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:
219)
at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandli
ngHook(HookGenerator.java:73)
at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registe
rNatives(sun_misc_URLClassPath.java:28)
at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMac
hine.java:500)
at com.javadeobfuscator.javavm.VirtualMachine.(VirtualMachine.java
:124)
at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:167)
at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedS
tringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51
)
at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)`

**Comment by ItzSomebody** [comment]
Use Java 8 instead of Java 10 since the runtime libraries were changed.
