### ISSUE TITLE
Normalizing

### ISSUE THREAD

**Issue by awesomennguy** [java-deobfuscator/deobfuscator#293]
[Thread-2] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-2] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-2] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-2] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-2] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Unknown Source)
	at java.lang.String.<init>(Unknown Source)
	at java.lang.String.substring(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:147)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:140)
	at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapDesc(Remapper.java:63)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapFieldName(CustomRemapper.java:118)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.lambda$remap$0(FieldNormalizer.java:70)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer$$Lambda$21/1951414710.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.remap(FieldNormalizer.java:34)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:66)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

using -xmx3g and libraries

**Comment by ItzSomebody** [comment]
`java.lang.OutOfMemoryError: GC overhead limit exceeded`

Increase the GC allocation.

**Comment by awesomennguy** [comment]
example please?
