### ISSUE TITLE
Out of memory error with DuplicateRenamer

### ISSUE THREAD

**Issue by FailedShack** [java-deobfuscator/deobfuscator#296]
I've been trying to use the obfuscator with an Android app converted to jar with dex2jar with all necessary libraries referenced. However, after a few seconds it starts eating up all of my system's resources and slowing everything down to a halt. Give it enough time and it will eventually crash with java.lang.OutOfMemoryError.

It's worth noting that I have 16 GB of RAM. At it's peak, the deobfuscator was using somewhere in the neighbourhood of 5-6 GB.

> [Thread-23] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-23] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-23] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-23] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-23] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.peephole.GotoRearranger
Rearranged 0 goto blocks
[Thread-23] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover
[Thread-23] INFO com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover - Removed 0 dead instructions
[Thread-23] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer

> Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(Unknown Source)
	at java.base/java.util.HashMap.putVal(Unknown Source)
	at java.base/java.util.HashMap.put(Unknown Source)
	at java.base/java.util.HashSet.add(Unknown Source)
	at java.base/java.util.AbstractCollection.addAll(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer.lambda$remap$13(DuplicateRenamer.java:314)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer$$Lambda$203/1912817528.accept(Unknown Source)
	at java.base/java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer.remap(DuplicateRenamer.java:302)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.base/java.lang.Thread.run(Unknown Source)

[Here's the file](https://mega.nz/#!nDpBkTLb!bxC0cA8_XdPY2ZmsUwFheAB6beRszRpfu2Pw9fDGcYw) I'm trying to deobfuscate along with all necessary libraries compressed into a single archive (it also needs rt.jar from the JRE, of course).

**Comment by ThisTestUser** [comment]
Since dex2jar files are usually extremely big, java-deobfuscator would not be the best way to normalize the names. Instead, try proguard with custom rename settings.
