### ISSUE TITLE
Deobfuscation failed.

### ISSUE THREAD

**Issue by ahmedkhlief** [java-deobfuscator/deobfuscator#304]
Hi Thank you for the tool.
Deobfuscation failed. and said to open a ticket : 

 java.lang.ArrayIndexOutOfBoundsException: 3514
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readStringish(ClassReader.java:2659)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readClass(ClassReader.java:2676)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1628)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

i used this  command  : 

java -jar deobfuscator-1.0.0.jar --config detect.yml

detect.yml : 

input: App.jar
detect: true

**Comment by ThisTestUser** [comment]
First, download the latest deobfuscator, if you haven't already.
If it doesn't work, try this version: https://github.com/ThisTestUser/deobfuscator/releases
If it still doesn't work, attach the file here.
