### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException Error

### ISSUE THREAD

**Issue by aidanwd** [java-deobfuscator/deobfuscator#307]
When using the Method deobfuscator transformer this happens:

java.lang.ArrayIndexOutOfBoundsException: 253
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1162)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source

**Comment by aidanwd** [comment]
Also, why does the string obfuscator leave some things behind when deobfing strings 
![image](https://user-images.githubusercontent.com/30511407/45919705-9d43e880-be4e-11e8-94c7-12e4878b83da.png), Also how would i deobf values like 
![image](https://user-images.githubusercontent.com/30511407/45919708-a92faa80-be4e-11e8-984e-e7bff49f2709.png)

**Comment by ThisTestUser** [comment]
You can use this version of deobfuscator.jar (use allatori.StringEncryptionTransformer): https://github.com/ThisTestUser/deobfuscator/releases/download/1.1/deobfuscator.jar
Also to deobfuscate the errored code in your second image you can use allatori.FlowObfuscationTransformer

**Comment by aidanwd** [comment]
Nice Thanks, I do have a few more issues though

**Comment by aidanwd** [comment]
Stuff like arraylistoutofbounds a lot on a few transformers

**Comment by aidanwd** [comment]
I dont believe u answered: 
When using the Method deobfuscator transformer this happens:

java.lang.ArrayIndexOutOfBoundsException: 253
at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1162)
at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
at java.lang.Thread.run(Unknown Source



Also ik it says not to open a report on github for this one but whats wrong here?:
Could not locate a class file.
Have you added the necessary files to the -libraries argument?
The error was:
com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException: java/lang/RuntimeException
	at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:337)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:404)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:370)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:463)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer.lambda$remap$12(DuplicateRenamer.java:64)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer.remap(DuplicateRenamer.java:62)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
@qisanwd did you add rt.jar in the path?

**Comment by aidanwd** [comment]
You need to add that!??!

**Comment by Janmm14** [comment]
Yes

**Comment by aidanwd** [comment]
@Janmm14 do u have a discord

**Comment by ItzSomebody** [comment]
Old issue and no sample to work off of. Closing.
