### ISSUE TITLE
Deobfuscate this?

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [java-deobfuscator/deobfuscator#313]
i get this when i try it, at one point i had the strings(what i want) deobfuscated but that was about a year ago, i cant get it to work....

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:474)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:331)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:50)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

https://www.upload.ee/files/9038881/2F4U.jar.html

**Comment by ThisTestUser** [comment]
[2F4UDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2456433/2F4UDeob.zip)

**Comment by THEREALWWEFAN231** [comment]
Thanks, how did you do it tho?

**Comment by ThisTestUser** [comment]
Use stringer.StringEncryptionTransformer from here: https://github.com/ThisTestUser/deobfuscator/releases

**Comment by ThisTestUser** [comment]
[PluginDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2462626/PluginDeob.zip)
