### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by yKsenomorf** [java-deobfuscator/deobfuscator#318]
```[main] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer - Decrypted string in net/minecraft/rO a(Lnet/minecraft/p7;Ljava/lang/String;Lnet/minecraft/oE;)Lnet/minecraft/oE;: Stronghold
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at com.javadeobfuscator.org.objectweb.asm.Type.getDescriptor(Type.java:679)
        at com.javadeobfuscator.org.objectweb.asm.Type.getDescriptor(Type.java:638)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:204)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.getSuperclass(JavaClass.java:323)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.isAssignableFrom(JavaClass.java:652)
        at com.javadeobfuscator.javavm.nativeimpls.java_lang_Object.lambda$registerNatives$6(java_lang_Object.java:92)
        at com.javadeobfuscator.javavm.nativeimpls.java_lang_Object$$Lambda$208/1004384293.execute(Unknown Source)
        at com.javadeobfuscator.javavm.hooks.HookedMethod.lambda$bind$0(HookedMethod.java:56)
        at com.javadeobfuscator.javavm.hooks.HookedMethod$$Lambda$92/1762921286.execute(Unknown Source)
        at com.javadeobfuscator.javavm.hooks.HookedMethod.execute(HookedMethod.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1191)
        at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
```

It decrypts some strings, then freezes
Increasing GC limit doesn't help
Config: https://hastebin.com/dufiyohape.css
.jar: https://4lpha.one/dl/1ajrttHY333qPtbg2u0u_2e_b49g0H_sf

**Comment by ThisTestUser** [comment]
[ZeroDayDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2489571/ZeroDayDeob.zip)

**Comment by yKsenomorf** [comment]
Thanks alot
