### ISSUE TITLE
Allatory + Synthetic/Bridge modifiers

### ISSUE THREAD

**Issue by SinnicK** [java-deobfuscator/deobfuscator#32]
Hi again, how are you? Well, I'm try to deobfucate a jar onfuscate with Allatori.

First, run the allatori command to do it and everything is OK. Now, I go to **Enigma Decompiler** to see the code and I realize that use */ Synthetic /* so I run the second command to remove this, again, everything is ok.

Well, now, when I go to see the code and with only one class the decompiler crashes and say this:

```
java.lang.IllegalArgumentException: bad position: 58
	at javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1629)
	at cuchaz.enigma.gui.CodeReader.navigateToToken(CodeReader.java:160)
	at cuchaz.enigma.gui.Gui.showToken(Gui.java:740)
	at cuchaz.enigma.gui.Gui.showTokens(Gui.java:756)
	at cuchaz.enigma.gui.GuiController.showReference(GuiController.java:280)
	at cuchaz.enigma.gui.GuiController.openReference(GuiController.java:269)
	at cuchaz.enigma.gui.GuiController.openDeclaration(GuiController.java:250)
	at cuchaz.enigma.gui.Gui.navigateTo(Gui.java:908)
	at cuchaz.enigma.gui.Gui.access$0(Gui.java:900)
	at cuchaz.enigma.gui.Gui$2.onSelectClass(Gui.java:170)
	at cuchaz.enigma.gui.ClassSelector$3.mouseClicked(ClassSelector.java:92)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
So, I extract the source and the conflict class have this within:

```javascript
public class ClassName
{
    public static void ClassName(final String a1) {
        // 
        // This method could not be decompiled.
        // 
        // Original Bytecode:
        // 
        //     0: aconst_null    
        //     1: astore_1       
        //     2: new             Ljava/io/FileOutputStream;
        //     5: dup            
        //     6: ldc             "csolver.properties"
        //     8: invokespecial   java/io/FileOutputStream.<init>:(Ljava/lang/String;)V
        //    11: astore_1       
        //    12: aload_0         /* a1 */
        //    13: aload_1        
        //    14: aconst_null    
        //    15: invokevirtual   java/util/Properties.store:(Ljava/io/OutputStream;Ljava/lang/String;)V
        //    18: aload_1        
        //    19: ifnull          75
        //    22: aload_1        
        //    23: invokevirtual   java/io/OutputStream.close:()V
        //    26: return         
        //    27: athrow         
        //    28: astore_2       
        //    29: aload_2        
        //    30: invokevirtual   java/io/IOException.printStackTrace:()V
        //    33: return         
        //    34: athrow         
        //    35: astore_2       
        //    36: aload_2        
        //    37: invokevirtual   java/io/IOException.printStackTrace:()V
        //    40: aload_1        
        //    41: ifnull          75
        //    44: aload_1        
        //    45: invokevirtual   java/io/OutputStream.close:()V
        //    48: return         
        //    49: astore_2       
        //    50: aload_2        
        //    51: invokevirtual   java/io/IOException.printStackTrace:()V
        //    54: return         
        //    55: astore_3       
        //    56: aload_1        
        //    57: ifnull          73
        //    60: aload_1        
        //    61: invokevirtual   java/io/OutputStream.close:()V
        //    64: aload_3        
        //    65: goto            74
        //    68: astore_1       
        //    69: aload_1        
        //    70: invokevirtual   java/io/IOException.printStackTrace:()V
        //    73: aload_3        
        //    74: athrow         
        //    75: return         
        //    LocalVariableTable:
        //  Start  Length  Slot  Name  Signature
        //  -----  ------  ----  ----  ----------------------
        //  0      76      0     a1    Ljava/util/Properties;
        //    Exceptions:
        //  Try           Handler
        //  Start  End    Start  End    Type                 
        //  -----  -----  -----  -----  ---------------------
        //  22     26     28     34     Ljava/io/IOException;
        //  2      18     35     55     Ljava/io/IOException;
        //  44     48     49     55     Ljava/io/IOException;
        //  2      18     55     75     Any
        //  35     40     55     75     Any
        //  60     64     68     73     Ljava/io/IOException;
        //  55     56     55     75     Any
        // 
        // The error that occurred was:
        // 
        // java.lang.IllegalStateException: Inconsistent stack size at #0074 (coming from #0065).
        //     at com.strobel.decompiler.ast.AstBuilder.performStackAnalysis(AstBuilder.java:2182)
        //     at com.strobel.decompiler.ast.AstBuilder.build(AstBuilder.java:109)
        //     at com.strobel.decompiler.languages.java.ast.AstMethodBodyBuilder.createMethodBody(AstMethodBodyBuilder.java:210)
        //     at com.strobel.decompiler.languages.java.ast.AstMethodBodyBuilder.createMethodBody(AstMethodBodyBuilder.java:99)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethodBody(AstBuilder.java:757)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:655)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:532)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
        //     at cuchaz.enigma.Deobfuscator.getSourceTree(Deobfuscator.java:224)
        //     at cuchaz.enigma.Deobfuscator.writeSources(Deobfuscator.java:306)
        //     at cuchaz.enigma.gui.GuiController$1.run(GuiController.java:110)
        //     at cuchaz.enigma.gui.ProgressDialog$1.run(ProgressDialog.java:98)
        // 
        throw new IllegalStateException("An error occurred while decompiling this method.");
    }
    
    public static Properties IiIiIiiiiiii() {
        // 
        // This method could not be decompiled.
        // 
        // Original Bytecode:
        // 
        //     0: new             Ljava/util/Properties;
        //     3: dup            
        //     4: invokespecial   java/util/Properties.<init>:()V
        //     7: astore_0       
        //     8: aconst_null    
        //     9: astore_1       
        //    10: ldc             "csolver.properties"
        //    12: astore_2       
        //    13: new             Ljava/io/FileInputStream;
        //    16: dup            
        //    17: aload_2        
        //    18: invokespecial   java/io/FileInputStream.<init>:(Ljava/lang/String;)V
        //    21: dup            
        //    22: astore_1       
        //    23: ifnonnull       75
        //    26: aconst_null    
        //    27: astore_3       
        //    28: aload_1        
        //    29: ifnull          46
        //    32: aload_1        
        //    33: invokevirtual   java/io/InputStream.close:()V
        //    36: aload_3        
        //    37: areturn        
        //    38: athrow         
        //    39: astore          4
        //    41: aload           4
        //    43: invokevirtual   java/io/IOException.printStackTrace:()V
        //    46: aload_3        
        //    47: areturn        
        //    48: nop            
        //    49: nop            
        //    50: nop            
        //    51: athrow         
        //    52: astore_3       
        //    53: aconst_null    
        //    54: astore          4
        //    56: aload_1        
        //    57: ifnull          72
        //    60: aload_1        
        //    61: invokevirtual   java/io/InputStream.close:()V
        //    64: aload           4
        //    66: areturn        
        //    67: astore_3       
        //    68: aload_3        
        //    69: invokevirtual   java/io/IOException.printStackTrace:()V
        //    72: aload           4
        //    74: areturn        
        //    75: aload_0        
        //    76: aload_1        
        //    77: invokevirtual   java/util/Properties.load:(Ljava/io/InputStream;)V
        //    80: aload_1        
        //    81: ifnull          142
        //    84: aload_1        
        //    85: invokevirtual   java/io/InputStream.close:()V
        //    88: aload_0        
        //    89: areturn        
        //    90: astore_2       
        //    91: aload_0        
        //    92: aload_2        
        //    93: invokevirtual   java/io/IOException.printStackTrace:()V
        //    96: areturn        
        //    97: astore_2       
        //    98: aload_2        
        //    99: invokevirtual   java/io/IOException.printStackTrace:()V
        //   102: aload_1        
        //   103: ifnull          142
        //   106: aload_1        
        //   107: invokevirtual   java/io/InputStream.close:()V
        //   110: aload_0        
        //   111: areturn        
        //   112: astore_2       
        //   113: aload_0        
        //   114: aload_2        
        //   115: invokevirtual   java/io/IOException.printStackTrace:()V
        //   118: areturn        
        //   119: astore          5
        //   121: aload_1        
        //   122: ifnull          139
        //   125: aload_1        
        //   126: invokevirtual   java/io/InputStream.close:()V
        //   129: aload           5
        //   131: goto            141
        //   134: astore_1       
        //   135: aload_1        
        //   136: invokevirtual   java/io/IOException.printStackTrace:()V
        //   139: aload           5
        //   141: athrow         
        //   142: aload_0        
        //   143: areturn        
        //    Exceptions:
        //  Try           Handler
        //  Start  End    Start  End    Type                 
        //  -----  -----  -----  -----  ---------------------
        //  32     36     39     46     Ljava/io/IOException;
        //  13     28     52     75     Ljava/lang/Exception;
        //  60     64     67     72     Ljava/io/IOException;
        //  84     88     90     97     Ljava/io/IOException;
        //  10     28     97     119    Ljava/io/IOException;
        //  52     56     97     119    Ljava/io/IOException;
        //  75     80     97     119    Ljava/io/IOException;
        //  106    110    112    119    Ljava/io/IOException;
        //  10     28     119    142    Any
        //  52     56     119    142    Any
        //  75     80     119    142    Any
        //  97     102    119    142    Any
        //  125    129    134    139    Ljava/io/IOException;
        //  119    121    119    142    Any
        // 
        // The error that occurred was:
        // 
        // java.lang.IllegalStateException: Inconsistent stack size at #0141 (coming from #0131).
        //     at com.strobel.decompiler.ast.AstBuilder.performStackAnalysis(AstBuilder.java:2182)
        //     at com.strobel.decompiler.ast.AstBuilder.build(AstBuilder.java:109)
        //     at com.strobel.decompiler.languages.java.ast.AstMethodBodyBuilder.createMethodBody(AstMethodBodyBuilder.java:210)
        //     at com.strobel.decompiler.languages.java.ast.AstMethodBodyBuilder.createMethodBody(AstMethodBodyBuilder.java:99)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethodBody(AstBuilder.java:757)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:655)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:532)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
        //     at cuchaz.enigma.Deobfuscator.getSourceTree(Deobfuscator.java:224)
        //     at cuchaz.enigma.Deobfuscator.writeSources(Deobfuscator.java:306)
        //     at cuchaz.enigma.gui.GuiController$1.run(GuiController.java:110)
        //     at cuchaz.enigma.gui.ProgressDialog$1.run(ProgressDialog.java:98)
        // 
        throw new IllegalStateException("An error occurred while decompiling this method.");
    }
}
```

I hope you can see what is wrong here and fix the problem.... the problem is only with one class as I said.

**Comment by SinnicK** [comment]
I tried decompile with Helios and your methods, here attached the results. Maybe can be helpful to solve.

[Fernflower.txt](https://github.com/java-deobfuscator/deobfuscator/files/329262/Fernflower.txt)
[CFR.txt](https://github.com/java-deobfuscator/deobfuscator/files/329263/CFR.txt)
[Proxyoin.txt](https://github.com/java-deobfuscator/deobfuscator/files/329264/Proxyoin.txt)

**Comment by Janmm14** [comment]
Please also try to decompile with Krakatau, it has no known decompiler vulnerabilities.

**Comment by SinnicK** [comment]
@Janmm14 I tried bro, but the result don't change, can't decompile this damn class hehe.

**Comment by SinnicK** [comment]
Hi, I discovered something interesting in this case.... After generating the "output.jar" quoted above (remove Allatori and Sync), I've applied the PeepholeOptimizer and for my surprise, whoala! The class that couldn't decompile is decompiled with successful... Really, I don't understand why this happen.

Below, I let the output that I get from the Optimizer.

```javascript
Rearranged 0 goto blocks
Removed 0 continous gotos
Removed 0 unconditional switches
**Removed 47 dead instructions**
Removed 0 nops
**Removed 2 goto unconditional jumps**
Removed 0 ldc-pop patterns
Removed 0 ldc-swap-invoke-swap-pop patterns
Removed 0 redundant traps

Transforming complete. Writing to file
```

Maybe with this, you can say some conclusion, I would like to hear your opinion to understand a little more about why this happens.

**Comment by Janmm14** [comment]
The PeepholeOptimizer is known to optimize and simplify the bytecode. Quite simple but all deobfuscators have some known issues (thats why ever decompile errors occurr; except krakatau) and it looks like the unconditional goto's were the issue in that case.

**Comment by samczsun** [comment]
Use [Helios](https://github.com/helios-decompiler/Helios) ([download](https://ci.samczsun.com/job/Bootstrapper/lastSuccessfulBuild/artifact/target/bootstrapper-0.0.6.jar))!

**Comment by SinnicK** [comment]
Hi @samczsun, sorry for re-open the issue but I have to say you that I tried with Helios (before post the issue) and the same error occurs with all decoders (CFR-Fernf-Procyon-Krak). Of course, before run Peephole Optimizer.
