### ISSUE TITLE
Help me for deob this please

### ISSUE THREAD

**Issue by NullHF** [java-deobfuscator/deobfuscator#322]
Hello can you help me please , i tested switch order of transformers
i get error for  ReflectionObfuscationTransformer  and HideAccesObfuscation
i succes decrypted string but rest again obfuscation 
Here the link : https://workupload.com/file/Vu47UAnC
(Sorry for my bad english)

java -jar deobfuscator.jar -input C:\Users\Gaming\Desktop\1.jar -output C:\Users\Gaming\Desktop\2.jar -transformer stringer.InvokedynamicTransformer -transformer stringer.invokedynamic.Invokedynamic1Transformer -transformer stringer.invokedynamic.Invokedynamic2Transformer -transformer stringer.ReflectionObfuscationTransformer -transformer stringer.v3.InvokedynamicTransformer -transformer stringer.v3_1.StringEncryptionTransformer -libraries "C:\Users\Gaming\Desktop\Nouveau dossier" -libraries "C:\Program Files\Java\jre1.8.0_191\lib"

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/Object get(Ljava/lang/Object;)Ljava/lang/Object; @ fr/paladium/palamod/client/gui/tools/prompt/p y(Ljava/lang/Object;I)Ljava/lang/String;
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1188)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.executor.defined.DictionaryMethodProvider.invokeMethod(DictionaryMethodProvider.java:48)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$null$8(ReflectionObfuscationTransformer.java:176)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$decrypt$9(ReflectionObfuscationTransformer.java:108)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.decrypt(ReflectionObfuscationTransformer.java:107)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:57)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

**Comment by ItzSomebody** [comment]
Run stringer.StringEncryptionTransformer first then run the stringer.HideAccessObfuscationTransformer.

**Comment by NullHF** [comment]
I get a error also with the order


Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$1$39.lambda$new$2(JVMMethodProvider.java:488)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$Function3.applyUnchecked(JVMMethodProvider.java:768)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider.invokeMethod(JVMMethodProvider.java:685)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1138)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$null$4(HideAccessObfuscationTransformer.java:138)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$5(HideAccessObfuscationTransformer.java:120)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:119)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)

**Comment by ThisTestUser** [comment]
[PalaMod-ClientDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2545992/PalaMod-ClientDeob.zip)
Not everything deobbed, because some dependencies are missing.
Known deps:
-Forge JAR
-MCP libs
-JSON Simple (http://www.java2s.com/Code/Jar/j/Downloadjsonsimple111jar.htm)
-CodeChickenLib 1.7 (http://files.minecraftforge.net/CodeChickenLib/)
-NEI 1.7 (https://minecraft.curseforge.com/projects/notenoughitems/files/2302312)
-SecretRooms (https://minecraft.curseforge.com/projects/secretroomsmod/files/2511803)
-BibloCraft (https://minecraft.curseforge.com/projects/bibliocraft/files/2300352)
-PCEF (renamed MCEF) ([pcef.zip](https://github.com/java-deobfuscator/deobfuscator/files/2545998/pcef.zip))
-RandomThings (https://minecraft.curseforge.com/projects/random-things/files/2225310)
-Discord RPC ([discord-rpc-release-v3.3.0.zip](https://github.com/java-deobfuscator/deobfuscator/files/2546003/discord-rpc-release-v3.3.0.zip))

**Comment by NullHF** [comment]
> [PalaMod-ClientDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2545992/PalaMod-ClientDeob.zip)
> Not everything deobbed, because some dependencies are missing.
> Known deps:
> -Forge JAR
> -MCP libs
> -JSON Simple (http://www.java2s.com/Code/Jar/j/Downloadjsonsimple111jar.htm)
> -CodeChickenLib 1.7 (http://files.minecraftforge.net/CodeChickenLib/)
> -NEI 1.7 (https://minecraft.curseforge.com/projects/notenoughitems/files/2302312)
> -SecretRooms (https://minecraft.curseforge.com/projects/secretroomsmod/files/2511803)
> -BibloCraft (https://minecraft.curseforge.com/projects/bibliocraft/files/2300352)
> -PCEF (renamed MCEF) ([pcef.zip](https://github.com/java-deobfuscator/deobfuscator/files/2545998/pcef.zip))
> -RandomThings (https://minecraft.curseforge.com/projects/random-things/files/2225310)
> -Discord RPC ([discord-rpc-release-v3.3.0.zip](https://github.com/java-deobfuscator/deobfuscator/files/2546003/discord-rpc-release-v3.3.0.zip))

omg the code is so clean
i can contact you via discord or another ?

**Comment by ThisTestUser** [comment]
Do you have another file that you need to deobfuscate?

**Comment by NullHF** [comment]
Yes i have this please , i not know what obfuscator is used


[Delta-b2.5.zip](https://github.com/java-deobfuscator/deobfuscator/files/3612763/Delta-b2.5.zip)

**Comment by ItzSomebody** [comment]
> i not know what obfuscator is used
> 

That uses an old version of Radon

**Comment by NullHF** [comment]
> > i not know what obfuscator is used
> 
> That uses an old version of [Radon](https://github.com/ItzSomebody/Radon)

So is your obfuscator , i can imagine you not accept help me for deob this ?

**Comment by ThisTestUser** [comment]
[Delta-b2.5Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3613153/Delta-b2.5Deob.zip)

**Comment by NullHF** [comment]
Thanks man , you so nice
