### ISSUE TITLE
Allatori deobfuscation Failed

### ISSUE THREAD

**Issue by wangll0522** [java-deobfuscator/deobfuscator#331]
-transformer allatori.StringEncryptionTransformer 
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at com.javadeobfuscator.deobfuscator.asm.source.SourceResult.consensus(SourceResult.java:61)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:67)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ThisTestUser** [comment]
Download a custom deobfuscator from https://github.com/ThisTestUser/deobfuscator/releases and use allatori.StringEncryptionTransformer instead of allatori.string.StringEncryptionTransformer.
