### ISSUE TITLE
Method code too large

### ISSUE THREAD

**Issue by SQLExceptionPhil** [java-deobfuscator/deobfuscator#332]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Method code too large!
        at com.javadeobfuscator.org.objectweb.asm.MethodWriter.getSize(MethodWriter.java:2059)
        at com.javadeobfuscator.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:861)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:504)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$7(Deobfuscator.java:308)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:306)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
If you have permission, you can upload the JAR file for us to find out what's wrong.

**Comment by SQLExceptionPhil** [comment]
[Skywars.zip](https://github.com/java-deobfuscator/deobfuscator/files/2634060/Skywars.zip)

**Comment by ThisTestUser** [comment]
[SkywarsDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2634481/SkywarsDeob.zip)

**Comment by SQLExceptionPhil** [comment]
How did you do it?
