### ISSUE TITLE
Deobfuscation issue (Unknown/error detect)

### ISSUE THREAD

**Issue by ThrowawayBotAccount** [java-deobfuscator/deobfuscator#338]
Got this error for this file

https://my.mixtape.moe/sxtcor.jar

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 1850
	at org.objectweb.asm.ClassReader.readStringish(ClassReader.java:2659)
	at org.objectweb.asm.ClassReader.readClass(ClassReader.java:2676)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1628)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

If you could tell what obfuscator was used and deobfuscate it, thanks.

**Comment by ThisTestUser** [comment]
[sxtcorDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2618273/sxtcorDeob.zip)
Radon uses trash classes that don't verify, so that's why you're getting the error.
