### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by foriv** [java-deobfuscator/deobfuscator#343]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at org.apache.commons.io.output.ByteArrayOutputStream.needNewBuffer(ByteArrayOutputStream.java:127)
        at org.apache.commons.io.output.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:96)
        at org.apache.commons.io.output.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:80)
        at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:720)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:172)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

Can someone help please!

**Comment by xParadoxical69** [comment]
just use `-Xmx1G`
