### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Silenc3IsGold3n** [java-deobfuscator/deobfuscator#345]
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at java.lang.reflect.Array.get(Native Method)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:474)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1306)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:277)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:50)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

`

[To-Deobf.zip](https://github.com/java-deobfuscator/deobfuscator/files/2714497/To-Deobf.zip)

**Comment by Silenc3IsGold3n** [comment]
got it to deobf nvm
