### ISSUE TITLE
Deobfuscator error UnsatisfiedLinkError--findBuiltInLib

### ISSUE THREAD

**Issue by itperson** [java-deobfuscator/deobfuscator#357]
I use the following config, but met the error:
Config:
input: jeesite.jar
output: output.jar
transformers:
  - allatori.string.StringEncryptionTransformer
path:
  - "C:\\Program Files\\Java\\jre1.8.0_51\\lib\\rt.jar"
  - "C:\\Program Files\\Java\\jre1.8.0_51\\lib\\jce.jar"
  - "C:\\Program Files\\Java\\jre1.8.0_51\\lib\\ext\\jfxrt.jar"
  - "D:\\Program Files\\Java\\jdk1.8.0_45\\lib\\tools.jar"

Error:
Deobfuscation failed. Please open a ticket on GitHub and provide the following e
rror:
com.javadeobfuscator.javavm.exceptions.ExecutionException: UnsatisfiedLinkError:
 java/lang/ClassLoader$NativeLibrary findBuiltinLib(Ljava/lang/String;)Ljava/lan
g/String;
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.jav
a:1209)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMac
hine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execut
e(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.jav
a:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMac
hine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execut
e(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.jav
a:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMac
hine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execut
e(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.jav
a:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMac
hine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execut
e(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.jav
a:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMac
hine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execut
e(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.jav
a:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMac
hine.java:1196)
        at com.javadeobfuscator.javavm.VirtualMachine.fullInitialization(Virtual
Machine.java:140)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualM
achine(TransformerHelper.java:168)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.string.String
EncryptionTransformer.transform(StringEncryptionTransformer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)
        Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: j
ava.lang.Throwable: null
                at java.lang.ClassLoader.loadLibrary0(Unknown Source)
                at java.lang.ClassLoader.loadLibrary(Unknown Source)
                at java.lang.Runtime.loadLibrary0(Unknown Source)
                at java.lang.System.loadLibrary(Unknown Source)
                at java.lang.System.initializeSystemClass(Unknown Source)

**Comment by itperson** [comment]
[jeesite.zip](https://github.com/java-deobfuscator/deobfuscator/files/2753900/jeesite.zip)

**Comment by ThisTestUser** [comment]
1. Download my custom deobfuscator from here:https://github.com/ThisTestUser/deobfuscator/releases
2. Use allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer (in that order)
Don't change anything else.

**Comment by itperson** [comment]
I download the jar and replace the transformer and run it. but i receive a lot of exceptions,
for example:
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
org/hyperic/sigar/jmx/SigarCpuPerc <clinit>()V com/jeesite/common/service/Servic
eException ALLATORIxDEMO(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchComparisonHandlerExc
eption: No comparator found for java/lang/String @ com/jeesite/common/service/Se
rviceException ALLATORIxDEMO(Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1560)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:109)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

**Comment by itperson** [comment]
> 1. Download my custom deobfuscator from here:https://github.com/ThisTestUser/deobfuscator/releases
> 2. Use allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer (in that order)
>    Don't change anything else.

I download the jar and replace the transformer and run it. but i receive a lot of exceptions,
for example:
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
org/hyperic/sigar/jmx/SigarCpuPerc ()V com/jeesite/common/service/Servic
eException ALLATORIxDEMO(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchComparisonHandlerExc
eption: No comparator found for java/lang/String @ com/jeesite/common/service/Se
rviceException ALLATORIxDEMO(Ljava/lang/String;)Ljava/lang/String;
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1560)
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:76)
at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:109)
at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

**Comment by itperson** [comment]
i add some libs and finished the task. thanks.
