### ISSUE TITLE
Deobfuscator allatori failed: it is not recognized

### ISSUE THREAD

**Issue by 2902598890** [java-deobfuscator/deobfuscator#376]
error:

Are you sure you're deobfuscating something obfuscated by Allatori?
com/1/2/3/4/z run()V com/1/2/3/4/z iiIIIIIIII(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchComparisonHandlerException: No comparator found for java/lang/String @ com/1/2/3/4/z iiIIIIIIII(Ljava/lang/String;)Ljava/lang/String;
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1560)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:109)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

I am using alllatori.StringEncryptionTransformer
Test jar:

[123.zip](https://github.com/java-deobfuscator/deobfuscator/files/2897584/123.zip)

**Comment by ThisTestUser** [comment]
[123Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2898054/123Deob.zip)

**Comment by 2902598890** [comment]
> [123Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2898054/123Deob.zip)

I keep trying, its results are unrecognizable, is it a problem with deobfuscator?
