### ISSUE TITLE
Error for every jar

### ISSUE THREAD

**Issue by Nubebuster** [java-deobfuscator/deobfuscator#377]
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.rules.stringer.RuleStringDecryptorWithThread.test(RuleStringDecryptorWithThread.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:255)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

I used a build from @ThisTestUser but the same error occurs with the vanilla build
[deobfuscator-1.0.0.zip](https://github.com/java-deobfuscator/deobfuscator/files/2920974/deobfuscator-1.0.0.zip)

Removed: what I want to deobfuscate.zip

This problem occurs with any jar I try to deobfuscate though.

**Comment by ItzSomebody** [comment]
That is Allatori. You should be able to deobfuscate that by adding the allatori.StringEncryptionTransformer transformer in ThisTestUser's build. Probably should also remove `detect: true` out of your config.

**Comment by Nubebuster** [comment]
The issue has been resolved using the allatori.StringEncryptionTransformer
