### ISSUE TITLE
NoClassInPathException when Normalizing

### ISSUE THREAD

**Issue by Nubebuster** [java-deobfuscator/deobfuscator#384]
When I try to use 
`com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.class`
or
`com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.class`
to deobfuscate, I get this error
`Exception in thread "main" com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException
	at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:337)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:404)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:370)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:463)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.lambda$0(FieldNormalizer.java:35)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.remap(FieldNormalizer.java:34)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at Main.main(Main.java:44)
`

I am using this code:
https://hastebin.com/owinojejij.cs

The problem is that I don't know which class is supposedly missing

**Comment by Janmm14** [comment]
can't open that hastebin, i suggest using another paste service

**Comment by Nubebuster** [comment]
@Janmm14 
https://hastebin.com/boyozuyuna.cs
https://pastebin.com/M3BkDVQP
(it was a hatebin btw xD hastebin was offline for a few weeks)

**Comment by Janmm14** [comment]
hmm here its actually adding whats missing to the exception: https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java#L337

**Comment by Nubebuster** [comment]
@Janmm14 right, but it's not in the actual stacktrace

**Comment by Enteerman** [comment]
@Nubebuster Reupload and open a new issue. The link does not work anymore. Try using the latest version.
