### ISSUE TITLE
[NullPointerException] stringer.HideAccess.ObfuscationTransformer

### ISSUE THREAD

**Issue by fahrenheit93** [java-deobfuscator/deobfuscator#386]
Hello again, i resolved my old problem with some dependencies, but after solving this one i got another issue which is :

`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$1$40.lambda$3(JVMMethodProvider.java:520)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$Function3.applyUnchecked(JVMMethodProvider.java:847)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider.invokeMethod(JVMMethodProvider.java:762)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1138)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$4(HideAccessObfuscationTransformer.java:143)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$2(HideAccessObfuscationTransformer.java:125)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:124)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
`

[MC-Mod.zip](https://github.com/java-deobfuscator/deobfuscator/files/3002233/MC-Mod.zip)

I'm using [Java-Deobfuscator GUI](https://github.com/java-deobfuscator/deobfuscator-gui) From @ThisTestUser 

My configuration :

`java -jar deobfuscator.jar -input C:\Users\moi\Documents\re\Minecraft-mod\fork\MC-Mod.jar -output C:\Users\moi\Documents\re\Minecraft-mod\fork\MC-Mod-deob.jar -transformer stringer.StringEncryptionTransformer -transformer normalizer.SourceFileClassNormalizer -transformer stringer.HideAccessObfuscationTransformer -path C:\Users\moi\AppData\Roaming\.minecraft\bootstrap\runtime\jre-x64-1.8.0_25-windows\lib\rt.jar -libraries C:\Users\moi\Documents\re\jd-gui-windows-1.4.1\forge-1.7.10-10.13.4.2512.jar -libraries C:\Users\moi\Documents\re\minecraft.jar -libraries C:\Users\moi\AppData\Roaming\.minecraft\minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar`

If anyone could help and explain to me how he did it to deobfuscate this one, would be great !

EDIT : All dependencies required : 
[dependencies.zip](https://github.com/java-deobfuscator/deobfuscator/files/3002274/dependencies.zip)

**Comment by ThisTestUser** [comment]
You must use sorucefileclassnormalizer last.

**Comment by fahrenheit93** [comment]
I put sourceFileNormalizer last but pretty same error here :
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$1$40.lambda$3(JVMMethodProvider.java:520)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$Function3.applyUnchecked(JVMMethodProvider.java:847)
	at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider.invokeMethod(JVMMethodProvider.java:762)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1138)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$4(HideAccessObfuscationTransformer.java:143)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$2(HideAccessObfuscationTransformer.java:125)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:124)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by Janmm14** [comment]
You are not using the latest version of the deonfuscator, line 520 cannot throw this exception.
https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/executor/defined/JVMMethodProvider.java#L520

**Comment by fahrenheit93** [comment]
I am using the GUI version from @ThisTestUser actually

**Comment by fahrenheit93** [comment]
Ok so i just put ClassNormalizer after the StringEncryptionTransformer, and it detected another missing lib, i just added this one, and boom again this error, this is better btw. I'll try to add another transformer

**Comment by fahrenheit93** [comment]
I see https://github.com/java-deobfuscator/deobfuscator/issues/322#issuecomment-435683173

@ThisTestUser Said that some libs are missing in this issue n°322, i put all the libs that are required to decompiled from Krakatau, and all libs required from the last version of the [Deobfuscator](https://github.com/ThisTestUser/deobfuscator), and same error, i can't use this famous "HideAccessObfuscation" Transfomer :/

Could you help please, i still stuck on it mmmh..

**Comment by ThisTestUser** [comment]
[PalaModDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3015641/PalaModDeob.zip)
The reason why it doesn't work is because there are some libraries that can't be resolved, so we need to modify the transformer to skip those.

**Comment by fahrenheit93** [comment]
Thank you very much that's insanely more understandable now, i just have another one which is smaller [MC-Addon2](https://github.com/java-deobfuscator/deobfuscator/files/3011084/MC-Addon2.zip) if you could.

Do you have any tips to learn deobfuscation by myself, i'm a webdeveloper in real life, and i don't know well Reverse-Engineering, i do have some basics with ASM i386 and i did some challenges but not very hardcore ones.

I would like to know if you have any documentations on how to learn properly Deobfuscation on JVM environment, thank you very much.

**Comment by fahrenheit93** [comment]
I need to ignore so much classes to make it works, that's wtff : 
![image](https://user-images.githubusercontent.com/48847643/55268697-7e566100-528c-11e9-9529-8aedc9c6c23b.png)

Insane..

**Comment by ThisTestUser** [comment]
[MC-Addon2Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3025006/MC-Addon2Deob.zip)

**Comment by byBackfish** [comment]
i have the same problem here :/.
