### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by SchoolsCool** [java-deobfuscator/deobfuscator#4]
Rearranged 683 goto blocks
Removed 0 continous gotos
Removed 0 unconditional switches
Deobfuscation failed. Please open a ticket on GitHub
java.lang.UnsupportedOperationException
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.execute(DeadCodeRemover.java:797)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$null$49(DeadCodeRemover.java:85)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$transform$50(DeadCodeRemover.java:46)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:45)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer.transform(PeepholeOptimizer.java:38)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:142)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:152)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by samczsun** [comment]
Please send the obfuscated jar to submit@javadeobfuscator.com with the subject "Issue #4"
