### ISSUE TITLE
NullPointerException during detection

### ISSUE THREAD

**Issue by garrett-hopper** [java-deobfuscator/deobfuscator#408]
[jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/3268948/jar.zip)

I'm getting this output while detecting:
```
» java -jar ~/dld/deobfuscator-1.0.0.jar --config detect.yml                                                  ~/tmp
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleIllegalSignature: Some obfuscators will set the signature of a class/method/field to an illegal value. This may crash naive decompilers/disassemblers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found illegal class signature for org/rspeer/60/4/01/01
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleSourceFileAttribute: Some obfuscators don't remove the SourceFile attribute by default. This information can be recovered, and is very useful
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found possible SourceFile attribute on com/rabbitmq/client/impl/AMQImpl$Access$RequestOk: AMQImpl.java
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.rules.stringer.RuleStringDecryptorWithThread.test(RuleStringDecryptorWithThread.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:255)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

**Comment by ThisTestUser** [comment]
Download my deobfuscator from here: https://github.com/ThisTestUser/deobfuscator/releases
Then, run allatori.StringEncryptionTransformer, general.removers.LocalVariableRemover, and write it to the output.
Then, take the output (you must do this separately for obfuscation to be completely removed) and apply allatori.FlowObfuscationTransformer to it.

**Comment by Jumblemuddle** [comment]
To be clear, I should be doing this against a jar which has already been decompiled and has `.java` files in it, right?
Everything you suggested, @ThisTestUser, seemed to work, but I still have a lot of nonsense:
```
        40 iIIiIiiiIIIii3;
        40 v0 = iIIiIiiiIIIii3;
        v0.iIIiIiiiIIIii = iIIiIiiiIIIii;
        v0.IIiiIiiiiIIiI = iIIiIiiiIIIii2;
        40 v1 = iIIiIiiiIIIii3;
        v0.iIiiiiiiIiIiI = new 11(new File(8.IiiiiiiiiiiIi));
        40 v2 = iIIiIiiiIIIii3;
        v2.iIIiiiiiIiiII = new 0();
```

**Comment by Janmm14** [comment]
This type of nonsense cant be solved. All what you can do is use normalizers to rename that iIi variables to a b c.

**Comment by Jumblemuddle** [comment]
@Janmm14, are those normalizers part of this project? What are they called?

**Comment by Jumblemuddle** [comment]
Should this issue be left open to document the NPE for detection?

**Comment by ItzSomebody** [comment]
https://github.com/java-deobfuscator/deobfuscator/tree/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/normalizer

**Comment by Janmm14** [comment]
Also this whole project is operating on .class files and not on some weird type of decompiled jar.

**Comment by ItzSomebody** [comment]
Labeled this as a deobfuscation failure (even though it's a detection fail) so I'd remember to check this once I finish working through some of the other issues.

**Comment by ThisTestUser** [comment]
Should be fixed in the latest release.
