### ISSUE TITLE
My jar does not deobfuscate

### ISSUE THREAD

**Issue by Nubebuster** [java-deobfuscator/deobfuscator#409]
I am not really sure what the cause is. Any help would be greatly appreciated!

```[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 34ms





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.javavm.utils.TypeHelper.getTypeByInternalName(TypeHelper.java:99)
	at com.javadeobfuscator.javavm.utils.TypeHelper.parseType(TypeHelper.java:67)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.getSuperclass(JavaClass.java:323)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:92)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:217)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:199)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:41)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
```
```
input: file.jar
output: deobbed.jar
transformers:
 - allatori.string.StringEncryptionTransformer
```

I think the encryption is done in 
```org.60.60.4.0.class```

[file.zip](https://github.com/java-deobfuscator/deobfuscator/files/3270300/file.zip)

Thanks in advance!

**Comment by Nubebuster** [comment]
using allatori.StringEncryptionTransformer instead and using @ThisTestUser 's latest build, it works.
