### ISSUE TITLE
String index out of range: 4

### ISSUE THREAD

**Issue by OpticFusion1** [java-deobfuscator/deobfuscator#411]
[BetterBookshelfs(1).zip](https://github.com/java-deobfuscator/deobfuscator/files/3280608/BetterBookshelfs.1.zip)

The config its self doesn't really matter in this case, every transformer i've tested caused this error to happen

`java.lang.StringIndexOutOfBoundsException: String index out of range: 4
        at java.lang.String.charAt(String.java:658)
        at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:177)
        at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:108)
        at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:166)
        at org.objectweb.asm.commons.ClassRemapper.visit(ClassRemapper.java:70)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:400)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(HashMap.java:981)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

**Comment by ItzSomebody** [comment]
[output.zip](https://github.com/java-deobfuscator/deobfuscator/files/3281783/output.zip)

**Comment by OpticFusion1** [comment]
> 
> 
> [output.zip](https://github.com/java-deobfuscator/deobfuscator/files/3281783/output.zip)
> 
> You have to use `general.removers.IllegalSignatureRemover` first.

Noted, thought i tried that
