### ISSUE TITLE
Stringer 3.0.3 not deobfuscate

### ISSUE THREAD

**Issue by lolka13372** [java-deobfuscator/deobfuscator#412]
Stringer 3.0.3 ActivationClient not deobfuscate
Full stringer.jar for deobfuscation: https://mega.nz/#!Kuo2UAAa!WhRqyOo6pmE5oCalbhMH3ApnJft7VDpXd0RlRccC7AM

**Comment by ThisTestUser** [comment]
1. Use deobfuscator from here: https://github.com/ThisTestUser/deobfuscator/releases
2. Use stringer.StringEncryptionTransformer and stringer.HideAccessObfuscationTransformer
3. Add stringer.jar (the obfuscator file)

**Comment by lolka13372** [comment]
@ThisTestUser 
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$17(HideAccessObfuscationTransformer.java:469)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.castFix(HideAccessObfuscationTransformer.java:443)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:432)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:330)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:287)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
LIke I said, you pulled out com.licel.license.client from stringer.jar, which is not allowed. You have to deobfuscate stringer.jar itself.

**Comment by lolka13372** [comment]
@ThisTestUser
HideAccessTransformer not working
Only StringEncryptionTransformer

**Comment by ThisTestUser** [comment]
Try downloading my deobfuscator jar in my repo again, adding log4j-api-2.11.2.jar from [here](https://logging.apache.org/log4j/2.0/download.html), and running it with stringer.jar.

**Comment by lolka13372** [comment]
@ThisTestUser 
![image](https://user-images.githubusercontent.com/51010014/59871952-6977fe00-93a1-11e9-9e01-083480a4769d.png)
It's right?

**Comment by lolka13372** [comment]
![image](https://user-images.githubusercontent.com/51010014/59872129-bc51b580-93a1-11e9-8d2a-c9e33a38f26d.png)

**Comment by lolka13372** [comment]
![image](https://user-images.githubusercontent.com/51010014/59872428-60d3f780-93a2-11e9-84b4-f7484b15dea7.png)

**Comment by lolka13372** [comment]
Thx for ignore

**Comment by ThisTestUser** [comment]
-Remove stringer.jar from your libraries list.
-StringEncryptionTransformer goes before HideAccessTransformer.
