### ISSUE TITLE
HELP!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by CauaJ19** [java-deobfuscator/deobfuscator#414]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at org.objectweb.asm.tree.MethodNode.visitVarInsn(MethodNode.java:433)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1476)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:101)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:125)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:300)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by Janmm14** [comment]
Try start with -Xmx2G
