### ISSUE TITLE
Can someone help me Deobfuscate this jar please?

### ISSUE THREAD

**Issue by levijc** [java-deobfuscator/deobfuscator#419]
I was able to get past one layer (that is what inject_deob.jar in the files I attached at the bottom is), but when I run  the detect on inject_deob.jar, I get this:

`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: 21337
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readConst(ClassReader.java:2728)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1586)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

Can anyone help?

I know for the original inject.jar file, Allatori was used.

I have uploaded the original file (inject.jar) and the first deobfuscated (inject_deob.jar) file here:
https://gofile.io/?c=IkuMci

**Comment by levijc** [comment]
I was able to get a little farther by giving the path to my rt.jar file in the config, using this transformer:

> com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
and the deobfuscator using this code:

`java -Xmx1024M -jar deobfuscator.jar --config config.yaml`
( I was previously getting the error that therer wasn't enough memory )
But now, I am getting this error:
`apple/laf/JRSUIConstants$Orientation could not be found while writing s/a/y/c/yy. Using COMPUTE_MAXS`

The file it is outputting is now is this (named inject-deob.jar) 
https://gofile.io/?c=98cHWM

Any help or advice?

**Comment by levijc** [comment]
I believe I may have gotten it, it is decrypting now, I used a different transformer, I will update as I can.

**Comment by levijc** [comment]
I am now getting this error - 

`[Filesystem] Getting boolean attributes of C:\Program Files\Java\jre1.8.0_211\lib\jce.jar (C:\java_home_dir\lib\jce.jar)
[Filesystem] Could not get boolean attributes of file C:\java_home_dir\lib\meta-index
[Filesystem] Getting boolean attributes of C:\Program Files\Java\jre1.8.0_211\lib\jce.jar (C:\java_home_dir\lib\jce.jar)
[Filesystem] Getting boolean attributes of C:\Program Files\Java\jre1.8.0_211\lib\jce.jar (C:\java_home_dir\lib\jce.jar)
[Filesystem] Getting boolean attributes of C:\Program Files\Java\jre1.8.0_211\lib\jce.jar (C:\java_home_dir\lib\jce.jar)
[Filesystem] Getting boolean attributes of C:\Program Files\Java\jre1.8.0_211\lib\jce.jar (C:\java_home_dir\lib\jce.jar)
[Filesystem] Opening C:\Program Files\Java\jre1.8.0_211\lib\jce.jar (C:\java_home_dir\lib\jce.jar)
[ClassLoader] An attempt was made to load the library awt.dll
[Filesystem] Could not find null\.accessibility.properties
[Filesystem] Could not find C:\java_home_dir\lib\accessibility.properties`

Any advice?

**Comment by ThisTestUser** [comment]
Download my deobfuscator.jar from https://github.com/thistestuser/deobfuscator
Then use allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer.
