### ISSUE TITLE
Unicode chars in classnames stop normalization

### ISSUE THREAD

**Issue by MiniDigger** [java-deobfuscator/deobfuscator#43]
the deobfuscator seems to have some problems with some unicode chars. the jar I am trying to normalize has a bunch of chineese letters, some of which can't even be displayed on win10.
![](http://bender.minidigger.me/2016/07/javaw_2016-07-14_21-24-30.png)
this seems to be a issue with asm.
this input jar is this one, I didn't made it so proceed with caution http://www.mediafire.com/download/w99tvemr6u864uk/Output.zip
```java -jar deobfuscator-1.0.0.jar -input input.jar -output output.jar -transformer normalizer.ClassNormalizer normalizer.MethodNormalizer normalizer.FieldNormalizer -path "C:\Program Files\Java\jre1.8.0_91\lib\rt.jar"
Could not parse ??.class (is it a class?)
java.lang.IllegalArgumentException
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
Could not parse ??.class (is it a class?)
java.lang.IllegalArgumentException
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
Deobfuscation failed. Please open a ticket on GitHub
java.lang.ArrayIndexOutOfBoundsException: 55572
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:181)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:105)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)```

**Comment by Janmm14** [comment]
The class files you got are for java 9 (or higher), corrupt or fake, as the check in line 170 is about the class version, and the issue in line 181 is that while reading the constant pool, the end of the class is reached.

**Comment by MiniDigger** [comment]
I know that it is not a fake class. the jar contains fake classes too but if I open one of the classes that has a not displayable name in a hex editor it looks fine. I know that the classes contain fake signature, could that be an issue?
maybe I need to do much more manuell stuff...

**Comment by Janmm14** [comment]
Maybe they're better fake classes. Are they referenced somewhere in code that gets executed?

**Comment by samczsun** [comment]
You'll have to manually deobfuscated it. It's not too hard.

Have fun o/
