### ISSUE TITLE
java.lang.RuntimeException: Method code too large!

### ISSUE THREAD

**Issue by NothCoding** [java-deobfuscator/deobfuscator#431]
Im trying to decompile an old Spigot Plugin to continue it, but it doesnt work:

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Method code too large!
	at org.objectweb.asm.MethodWriter.getSize(MethodWriter.java:2059)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:861)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:554)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$9(Deobfuscator.java:362)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:360)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by GSharma789** [comment]
same error i have, unfortunately i can not upload jar here . where to make change in code so this can be fixed ?

**Comment by Janmm14** [comment]
at org.objectweb.asm.MethodWriter.getSize(MethodWriter.java:2059)

**Comment by ThisTestUser** [comment]
This is the result of a particular type of ZKM string encryption.

**Comment by Enteerman** [comment]
Since the method is extremely easy to simplify, it still fools programs like this because they insert POP2 and LDC instead of removing the actual LDC, LDC, (IADD/IOR/...) pattern.
