### ISSUE TITLE
Deobsufcation Failed

### ISSUE THREAD

**Issue by Pr0One** [java-deobfuscator/deobfuscator#436]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.String.substring(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:148)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:152)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:152)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:152)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:140)
        at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapDesc(Remapper.java:63)
        at com.javadeobfuscator.org.objectweb.asm.commons.MethodRemapper.visitLocalVariable(MethodRemapper.java:213)
        at com.javadeobfuscator.org.objectweb.asm.tree.LocalVariableNode.accept(LocalVariableNode.java:109)
        at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:821)
        at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
        at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer$$Lambda$8/20141306.accept(Unknown Source)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
You need to run the deobfuscator with more RAM.
