### ISSUE TITLE
Cannot Deobfuscate Allitori String Decryption

### ISSUE THREAD

**Issue by ThisTestUser** [java-deobfuscator/deobfuscator#44]
I get this error when I try to decrypt: 
Reading complete. Transforming

Deobfuscation failed. Please open a ticket on GitHub
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$null$246(StringEncryptionTransformer.java:61)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$transform$247(StringEncryptionTransformer.java:49)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:48)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:162)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by samczsun** [comment]
Please send a copy of the obfuscated JAR to submit@javadeobfuscator.com with the subject "Issue #44"

**Comment by samczsun** [comment]
I managed to deobfuscate it fine using the latest commit. Can you try that please?

**Comment by ThisTestUser** [comment]
So its the one that you just posted? I'll try using that one.
