### ISSUE TITLE
ReflectionObfuscationTransformer

### ISSUE THREAD

**Issue by Kriso123** [java-deobfuscator/deobfuscator#444]
This is my config.yml
input: 33.jar
output: 5.jar
path:
 - "C:\\Program Files\\Java\\jre1.8.0_211\\lib\\rt.jar"
 - "C:\\Users\\Kriso\\AppData\\Roaming\\.minecraft\\libraries\\net\\minecraftforge\\forge\\1.7.10-10.13.4.1614-1.7.10\\forge-1.7.10-10.13.4.1614-1.7.10.jar"
 - "C:\\Users\\Kriso\\.gradle\\caches\\minecraft\\net\\minecraftforge\\forge\\1.7.10-10.13.4.1614-1.7.10\\forge-1.7.10-10.13.4.1614-1.7.10-srg.jar"
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer

This is what i get when i try to deobf a forge mod, idk why.If anybody can help this is the download link
https://www.mediafire.com/file/4y3cwy3ui4jqxge/33.jar/file

C:\Users\Kriso\Desktop\yea>java -jar deob.jar --config config.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeo
bfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransform
er
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 368ms
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeo
bfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
[Zelix] [ReflectionObfuscationTransformer] Starting
[Zelix] [ReflectionObfuscationTransformer] Finding reflection obfuscation
[Zelix] [ReflectionObfuscationTransformer] Found 12893 reflection obfuscation in
structions
Error while fully initializing  ________________/he
com.javadeobfuscator.deobfuscator.executor.exceptions.FallingOffCodeException:
@ a/c/a vm()Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:354)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvid
er.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvid
er.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1426)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvid
er.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvid
er.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfusc
ationTransformer.lambda$null$7(ReflectionObfuscationTransformer.java:175)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfusc
ationTransformer.lambda$inlineReflection$8(ReflectionObfuscationTransformer.java
:133)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfusc
ationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:132)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfusc
ationTransformer.transform(ReflectionObfuscationTransformer.java:63)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

Deobfuscation failed. Please open a ticket on GitHub and provide the following e
rror:
java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArra
yLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:486)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvid
er.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvid
er.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1306)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfusc
ationTransformer.lambda$null$7(ReflectionObfuscationTransformer.java:185)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfusc
ationTransformer.lambda$inlineReflection$8(ReflectionObfuscationTransformer.java
:133)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfusc
ationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:132)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfusc
ationTransformer.transform(ReflectionObfuscationTransformer.java:63)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfusc
ator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

**Comment by ThisTestUser** [comment]
[33Deob.zip](https://github.com/java-deobfuscator/deobfuscator/files/3538729/33Deob.zip)

The reason why this happens is because Paramorphism obfuscator is in there.

**Comment by Kriso123** [comment]
Thank you bro i love you
