### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Samistine** [java-deobfuscator/deobfuscator#45]
Might be doing something wrong idk. I have a server with KVM that has a proprietary client that I want to cleanup.

```
$ java -jar deobfuscator-1.0.0.jar -input avctKVM.jar -output output.jar -trans
former general.SyntheticBridgeTransformer

Reading complete. Loading hierachy

Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: java/lang/Object
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:230)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

[avctKVM.zip](https://github.com/java-deobfuscator/deobfuscator/files/378940/avctKVM.zip)

**Comment by samczsun** [comment]
```Could not locate a class file.
Have you added the necessary files to the -path argument?```

**Comment by Samistine** [comment]
This is a standalone program unlike a bukkit plugin.

**Comment by samczsun** [comment]
```NoClassInPathException: java/lang/Object```

**Comment by CodenameFlip** [comment]
I could be wrong but it looks like you forgot to add the `-path` parameter.

I would refer back to the example command :)
