### ISSUE TITLE
Allatori Deobfuscation

### ISSUE THREAD

**Issue by jonesdj1** [java-deobfuscator/deobfuscator#46]
I dont know how to do this can someone help me?

C:\Users\User\Desktop\deob>java -jar deob.jar -input input.jar -output output.jar -transformer allatori.StringEncryptionTransformer -path "C:\Program Files\Java\jre1.8.0_91\lib\rt.jar"
Warning! Output file already exists

Reading complete. Loading hierachy

Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: com/google/common/base/Function
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:240)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

C:\Users\User\Desktop\deob>java -jar deob.jar -input input.jar -output output.jar -transformer  stringer.StringEncryptionTransformer -path "C:\Program Files\Java\jre1.8.0_91\lib\rt.jar" "C:\Program Files\Java\jre1.8.0_91\lib\jce.jar"
Warning! Output file already exists

Reading complete. Loading hierachy

Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: com/google/common/base/Function
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:240)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by samczsun** [comment]
Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: com/google/common/base/Function

**Comment by jonesdj1** [comment]
what does that mean what do i have to add i dont get it

**Comment by jonesdj1** [comment]
and how do i add more then one thing

**Comment by bruno10223** [comment]
I have the same problem

**Comment by samczsun** [comment]
It is assumed that if you are using this program, you have a basic understanding of how to run command line applications as well as Java itself.
