### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error

### ISSUE THREAD

**Issue by DolphinGamerYT** [java-deobfuscator/deobfuscator#474]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.StringIndexOutOfBoundsException: String index out of range: 10
        at java.lang.String.charAt(Unknown Source)
        at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:177)
        at com.javadeobfuscator.org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:108)
        at com.javadeobfuscator.org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:166)
        at com.javadeobfuscator.org.objectweb.asm.commons.ClassRemapper.visit(ClassRemapper.java:70)
        at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:400)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
Use this one: https://github.com/thistestuser/deobfuscator/releases

**Comment by DolphinGamerYT** [comment]
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.StringIndexOutOfBoundsException: String index out of range: 10
        at java.lang.String.charAt(Unknown Source)
        at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:177)
        at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:108)
        at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:166)
        at org.objectweb.asm.commons.ClassRemapper.visit(ClassRemapper.java:70)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:400)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:382)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:339)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

**Comment by DolphinGamerYT** [comment]
I'm having the same issue

**Comment by ThisTestUser** [comment]
Use illegalsignatureremover first.

**Comment by DolphinGamerYT** [comment]
`[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 43 source filenames
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/Exception could not be found while writing Forms/äPiywM3v2qfw=öllTAnöAAYIepeoYSE=öGsqgaöVg==öxMrjqöü. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing Forms/vp7HwVw23OMKyK0RFDBK8jRwXHK4r4=öyvNHcöVu2JLZ17YOk=öVonqPöü. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing GraphicInterface/KNk7P1NfUkvGeHQ==öIeRVFöPxkVBU8qAhE=öOztuaö6uZ86JCj57fom+NythI7yw==öyyEBYööKhhVEö+84R7vsDg2DW8eA8b9ht0A==öWrYDUö4FpPzhAosbg=öDmhxbööYXowEö775AL6r9j+8=övjeZPööTsrwFöü. Using COMPUTE_MAXS`
And the program is not opening now.

**Comment by Janmm14** [comment]
If you use a normalizer, don't expect the plugin to work.

Also it looks like you did not add rt.jar to the path.
