### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error

### ISSUE THREAD

**Issue by gabe56f** [java-deobfuscator/deobfuscator#475]
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.javavm.exceptions.ExecutionException: Unknown ctor init ()V valid (Ljava/lang/String;)V (Ljava/lang/ThreadGroup;Ljava/lang/String;)V
        at com.javadeobfuscator.javavm.VirtualMachine.newInstance(VirtualMachine.java:956)
        at com.javadeobfuscator.javavm.VirtualMachine.fullInitialization(VirtualMachine.java:132)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:168)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer.transform(SimpleStringEncryptionTransformer.java:74)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

**Comment by ThisTestUser** [comment]
If you could, attach your JAR file.
