### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ikanekb** [java-deobfuscator/deobfuscator#501]
java.lang.OutOfMemoryError: Java heap space
        at org.apache.commons.io.output.ByteArrayOutputStream.needNewBuffer(ByteArrayOutputStream.java:127)
        at org.apache.commons.io.output.ByteArrayOutputStream.write(ByteArrayOutputStream.java:158)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
        at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:721)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:172)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ikanekb** [comment]
after incrementing the -Xmx to 6G and more than 2 hours processing:

java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.resize(Unknown Source)
        at java.util.HashMap.putVal(Unknown Source)
        at java.util.HashMap.put(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapFieldName(CustomRemapper.java:118)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.lambda$remap$0(FieldNormalizer.java:70)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer$$Lambda$18/1505119611.accept(Unknown Source)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.remap(FieldNormalizer.java:34)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.transformers.DelegatingTransformer.transform(DelegatingTransformer.java:28)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by Janmm14** [comment]
Which transformers did you use?

**Comment by ikanekb** [comment]
transformers:
  - zelix.string.SimpleStringEncryptionTransformer

But the error appears after in:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.DelegatingTransformer

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at java.lang.String.substring(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:148)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:152)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:152)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:140)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapFieldName(CustomRemapper.java:106)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.lambda$remap$0(FieldNormalizer.java:70)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer$$Lambda$331/1386204514.accept(Unknown Source)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.remap(FieldNormalizer.java:34)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.transformers.DelegatingTransformer.transform(DelegatingTransformer.java:28)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
