### ISSUE TITLE
"Method not found" when trying to deobfuscate Frames+

### ISSUE THREAD

**Issue by AnErrupTion** [java-deobfuscator/deobfuscator#505]
Hello,
So I was trying to deobfuscate a Minecraft mod named Frames+, but I've got an error.
Basically, I was trying to deobfuscate it again (I've already deobfuscated it with the tool just before and it worked but it wasn't fully deobfuscated) and I've got this error:

com.javadeobfuscator.javavm.exceptions.ExecutionException: IncompatibleClassChangeError: Method not found com/github/benmanes/caffeine/cache/MpscGrowableArrayQueue5.b.(II)Ljava/lang/String;
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:102)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1111)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1044)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1025)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:131)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
        Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
                at com.github.benmanes.caffeine.cache.MpscGrowableArrayQueue5.Decryptor(MpscGrowableArrayQueue.java)

A zip file containing two files can be found below, one is the non-deobfuscated one (the one that you can find on Sk1er's website) and one that I've deobfuscated once (the one where I've got the error).

Zip file: https://mega.nz/#!Yi4QGYoZ!RZcYufUEz6rLqRi9K0zBXWV_kRxrtdc4kr1NEbGHg6w

Here's the config file:

```
input: framesplus_deobf.jar
output: framesplus_output.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer
```

~ AnErrupTion

**Comment by Janmm14** [comment]
Put normalizers at then end of the transformers list. Always.
