### ISSUE TITLE
Help error 

### ISSUE THREAD

**Issue by jzr54732** [java-deobfuscator/deobfuscator#506]
[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occurred while parsing the configuration file
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.javadeobfuscator.deobfuscator.config.Configuration` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('input:fuckme.jar detect:true')
 at [Source: (File); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1329)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:370)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:170)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:80)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by Janmm14** [comment]
config file invalid

**Comment by Enteerman** [comment]
Invalid config, attach your config or open a new issue.
