### ISSUE TITLE
stringer.v3.ResourceEncryption error

### ISSUE THREAD

**Issue by winxpqq955** [java-deobfuscator/deobfuscator#508]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ClassCastException: com.javadeobfuscator.javavm.values.JavaNull cannot be cast to com.javadeobfuscator.javavm.values.JavaArray
	at com.javadeobfuscator.javavm.values.JavaWrapper.asArray(JavaWrapper.java:171)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1682)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.VirtualMachine.newInstance(VirtualMachine.java:948)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.v3.ResourceEncryptionTransformer.transform(ResourceEncryptionTransformer.java:60)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
		at xfy.bsp.bh.U(Unknown Source)
		at xfy.bsp.bh.<init>(Unknown Source)

**Comment by ThisTestUser** [comment]
Use stringer.ResourceEncryptionTransformer and use this deobfuscator: https://github.com/ThisTestUser/deobfuscator/releases

**Comment by ItzSomebody** [comment]
Since this wasn't replied to by the OP and is an old issue, I'll close this for now. @winxpqq955 If this is still an issue, feel free to reopen.
