### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by DeMoNeK** [java-deobfuscator/deobfuscator#513]
i have error : 
java -Xss128m -jar deobfuscator.jar --config config.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at org.objectweb.asm.ClassReader.readClass(ClassReader.java:452)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:99)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:120)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:300)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

C:\Users\macie\Desktop\dJavaDeobf>

config:

input: plugin.jar
output: plugin-deobf.jar
path:
 - C:\Program Files\Java\jre1.8.0_181\lib\rt.jar
transformers:
- allatori.string.StringEncryptionTransformer

what's wrong?

**Comment by Janmm14** [comment]
use -Xmx2G, if that does not help, you use wrong transformer or there is no transformer capable of the obfuscation
