### ISSUE TITLE
zip.dll

### ISSUE THREAD

**Issue by omegabr22** [java-deobfuscator/deobfuscator#514]
```java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:87)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:127)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
```

[test.zip](https://github.com/java-deobfuscator/deobfuscator/files/4027371/test.zip)
so i had first a problem with zip.dll libary but now is this

**Comment by ItzSomebody** [comment]
Since this wasn't addressed and is an old issue, I'll close this for now.

@omegabr22 I believe this is caused by attempting to open a zip file that is either corrupted or screwed up enough to the point where the Java API is refusing to open it; however, making any other conclusions is difficult based on this information alone (and it's independent of the zip.dll stuff in the logs.) If this is still an issue, feel free to reopen.
