### ISSUE TITLE
Deobfuscation error (java.lang.ArrayIndexOutOfBoundsException on read source file)

### ISSUE THREAD

**Issue by Bibon21** [java-deobfuscator/deobfuscator#516]
`java.lang.ArrayIndexOutOfBoundsException: 6930
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readStringish(ClassReader.java:2659)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readClass(ClassReader.java:2676)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1628)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
`
Please deobfuscate: 
[mod.zip](https://github.com/java-deobfuscator/deobfuscator/files/4032120/mod.zip)

**Comment by Bibon21** [comment]
Help me please 🐰

**Comment by Princekiin** [comment]
You can open it with JByte-Mod. Also i see some code hider tricks and many try-catch splitting. Try ThreadTear instead.

**Comment by ItzSomebody** [comment]
Closing this since this is pretty old. In the future, please try to avoid directly uploading stuff to the issue tracker that you don't own the rights to.
