### ISSUE TITLE
java.lang.IllegalArgumentException: value null

### ISSUE THREAD

**Issue by Stormfox2** [java-deobfuscator/deobfuscator#525]
```java
java.lang.IllegalArgumentException: value null
	at com.javadeobfuscator.org.objectweb.asm.ClassWriter.newConstItem(ClassWriter.java:1106)
	at com.javadeobfuscator.org.objectweb.asm.MethodWriter.visitLdcInsn(MethodWriter.java:1165)
	at com.javadeobfuscator.org.objectweb.asm.tree.LdcInsnNode.accept(LdcInsnNode.java:71)
	at com.javadeobfuscator.org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
	at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:485)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$7(Deobfuscator.java:308)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
```
Using ```com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer```

**Comment by ItzSomebody** [comment]
Since this wasn't addressed and is an old issue, I'll close this for now. @Stormfox2 If this is still an issue, feel free to reopen.
