### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 246

### ISSUE THREAD

**Issue by Out69** [java-deobfuscator/deobfuscator#528]
java.lang.ArrayIndexOutOfBoundsException: 246
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1162)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ItzSomebody** [comment]
Since this wasn't addressed and is a pretty old issue, I'll close this for now. @Out69 If this is still an issue, feel free to reopen.
