### ISSUE TITLE
Using zelix.string.SimpleStringEncryptionTransformer

### ISSUE THREAD

**Issue by SoulshifterOne** [java-deobfuscator/deobfuscator#529]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException: value null
        at com.javadeobfuscator.org.objectweb.asm.ClassWriter.newConstItem(ClassWriter.java:1106)
        at com.javadeobfuscator.org.objectweb.asm.MethodWriter.visitLdcInsn(MethodWriter.java:1165)
        at com.javadeobfuscator.org.objectweb.asm.tree.LdcInsnNode.accept(LdcInsnNode.java:71)
        at com.javadeobfuscator.org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
        at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
        at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
        at com.javadeobfuscator.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:485)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$7(Deobfuscator.java:308)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:306)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

Any Idea?. Thanks

**Comment by Enteerman** [comment]
Attach your config as well as your jar. If you don't own the program, sorry, we won't be able to help you.

**Comment by ThisTestUser** [comment]
zelix.StringEncryptionTransformer should be able to work when zelix.string.StringEncryptionTransformer doesn't.
