### ISSUE TITLE
ava.lang.ClassCastException: com.javadeobfuscator.org.objectweb.asm.tree.VarInsnNode cannot be cast to com.javadeobfuscator.org.objectweb.asm.tree.LdcInsnNode

### ISSUE THREAD

**Issue by omegabr22** [java-deobfuscator/deobfuscator#530]
````[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
[Zelix] [ReflectionObfuscationTransformer] Starting
[Zelix] [ReflectionObfuscationTransformer] Finding reflection obfuscation
[Zelix] [ReflectionObfuscationTransformer] Found 16 reflection obfuscation instructions





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ClassCastException: com.javadeobfuscator.org.objectweb.asm.tree.VarInsnNode cannot be cast to com.javadeobfuscator.org.objectweb.asm.tree.LdcInsnNode

	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.lambda$null$7(ReflectionObfuscationTransformer.java:220)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.lambda$inlineReflection$8(ReflectionObfuscationTransformer.java:133)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:132)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:63)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Thread.java:748)```


here is my config:
```java -jar deobfuscator.jar -input C:\Users\omegabr\Downloads\s.jar -output C:\Users\omegabr\Downloads\x.jar -transformer zelix.ReflectionObfuscationTransformer -path "C:\Program Files\Java\jdk1.8.0_231\jre\lib\rt.jar" -smartRedo -verify```

**Comment by omegabr22** [comment]
[s.zip](https://github.com/java-deobfuscator/deobfuscator/files/4247091/s.zip)
here is the jar (is inside the .zip file)

**Comment by Janmm14** [comment]
u might have to run some other zkm transformer first, or the jar was obfuscated using a recent zkm version, in that case this deobfuscator has no transformer built in to deobfuscate.

**Comment by ThisTestUser** [comment]
[sDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4483385/sDeob.zip)
I can't remove the reflection obf, because there are lots of files missing in there.
