### ISSUE TITLE
VM throws NoSuchAlgorithmException

### ISSUE THREAD

**Issue by cookiedragon234** [java-deobfuscator/deobfuscator#536]
Getting the following when trying to deobfuscate a string using virtualisation:
```Java
[Filesystem] Getting boolean attributes of C:\Program Files\Java\jdk1.8.0_241\jre\lib\security\java.security (C:\java_home_dir\lib\security\java.security)
[Filesystem] Opening C:\Program Files\Java\jdk1.8.0_241\jre\lib\security\java.security (C:\java_home_dir\lib\security\java.security) for reading
[ClassLoader] Could not find class sun.security.ec.SunEC
[ClassLoader] Could not find class sun.security.ec.SunEC
[ClassLoader] Could not find class sun.security.ec.SunEC
[ClassLoader] Could not find class com.sun.crypto.provider.SunJCE
[ClassLoader] Could not find class com.sun.crypto.provider.SunJCE
[ClassLoader] Could not find class com.sun.crypto.provider.SunJCE
[ClassLoader] Could not find class sun.security.mscapi.SunMSCAPI
[ClassLoader] Could not find class sun.security.mscapi.SunMSCAPI
[ClassLoader] Could not find class sun.security.mscapi.SunMSCAPI
java.security.NoSuchAlgorithmException: Cannot find any provider supporting DES
        at javax.crypto.Cipher.getInstance(Cipher.java:539)
        at Class23.method_415(Unknown Source)
        at Class23.method_414(Unknown Source)
        at Class23.<clinit>(Unknown Source)
```

Is there something Im doing wrong here? Thanks :)

**Comment by cookiedragon234** [comment]
For anyone wondering uncomment these lines: https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/utils/TransformerHelper.java#L158
