### ISSUE TITLE
ZipException while opening Jar

### ISSUE THREAD

**Issue by MrExplode** [java-deobfuscator/deobfuscator#539]
SO I tried to open a jar to remove further obfuscations, but I got this exception.
I have to note that this Jar is a repackaged jar, because it was encrypted with various methods before, so I decryptied the files, unzipped the whole jar, then repackaged with [this ](https://gist.github.com/MrExplode/556e935aa26ca72394ebd342bdbd63e4)code I wrote.

On jdk 8 it gives an other error: `java.util.zip.ZipException: error in opening zip file`

Java version: AdoptOpenJDK 11.0.6.10

```
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:87)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:113)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by MrExplode** [comment]
Update: I installed OracleJRE 8 and tested it with various other jar files, but the error still happened.

**Comment by Janmm14** [comment]
I feel like this error is likely not inside java-deobfuscator.

**Comment by MrExplode** [comment]
Found the problem, wasn't related to java-deobfuscator.
