### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by KrokoOnAir** [java-deobfuscator/deobfuscator#545]
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.javadeobfuscator.javavm.mirrors.JavaClass.findFieldNode(JavaClass.java:123)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.findFieldNode(JavaClass.java:132)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1627)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.VirtualMachine.exceptionToString(VirtualMachine.java:1876)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:134)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:328)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:285)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by Enteerman** [comment]
Have you tried processing with the transformers one by one, or tune the GC (use the concurrent one) as suggested from the answers to the [StackOverflow question](https://stackoverflow.com/questions/1393486/error-java-lang-outofmemoryerror-gc-overhead-limit-exceeded)?

**Comment by Enteerman** [comment]
#642
