### ISSUE TITLE
An error occurred while parsing the commandline

### ISSUE THREAD

**Issue by DefenderLab** [java-deobfuscator/deobfuscator#548]

**Comment by DefenderLab** [comment]
C:\tools>java -jar deobfuscator.jar -input C:\tools\ddgfocbdbc.jar -output c:\lo
gs\deobfuscated -transformer allatori.string.StringEncryptionTransformer -path "
C:\Program Files\Java\jre1.8.0_31\lib\rt.jar"
[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occur
red while parsing the commandline
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -input
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser
.java:347)
        at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(Defaul
tParser.java:689)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(Default
Parser.java:520)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:2
43)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:62)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:50)

**Comment by ThisTestUser** [comment]
Use the GUI instead: https://github.com/java-deobfuscator/deobfuscator-gui/releases

**Comment by DefenderLab** [comment]
Heap error with GUI

**Comment by ThisTestUser** [comment]
Launch the GUI with xmx arguments (java -jar deobfuscator-gui.jar -Xmx). If it still doesn't work, then you may upload your sample.

**Comment by ItzSomebody** [comment]
Old issue with no response. Closing.
