### ISSUE TITLE
Allatori string decryption problem

### ISSUE THREAD

**Issue by netindev** [java-deobfuscator/deobfuscator#56]
I'm trying to decompile allatori 5.9

```
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
com/allatori/wtk/WTKObfuscator THIS_IS_DEMO_VERSION_NOT_FOR_COMMERCIAL_USE(Ljava/io/File;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; com/allatori/IIIiiIiiII THIS_IS_DEMO_VERSION_NOT_FOR_COMMERCIAL_USE(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/CloneNotSupportedException <init>()V @ com/allatori/wtk/WTKObfuscator THIS_IS_DEMO_VERSION_NOT_FOR_COMMERCIAL_USE(Ljava/lang/String;)Ljava/lang/String;
    at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1129)
    at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
    at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
    at java.util.ArrayList.forEach(Unknown Source)
    at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
    at java.util.HashMap$Values.forEach(Unknown Source)
    at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:53)
```

**Comment by samczsun** [comment]
Please send a copy of the obfuscated jar to submit@javadeobfuscator.com with the subject "Issue #56"

**Comment by Janmm14** [comment]
@netindev Why close this issue then? Its not solved by just sending him the jar.

**Comment by samczsun** [comment]
Ah geez, I can't remember if I ever fixed this or not, but I'm gonna have to close this now because it's too stale and I'd like to get issues back to a manageable state

**Comment by FearLinux** [comment]
lol

**Comment by Janmm14** [comment]
> lol

pls why comment on 5 year old issue? btw this issue is fxied
