### ISSUE TITLE
error + deobf .jar please

### ISSUE THREAD

**Issue by keyfqsY** [java-deobfuscator/deobfuscator#563]
File:  https://easyupload.io/2fbr39

Error:

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 5: Cannot pop operand off an empty stack.
        at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:298)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:35)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
        at org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:221)
        at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:297)
        at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:200)
        ... 6 more

**Comment by ThisTestUser** [comment]
[deobfDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/4692465/deobfDeob.zip)
