### ISSUE TITLE
An error on detect step

### ISSUE THREAD

**Issue by yarncha** [java-deobfuscator/deobfuscator#564]
Hi, I've try to deobfuscate this jar file, but this happens...
```
C:\Users\Yamcha\Desktop\deopfustester>java -jar deobfuscator.jar --config detect.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse test.class (is it a class file?)
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:256)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:330)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
```

And when i run this program, this program runs normally. Is there any way I can try to fix this error?
```
C:\Users\Yamcha\Desktop\deopfustester>java -jar test.jar
3
```

[test.zip](https://github.com/java-deobfuscator/deobfuscator/files/4694322/test.zip)

**Comment by ThisTestUser** [comment]
That just means that there is an invaild class file in the JAR. If the program runs properly, there is no issue here.
