### ISSUE TITLE
String index out of range: 10

### ISSUE THREAD

**Issue by HideakiAtsuyo** [java-deobfuscator/deobfuscator#573]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 10
        at java.lang.String.charAt(Unknown Source)
        at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:177)
        at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:108)
        at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:166)
        at org.objectweb.asm.commons.ClassRemapper.visit(ClassRemapper.java:70)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:400)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
And the config.yml:

```yml
input: Tool.jar
output: Tool-clean.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
```

**Comment by Janmm14** [comment]
try run `general.removers.IllegalSignatureRemover` before

**Comment by HideakiAtsuyo** [comment]
```
$ java -jar deobfuscator.jar --config config.yml                                                                        [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 64 source filenames
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/Exception could not be found while writing GraphicInterface/V5s=ömVxcOööLTHrDöyMbC+z7dPbU=öYOvazöü. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing GraphicInterface/ätZWTbf+mWKSENhEqyp4CFnirB9ADsEXHRKbYFOIXonU=öqqJrgöXLkCPxBL1MA=ögPmbXöVue3g1bRpeo=övBmRGöfQ==öGmTkAöLL+smzJopdg=övCkWDöDA0uFhUwWgQKEzsRIhBWHQIkBwYsEygMVmJaöXzGbvöTm8=öCeGQQöü. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing Forms/B6hvxliZ1Cjkkr58Va1ymlXti5+Toz50hxI=öEdxMfö1veWuEMgZyM=öMIlHGöü. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing Forms/cfl6A4höZVwYWöSQ==ösMHxBödQ==öOAiRYöü. Using COMPUTE_MAXS
Error: java/net/SocketException could not be found while writing Forms/ENdIS5YnustmP5I1hr5g==öDajLPö6Fz0+f58FFatfcTPDceLsg==öMTIBGöbyMzBAQnHxYbCSEINRoJMB4Göü. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing Forms/y4Oj+X5ig==özQeowönvGSnThyoMGODj2fFiwHUg==öIjxlJöü. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing Forms/ZQ==ökocIjöü. Using COMPUTE_MAXS
```
Hum :/

**Comment by Janmm14** [comment]
rt.jar in path is required

**Comment by HideakiAtsuyo** [comment]
What is rt.jar?

**Comment by Janmm14** [comment]
Its the jar file that contains the java api. Usually for jre installations inside the lib folder, for jdk installation inside jre/lib folder

In later JVM versions it got removed but can be created programatically. Goolge for that one please.

**Comment by HideakiAtsuyo** [comment]
But why i need a file if i've already him:

C:\Program Files\Java\jre1.8.0_241\lib\rt.jar

**Comment by Janmm14** [comment]
in that case you have to tell java-deobfuscator to use it in deobfuscation, add
```yaml
path:
  - "C:\Program Files\Java\jre1.8.0_241\lib\rt.jar"
```
to your config

**Comment by HideakiAtsuyo** [comment]
config.yml:

```yml
input: StreamerTool.jar
output: StreamerTool-clean.jar
path:
  - "C:/Program Files/Java/jre1.8.0_241/lib/rt.jar"
transformers:
  - general.removers.IllegalSignatureRemover
  - normalizer.SourceFileClassNormalizer
```

Console Result:

```
$ java -jar deobfuscator.jar --config config.yml                                                                        [main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 64 source filenames
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
```

THANKS!
