### ISSUE TITLE
The deobfuscator does not work when i add LWJGL.jar as library

### ISSUE THREAD

**Issue by Eptiiix** [java-deobfuscator/deobfuscator#589]
The deobfuscator does not work when i add LWJGL.jar as library

java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:106)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:141)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by nedogimov** [comment]
> The deobfuscator does not work when i add LWJGL.jar as library
> 
> java.lang.IllegalArgumentException
> at org.objectweb.asm.ClassReader.(ClassReader.java:160)
> at org.objectweb.asm.ClassReader.(ClassReader.java:143)
> at org.objectweb.asm.ClassReader.(ClassReader.java:418)
> at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:106)
> at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:141)
> at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:327)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
> at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
> at java.lang.Thread.run(Unknown Source)

Corrupt jar, try another version

**Comment by ItzSomebody** [comment]
I'm not *exactly* sure what's the problem here, but I'm guessing the most likely error is an unsupported classfile version (since this was prior to the ASM version being bumped to ASM 8). If the issue persists, feel free to post it again.
