### ISSUE TITLE
stringer.ReflectionObfuscationTransformer : failed

### ISSUE THREAD

**Issue by zip62** [java-deobfuscator/deobfuscator#59]
Hello,

```
Reading complete. Loading hierachy

Transforming

[Stringer] [ReflectionObfuscationTransformer] Starting
[Stringer] [ReflectionObfuscationTransformer] Found 262 reflection obfuscation calls
Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/util/Hashtable get(Ljava/lang/Object;)Ljava/lang/Object; @ com/sun/media/jai/util/PropertyUtil getString(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1076)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.executor.defined.DictionaryMethodProvider.invokeMethod(DictionaryMethodProvider.java:49)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:36)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1149)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.executor.defined.DictionaryMethodProvider.invokeMethod(DictionaryMethodProvider.java:49)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:36)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1149)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$null$10(ReflectionObfuscationTransformer.java:186)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$decrypt$11(ReflectionObfuscationTransformer.java:118)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.decrypt(ReflectionObfuscationTransformer.java:117)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:67)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Thanks

**Comment by Janmm14** [comment]
Are you sure that the jar you have is obfuscated by stringer?

**Comment by zip62** [comment]
No, i'am not sure.
I have open this ticket because the program ask.

**Comment by Janmm14** [comment]
Maybe try other reflection obfuscation transformer first or try running string obfuscation transformation before reflection obfuscation.

**Comment by zip62** [comment]
OK. Thanks
