### ISSUE TITLE
ERROR - GC overhead limit exceeded

### ISSUE THREAD

**Issue by MisterSevent** [java-deobfuscator/deobfuscator#596]
When I'm going to execute, it crashes in a few seconds and then this message appears

_**### Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.objectweb.asm.tree.MethodNode.visitVarInsn(MethodNode.java:433)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1476)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1016)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.v9.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:34)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)**_

**Comment by Michael18751** [comment]
Same here:

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(Unknown Source)
	at java.lang.StringBuilder.<init>(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:145)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapMethodName(CustomRemapper.java:42)
	at org.objectweb.asm.commons.ClassRemapper.visitMethod(ClassRemapper.java:121)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:724)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer$$Lambda$22/1453602872.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by ThisTestUser** [comment]
For the first error, use stringer.StringEncryptionTransformer instead. It is much faster.
For the second error, you probably should give the deobfuscator.jar more memory, but if it still doesn't work, you could use an obfuscator like proguard to rename the classes instead.

**Comment by Michael18751** [comment]
How do I give it more memory?

**Comment by GhostFace54** [comment]
in command line you do for example 5GB of RAM `java -Xmx5120 -Xms5120 -jar deobfuscator.jar --config [config file]`
