### ISSUE TITLE
general.peephole.PeepholeOptimizer : failed

### ISSUE THREAD

**Issue by zip62** [java-deobfuscator/deobfuscator#60]
Hello,

```
Reading complete. Loading hierachy

Transforming

Rearranged 956 goto blocks
Removed 77 continous gotos
Removed 0 unconditional switches
Error while removing dead code from com/sun/media/jai/util/SunTileScheduler scheduleJob(Ljavax/media/jai/PlanarImage;[Ljava/awt/Point;ZZ[Ljavax/media/jai/TileComputationListener;)Ljava/lang/Object;
Deobfuscation failed. Please open a ticket on GitHub
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:403)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:267)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:221)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$null$2(DeadCodeRemover.java:42)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$transform$3(DeadCodeRemover.java:40)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:39)
        at com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer.transform(PeepholeOptimizer.java:45)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Thanks

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists.
