### ISSUE TITLE
normalizer.MethodNormalizer : failed

### ISSUE THREAD

**Issue by zip62** [java-deobfuscator/deobfuscator#61]
Hello,

```
Reading complete. Loading hierachy

Transforming

Deobfuscation failed. Please open a ticket on GitHub
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.String.toCharArray(Unknown Source)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.Type.getMethodType(Type.java:241)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$null$7(MethodNormalizer.java:166)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer$$Lambda$18/1529918258.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$transform$10(MethodNormalizer.java:161)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer$$Lambda$12/1916400826.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.transform(MethodNormalizer.java:47)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Thanks

**Comment by Janmm14** [comment]
Program does not have enough ram. How much ram you gave it or how much ram do you have?

**Comment by zip62** [comment]
OK. I have 2Gb.
.jar is 35Mb

**Comment by Janmm14** [comment]
Well this looks like there may be an issue in this decompiler or the jar file contains some rubbish classes with very long strings or something like that.

**Comment by zip62** [comment]
OK. Thanks
