### ISSUE TITLE
normalizer.FieldNormalizer : failed

### ISSUE THREAD

**Issue by zip62** [java-deobfuscator/deobfuscator#62]
Hello,

```
Reading complete. Loading hierachy

Transforming

Deobfuscation failed. Please open a ticket on GitHub
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.String.substring(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:140)
        at com.javadeobfuscator.deobfuscator.org.objectweb.asm.commons.Remapper.mapDesc(Remapper.java:63)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapFieldName(CustomRemapper.java:118)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.lambda$transform$0(FieldNormalizer.java:79)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer$$Lambda$12/1916400826.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.transform(FieldNormalizer.java:43)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Thanks

**Comment by Janmm14** [comment]
See https://github.com/java-deobfuscator/deobfuscator/issues/61#issuecomment-246537025

**Comment by zip62** [comment]
OK. I have 2Gb.
.jar is 35Mb

I will test tomorrow on a 16Gb.

**Comment by zip62** [comment]
Hello,

I have the same problem on my six core processor with 16 Gb of memory : 

```
Reading complete. Loading hierachy


Transforming

Deobfuscation failed. Please open a ticket on GitHub
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:152)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:152)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:152)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:140)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapFieldName(CustomRemapper.java:107)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.lambda$transform$0(FieldNormalizer.java:79)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer$$Lambda$13/681463887.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.transform(FieldNormalizer.java:43)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Thanks

**Comment by samczsun** [comment]
Well this is certainly interesting. I certainly wish I'd responded to this earlier, but please do open a new issue if you don't mind
