### ISSUE TITLE
Need help in Deobfuscating this please

### ISSUE THREAD

**Issue by ajayjony** [java-deobfuscator/deobfuscator#620]
**The errors I'm getting are:**

        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1329)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:336)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:264)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:80)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by Janmm14** [comment]
probably invalid config file

**Comment by ajayjony** [comment]
I tried it on gui and it gives me this error:

[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - 
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleIllegalSignature: Some obfuscators will set the signature of a class/method/field to an illegal value. This may crash naive decompilers/disassemblers
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - 	Found illegal class signature for GraphicInterface/Interface$94
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[Thread-5] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - 	com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover


can someone please add me on Discord frozensunshine#1814

**Comment by Janmm14** [comment]
That is no error.

**Comment by Enteerman** [comment]
First: Invalid Config file.

Second: It didn't exit with error, it was on detect mode.
