### ISSUE TITLE
 can't deobfuscate Paramorphism 

### ISSUE THREAD

**Issue by CNSnowFlake** [java-deobfuscator/deobfuscator#621]
it can't load jar completely
i enable  boolean PARAMORPHISM but it doesn't work

* error exception
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse - Could not parse //.class (is it a class file?)
java.lang.ArrayIndexOutOfBoundsException: 6
	at org.objectweb.asm.ClassReader.readShort(ClassReader.java:3580)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:194)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:256)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:246)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:66)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:811)
	at java.lang.Thread.run(Unknown Source)
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.special.ParamorphismTransformer
[Special] [ParamorphismTransformer] Starting
[Special] [ParamorphismTransformer] Removed 0 annotations
[Special] [ParamorphismTransformer] Removed 0 flow obfuscations
[Special] [ParamorphismTransformer] Decrypted 0 method calls
[Special] [ParamorphismTransformer] Decrypted 0 field calls
[Special] [ParamorphismTransformer] Decrypted 0 strings
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing

**Comment by CNSnowFlake** [comment]
Paramorphism and paramorphism v2 the Boolean value of V2 is reversed
