### ISSUE TITLE
Is it possible to deobf this

### ISSUE THREAD

**Issue by Fonix420** [java-deobfuscator/deobfuscator#622]
I found the obfuscator its this [https://github.com/superblaubeere27/obfuscator](url)

**Comment by ThisTestUser** [comment]
Special.JObfTransformer will help here.

**Comment by Fonix420** [comment]
> 
> 
> Special.JObfTransformer will help here.

It crashes when using Special.JObfTransformer

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/security/MessageDigest$Delegate digest([B)[B @ org/newdawn/slick/geom/Vector2f lIIIlllIl(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1246)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1392)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.transformers.special.JObfTransformer.transform(JObfTransformer.java:416)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
@ThisTestUser what could cause the super class lookup to fail here?

**Comment by ThisTestUser** [comment]
It might be the HWID protection feature in the obfuscator.
