### ISSUE TITLE
Did you know where i can find : com/sun/medialib/codec/jiio/mediaLibImage ?

### ISSUE THREAD

**Issue by zip62** [java-deobfuscator/deobfuscator#63]
Hello,

I need the .jar file that contain : com/sun/medialib/codec/jiio/mediaLibImage

I don't find it with Google.

Dou you have any idea ?

```
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: com/sun/medialib/codec/jiio/mediaLibImage
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$null$7(MethodNormalizer.java:173)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.lambda$transform$10(MethodNormalizer.java:161)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer.transform(MethodNormalizer.java:47)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

Thanks

**Comment by Janmm14** [comment]
First try adding other jars inside the lib directory of you java installation. If that does not help, download the java jdk and try adding every jar file of the lib directory.

But first try to only specify the lib directory without mentioning any jar file, it might work that it searches the whole directory

**Comment by zip62** [comment]
OK. Thanks
