### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LolTDMMMOs** [java-deobfuscator/deobfuscator#633]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:338)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

--Config.yaml
input: Atom.jar
output: Atom-DEOBF.jar
path:
 - /usr/lib/jvm/bellsoft-java8-full-amd64/jre/lib/rt.jar
transformers:
-

**Comment by Enteerman** [comment]
Please specify transformers

**Comment by Enteerman** [comment]
Please close @LolTDMMMOs
