### ISSUE TITLE
Deobfuscation failed (Stringer)

### ISSUE THREAD

**Issue by snuckdev** [java-deobfuscator/deobfuscator#646]
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$1$42.lambda$3(JVMMethodProvider.java:602)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider$Function3.applyUnchecked(JVMMethodProvider.java:974)
        at com.javadeobfuscator.deobfuscator.executor.defined.JVMMethodProvider.invokeMethod(JVMMethodProvider.java:889)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1200)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$4(HideAccessObfuscationTransformer.java:145)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$2(HideAccessObfuscationTransformer.java:127)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:126)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

**Comment by snuckdev** [comment]
Transformers:
- com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer
- com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
- com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer

**Comment by ItzSomebody** [comment]
If you are able, can you provide a sample that causes this to happen?

**Comment by snuckdev** [comment]
Yes of course.
[AtlasLeilao.zip](https://github.com/java-deobfuscator/deobfuscator/files/5351300/AtlasLeilao.zip)

**Comment by Janmm14** [comment]
@snuckdev 
"Sample" implies, just as the information during issue creation implies, that you have the rights to (re-)publish/share. Unfortunaly I am 99.999% sure that this is not the case with the sample you provided. Please delete it.

@ItzSomebody @Enteerman

**Comment by snuckdev** [comment]
Man here in Brazil it's leaked
