### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FakeException** [java-deobfuscator/deobfuscator#663]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(Unknown Source)
	at org.objectweb.asm.Type.getObjectType(Type.java:253)
	at org.objectweb.asm.commons.Remapper.mapType(Remapper.java:79)
	at org.objectweb.asm.commons.Remapper.mapType(Remapper.java:97)
	at org.objectweb.asm.commons.ClassRemapper.visit(ClassRemapper.java:107)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:385)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by ItzSomebody** [comment]
If you're able to, can you provide a sample of when this occurs (provided you aren't violating some copyright license)?

**Comment by FakeException** [comment]
when i try to use SourceFileClassNormalizer i get that error, the packages of the jar are something like that
![image](https://user-images.githubusercontent.com/51448775/99226997-f1f30c00-27ea-11eb-8f07-3428dfba026a.png)

**Comment by fee1-dead** [comment]
You should not use `SourceFileClassNormalizer` for java applications that intentionally modify the SourceFile attributes to confuse people.
