### ISSUE TITLE
Deobfuscation Failed. Out of memory.

### ISSUE THREAD

**Issue by lilsketchy** [java-deobfuscator/deobfuscator#667]
So i'm trying to deobfuscate, but it just failed idk why, here's the error message. I'm using the latest release of the Deobfuscator.
Can someone help me deobfuscate it? I really need this.
Discord: aglerr#9849

```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(Unknown Source)
	at java.lang.StringBuilder.<init>(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:145)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapMethodName(CustomRemapper.java:42)
	at org.objectweb.asm.commons.ClassRemapper.visitMethod(ClassRemapper.java:187)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:465)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer$$Lambda$23/1515168023.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by fee1-dead** [comment]
See #642, If you are trying to remap to a normal name, I recommend using ProGuard because they are good at this.
