### ISSUE TITLE
Allatori String Decryption Problem

### ISSUE THREAD

**Issue by Revocation** [java-deobfuscator/deobfuscator#67]
Hi, how are you? Hope fine, today trying to decrypt some Allatori String, I found this error:

```
Reading complete. Loading hierachy
Transforming

Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
IiIIiiiIIIiIi <clinit>()V IiIIiiiIIIiIi anyValidIdentifierName(Ljava/lang/String
;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for java/lang/System getProperty(Ljava/lang/String;)L
java/lang/String; @ IiIIiiiIIIiIi anyValidIdentifierName(Ljava/lang/String;)Ljav
a/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
IiIIiiiIIIiIi <clinit>()V IiIIiiiIIIiIi anyValidIdentifierName(Ljava/lang/String
;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for java/lang/System getProperty(Ljava/lang/String;)L
java/lang/String; @ IiIIiiiIIIiIi anyValidIdentifierName(Ljava/lang/String;)Ljav
a/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
IiIIiiiIIIiIi <clinit>()V IiIIiiiIIIiIi anyValidIdentifierName(Ljava/lang/String
;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for java/lang/System getProperty(Ljava/lang/String;)L
java/lang/String; @ IiIIiiiIIIiIi anyValidIdentifierName(Ljava/lang/String;)Ljav
a/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
IiIIiiiIIIiIi <clinit>()V IiIIiiiIIIiIi anyValidIdentifierName(Ljava/lang/String
;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for java/lang/System getProperty(Ljava/lang/String;)L
java/lang/String; @ IiIIiiiIIIiIi anyValidIdentifierName(Ljava/lang/String;)Ljav
a/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
IIiiiiIiiIIII toString()Ljava/lang/String; IIiiiiIiiIIII iIIiIIiIiIIIi(Ljava/lan
g/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.ExecutionException: getFie
ld failed @ IIiiiiIiiIIII iIIiIIiIiIIIi(Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvid
er.getField(DelegatingProvider.java:75)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:985)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)

Transforming complete. Writing to file
```

If you need the Jar, I've sent to your email with the subject #67, thanks dude.

**Comment by samczsun** [comment]
Your link does not appear to work

**Comment by Revocation** [comment]
> Your link does not appear to work
You're right bro, **sent again**. Thanks.

**Comment by samczsun** [comment]
I see, these appear to be false positives because there is a method that actually gets a property using `System.getProperty`. The getField failing one is again a real method which has the same signature as a decryption method.
