### ISSUE TITLE
Error ZKM Reflection Obfuscation

### ISSUE THREAD

**Issue by kaymikoda** [java-deobfuscator/deobfuscator#671]
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
[Zelix] [ReflectionObfuscationTransformer] Starting
[Zelix] [ReflectionObfuscationTransformer] Finding reflection obfuscation
[Zelix] [ReflectionObfuscationTransformer] Found 75 reflection obfuscation instructions
Error while fully initializing de/mypackage/anotherone/aO
java.lang.NullPointerException
	at java.lang.reflect.Array.get(Native Method)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:100)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:507)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1396)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:590)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:69)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at Main.main(Main.java:28)
Exception in thread "main" com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/Object toCharArray()[C @ de/mypackage/anotherone/ha a(J)I
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1250)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1396)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1396)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:624)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:69)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at Main.main(Main.java:28)

**Comment by kaymikoda** [comment]
[example classes.zip](https://github.com/java-deobfuscator/deobfuscator/files/5642834/example.classes.zip)

**Comment by Janmm14** [comment]
You did not add rt.jar aka java stdlib jar to the path
