### ISSUE TITLE
java.lang.ClassCastException: org.objectweb.asm.tree.InsnNode cannot be cast to org.objectweb.asm.tree.LdcInsnNode

### ISSUE THREAD

**Issue by 2934899534** [java-deobfuscator/deobfuscator#673]
java.lang.ClassCastException: org.objectweb.asm.tree.InsnNode cannot be cast to org.objectweb.asm.tree.LdcInsnNode
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:501)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:69)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
Did you use zelix.StringEncryptionTransformer first? You should read the commonerrors (https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Zelix.md) for Zelix.

**Comment by ThisTestUser** [comment]
Try deobfuscating again with the latest release (https://github.com/java-deobfuscator/deobfuscator/releases/tag/1.5). If nothing got detected that means that this specific obfuscation version is unsupported.

**Comment by ItzSomebody** [comment]
Since there is no jar attached and the OP hasn't responded for quite a while now, I'll go ahead and close this.

OP: Feel free to comment if needed.
