### ISSUE TITLE
Infinity java.security reading

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#688]
I use zelix.string.SimpleStringEncryptionTransformer, because default zelix.StringEncryptionTransformer doesn't works on ZKM 12.0.1, so, after decryption I get infinity opening java.security, how to fix it?

P.s. Args -Xmx5100M -Xms5100M

```
[Thread-2] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer - Decrypted string in net/minecraft/ab8 r()V: push
[Thread-2] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer - Decrypted string in net/minecraft/ab8 <clinit>()V: CL_00001549
[Thread-2] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer - Decrypted string in net/minecraft/ab8 <clinit>()V: 662A6B8D-DA3E-4C1C-8813-96EA6097278D
[Thread-2] INFO com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer - Decrypted string in net/minecraft/ab8 <clinit>()V: Sprinting speed boost
[Filesystem] Getting boolean attributes of C:\Program Files\Java\jdk1.8.0_271\jre\lib\security\java.security (C:\java_home_dir\lib\security\java.security)
[Filesystem] Opening C:\Program Files\Java\jdk1.8.0_271\jre\lib\security\java.security (C:\java_home_dir\lib\security\java.security) for reading
```

Error when I use zelix.StringEncryptionTransformer:

```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Unknown action for encrypted strings array
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$0(StringEncryptionTransformer.java:1284)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:98)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Xed0sS** [comment]
I'm solved this problem, just replace this file in java security folder.
https://www.upload.ee/files/12729328/java.security.html
