### ISSUE TITLE
 unexpected different size of values SourceResult

### ISSUE THREAD

**Issue by JceDaniel** [java-deobfuscator/deobfuscator#693]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: unexpected different size of values SourceResult{values=[1, 2, 3], exceptions=[]} SourceResult{values=[1, 3], exceptions=[]}
at com.javadeobfuscator.deobfuscator.asm.source.ConstantPropagatingSourceFinder.findSource(
ConstantPropagatingSourceFinder.java:57)
at com.javadeobfuscator.deobfuscator.asm.source.SourceFinder.findSource(SourceFinder.java:81)
 at com.javadeobfuscator.deobfuscator.asm.source.ConstantPropagatingSourceFinder.findSource(
ConstantPropagatingSourceFinder.java:52)
at com.javadeobfuscator.deobfuscator.asm.source.SourceFinder.findSource(SourceFinder.java:81)
at com.javadeobfuscator.deobfuscator.transformers.dasho.string.StringEncryptionTransformer.transform(
StringEncryptionTransformer.java:75)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ThisTestUser** [comment]
You should probably read the commonerrors for DashO: https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/DashO.md

**Comment by jssdaniel** [comment]
**Also can you make me a suggestion about this.**

[DashO] [FlowObfuscationTransformer] Starting
[DashO] [FlowObfuscationTransformer] Suspected 55 flow obfuscated chunks
[DashO] [FlowObfuscationTransformer] Removed 52 flow obfuscated chunks
[DashO] [FlowObfuscationTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/awt/Dimension could not be found while writing l$i. Using COMPUTE_MAXS
Error: java/security/cert/CertificateException could not be found while writing j. Using COMPUTE_MAXS

**Comment by ItzSomebody** [comment]
Add the appropriate library to your config path (both are under rt.jar/java.base, if I recall correctly).

**Comment by jssdaniel** [comment]
**The .jar come with .cfg file and own RunTime**

[Application]
app.name=App
app.mainjar=app-jfx.jar
app.version=3.1.2
app.preferences.id=com/app
app.mainclass=com/app/App
app.classpath=lib/afterburner.fx-1.7.0.jar;lib/javax.servlet-api-3.1.0.jar;lib/javax.annotation-api-1.2.jar;..............etc;
app.runtime=$APPDIR\runtime
app.identifier=com.app

[JVMOptions]
-Duser.timezone=America/New_York
-Dfile.encoding=UTF8

[JVMUserOptions]

[ArgOptions]

**Comment by fee1-dead** [comment]
ok Ignore everything else and add all the jars from `app.classpath` to deobfuscator config

**Comment by jssdaniel** [comment]
->       package com.javadeobfuscator.deobfuscator.config;
@JsonProperty
    private List<File> libraries;
**I suppose that**
libraries:
  - "C:\\Users\\MyName\\filename.jar"
  - "etc"
**I'm not ready to surprise myself yet.
Thank you!**

**Comment by jssdaniel** [comment]
Error: failed to compute frames

**Comment by ThisTestUser** [comment]
Use dasho.StringEncryptionTransformer instead.

**Comment by JceDaniel** [comment]
**I will try with other laptops and other java vm**

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:201)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1014)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
	at com.javadeobfuscator.deobfuscator.transformers.dasho.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:39)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by ThisTestUser** [comment]
That just means you need to add more RAM to the deobfuscator.

**Comment by JceDaniel** [comment]
I am trying to find a laptop of more than 12 Gb. The flowObfuscation helped me a lot (inner switch of 100 lines-> 5 lines).  The current drawback is in the Strings ("$ 8 # vdiwh38 / $ 28 #? / * 29bdi29rye").  Soon I will share the error itself if I think it is compute frames but I have to confirm it
![IMG_20210209_150628](https://user-images.githubusercontent.com/57338715/108567074-21735200-72cd-11eb-967d-93e3a89d99ab.jpg)

**Comment by JceDaniel** [comment]
The tests I have done is with 8Gb RAM i3 and i5

**Comment by JceDaniel** [comment]
The only Java that has worked for me is adoptOpenJDK 8. The superiors to that version fail me with an rt.jar error that when those versions stopped using that file since it is missing in the installation path

**Comment by JceDaniel** [comment]
Also I have been trying to use the java path of the Application;  that has a runtime folder.  With rt.jar and other files from where I suppose the application starts but it still failed me.  At the moment I just hope to get a 32 Gb desktop to try again.

**Comment by Janmm14** [comment]
With some fast usb stick you can tell windows to use it as ram, maybe thats a possible solution for you.

**Comment by ThisTestUser** [comment]
You are using dasho.string.StringEncryptionTransformer, which is slow. You should instead use dasho.StringEncryptionTransformer which is much faster.

**Comment by JceDaniel** [comment]
I can go a little further;  use a readyboost on a 8Gb sd card.
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.dasho.StringEncryptionTransformer
[DashO] [StringEncryptionTransformer] Starting
[DashO] [StringEncryptionTransformer] Decrypted 120 encrypted strings
[DashO] [StringEncryptionTransformer] Removed 8 decryption methods
[DashO] [StringEncryptionTransformer] Done
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: failed to compute frames
Error: failed to compute frames
