### ISSUE TITLE
Deobfuscation problem

### ISSUE THREAD

**Issue by AlbertoBer** [java-deobfuscator/deobfuscator#695]
I can't deobfuscate that jar: https://www.mediafire.com/file/8argilkt5t4b5n4/CAC.jar/file i tried all the transformers but nothing happen, i think it's obfuscated with Radon (https://github.com/ItzSomebody/Radon)

**Comment by fee1-dead** [comment]
What do you mean by "nothing happen"?

**Comment by AlbertoBer** [comment]
No output was given

**Comment by AlbertoBer** [comment]
Or if it gave me an output it was identical to the original one

**Comment by fee1-dead** [comment]
What were you trying to accomplish? What transformers have you tried? Can you attach configuration files of your attempts?

**Comment by AlbertoBer** [comment]
Here's my config: java -jar deobfuscator.jar -input C:\Users\Lorenzo\Cac.jar -output C:\Users\Lorenzo\Downloads\output.jar -transformer general.peephole.DeadCodeRemover -transformer special.SuperblaubeereTransformer -verify -detect

**Comment by AlbertoBer** [comment]
I'm trying to make code at least readable

**Comment by fee1-dead** [comment]
Why are you using `SuperblaubeereTransformer` if you think it is obfuscated with Radon?

**Comment by AlbertoBer** [comment]
Because with RadonTransformer it gives me an error:
[Thread-5] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse me/clientastisch/checks/Checks.class (is it a class file?)
java.lang.ArrayIndexOutOfBoundsException: 6
	at org.objectweb.asm.ClassReader.readShort(ClassReader.java:3580)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:194)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:256)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:246)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by AlbertoBer** [comment]
So i tried all transformers 1 to 1

**Comment by fikawka** [comment]
> So i tried all transformers 1 to 1.
> I do this out of desperation, I've been trying for 3 days

Try illegal signature remover, then in the deobfuscated jar use radon transformer, if v2 doesnt work try v1

**Comment by ThisTestUser** [comment]
Don't use -detect in your config. Also you can ignore the "Could not parse" error, especially if it only happens for a few classes.
