### ISSUE TITLE
Allatori Deobfuscator Issue

### ISSUE THREAD

**Issue by DefSmile** [java-deobfuscator/deobfuscator#696]
I was given this error and told said to provide the error here.
This was using:
allatori.FlowObfusctionTransformer
allatori.StringEncryptionTransformer
allatori.string.StringEncryptionTransformer
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
	at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
	at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
	at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.base/java.lang.Thread.run(Thread.java:834)
`
If you need more info let me know.

**Comment by Janmm14** [comment]
Try without allatori.string.StringEncryptionTransformer and look if it deobfuscates correctly.

**Comment by DefSmile** [comment]
> Try without allatori.string.StringEncryptionTransformer and look if it deobfuscates correctly.

So it kind of works, I don't get the NPE but now with
normalizer.SourceFileClassNormalizer
allatori.StringEncryptionTransformer
allatori.LightFlowObfuscationTransformer

the first 2 work fine but when it gets to LightFlowTransformer it throws this
`[Thread-8] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.LightFlowObfuscationTransformer
[Allatori] [LightFlowObfuscationTransformer] Starting
[Allatori] [LightFlowObfuscationTransformer] Removed 1558 dead instructions
[Allatori] [LightFlowObfuscationTransformer] Done
[Thread-8] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/Object could not be found while writing oshi/software/os/IIii/vp. Using COMPUTE_MAXS
Error: java/awt/Point could not be found while writing com/sun/jna/platform/dm$W32WindowUtils$W32TransparentContentPane. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/COM/tlb/imp/yaa. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oxygen/client/lm. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/hardware/platform/mac/sy. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/hardware/platform/mac/tq. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing walker/engine/pathfinding/de. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing org/slf4j/IiiiIIiIIi/qaa. Using COMPUTE_MAXS
Error: java/lang/NumberFormatException could not be found while writing com/sun/jna/via. Using COMPUTE_MAXS
Error: java/lang/UnsupportedOperationException could not be found while writing oshi/software/os/linux/yo. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/software/os/IIii/nu. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/aca. Using COMPUTE_MAXS
Error: java/util/ArrayList could not be found while writing oshi/software/os/IIii/lw. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/hardware/platform/IIii/ny2. Using COMPUTE_MAXS
Error: java/lang/NumberFormatException could not be found while writing oshi/IIii/cs. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/IIii/IIii/IIii/dc1. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/hardware/platform/IIii/vu. Using COMPUTE_MAXS
Error: java/lang/UnsatisfiedLinkError could not be found while writing oshi/software/os/IIii/kx. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing oshi/driver/IIii/IIii/IIii/mx. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/driver/IIii/IiiiiII/mja. Using COMPUTE_MAXS
Error: java/time/format/DateTimeParseException could not be found while writing oshi/driver/IIii/nt. Using COMPUTE_MAXS
Error: java/lang/SecurityException could not be found while writing oshi/IIii/gp. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oxygen/client/util/dd. Using COMPUTE_MAXS
Error: java/lang/UnsatisfiedLinkError could not be found while writing oshi/software/os/linux/lv. Using COMPUTE_MAXS
Error: java/lang/Integer could not be found while writing oxygen/client/loader/nn. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/software/os/IiiiIIiIIi/IIii/yq. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/jia. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing oxygen/api/accessors/up. Using COMPUTE_MAXS
Error: java/lang/Enum could not be found while writing walker/engine/pathfinding/uj. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/google/gson/caa. Using COMPUTE_MAXS
Error: java/lang/Class could not be found while writing com/google/gson/IIii/pea3. Using COMPUTE_MAXS
Error: java/util/HashMap could not be found while writing org/slf4j/IiiiIIiIIi/mha. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/hardware/platform/mac/cw. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing org/slf4j/dfa. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/wb$FFIType. Using COMPUTE_MAXS
Error: java/io/File could not be found while writing oxygen/client/loader/zk. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/software/os/linux/ey. Using COMPUTE_MAXS
Error: java/lang/IllegalArgumentException could not be found while writing oshi/IIii/IIii/IIii/nr. Using COMPUTE_MAXS
Error: java/lang/reflect/Method could not be found while writing com/sun/jna/ija. Using COMPUTE_MAXS
Error: java/lang/UnsatisfiedLinkError could not be found while writing com/sun/jna/win32/dia. Using COMPUTE_MAXS
Error: java/lang/NumberFormatException could not be found while writing oshi/IIii/ry. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/hardware/cc2. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing oxygen/client/loader/ue. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/google/gson/IIii/IIii/gfa. Using COMPUTE_MAXS
Error: java/util/Date could not be found while writing com/google/gson/IIii/IiiiIIiIIi/zia. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/google/gson/jca. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing org/slf4j/impl/bfa. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing com/sun/jna/platform/win32/COM/tlb/imp/oia. Using COMPUTE_MAXS
Error: java/lang/RuntimeException could not be found while writing com/sun/jna/platform/win32/uka. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/COM/tlb/imp/oba. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oxygen/client/loader/gj. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing oxygen/api/internal/yp. Using COMPUTE_MAXS
Error: java/util/Date could not be found while writing com/google/gson/fea. Using COMPUTE_MAXS
Error: java/io/File could not be found while writing oxygen/client/loader/em. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oxygen/client/loader/ei. Using COMPUTE_MAXS
Error: java/awt/dnd/DragSourceContext could not be found while writing com/sun/jna/platform/dnd/oja. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/google/gson/IIii/IiiiIIiIIi/lda1. Using COMPUTE_MAXS
Error: java/lang/Appendable could not be found while writing com/google/gson/gea5. Using COMPUTE_MAXS
Error: java/lang/NoSuchMethodException could not be found while writing com/sun/jna/platform/win32/COM/util/fla. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/hardware/platform/IiiiIIiIIi/IIii/xv. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/software/os/IiiiIIiIIi/IiiiiII/oq. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/driver/windows/IIii/eq. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/hardware/platform/IIii/mz. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/COM/vca. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/hardware/platform/IIii/hv. Using COMPUTE_MAXS
Error: java/util/List could not be found while writing oshi/driver/IIii/IiiiIIiIIi/IIii/mu. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing oshi/software/os/IiiiIIiIIi/IiiiiII/uw. Using COMPUTE_MAXS
Error: java/lang/reflect/InvocationTargetException could not be found while writing org/slf4j/IiiiIIiIIi/hea. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/driver/windows/IIii/gx. Using COMPUTE_MAXS
Error: java/lang/Integer could not be found while writing com/sun/jna/platform/win32/COM/sda$WmiQuery. Using COMPUTE_MAXS
Error: java/awt/Container could not be found while writing com/IiiiIIiIIi/IIii/IIii/ika. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/hardware/platform/linux/ls. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing com/sun/jna/platform/dm$W32WindowUtils. Using COMPUTE_MAXS
Error: java/lang/Class could not be found while writing com/sun/jna/wm. Using COMPUTE_MAXS
Error: java/lang/SecurityException could not be found while writing com/sun/jna/wb. Using COMPUTE_MAXS
Error: javax/swing/RootPaneContainer could not be found while writing com/sun/jna/platform/dm$MacWindowUtils. Using COMPUTE_MAXS
Error: java/io/RandomAccessFile could not be found while writing com/sun/jna/oea$ELFSectionHeaders. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing oxygen/client/loader/wn1. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing com/sun/jna/platform/win32/fk$DdeClient. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/COM/tlb/imp/ria. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/google/gson/eaa. Using COMPUTE_MAXS
Error: java/time/LocalDate could not be found while writing oshi/hardware/IIii/zy1. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing com/sun/jna/pia. Using COMPUTE_MAXS
Error: java/awt/Container could not be found while writing com/IiiiIIiIIi/IIii/IIii/sia. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing oshi/software/os/IiiiIIiIIi/IiiiiII/fs. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/hardware/platform/linux/ww. Using COMPUTE_MAXS
Error: java/util/Date could not be found while writing org/slf4j/impl/cka. Using COMPUTE_MAXS
Error: java/lang/Long could not be found while writing oshi/hardware/IIii/nx. Using COMPUTE_MAXS
Error: java/time/format/DateTimeParseException could not be found while writing oshi/driver/IIii/IiiiiII/nt. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing walker/engine/bn. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/hardware/platform/IiiiIIiIIi/IiiiIIiIIi/zz. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/software/os/IiiiiII/lq. Using COMPUTE_MAXS
Error: java/util/regex/Matcher could not be found while writing oshi/hardware/platform/IiiiIIiIIi/IiiiIIiIIi/yu. Using COMPUTE_MAXS
Error: javax/swing/tree/TreeNode could not be found while writing oxygen/api/internal/ps. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/COM/util/dea$CallbackProxy2. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oshi/software/os/IiiiiII/oy. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/COM/tlb/imp/ffa. Using COMPUTE_MAXS
Error: java/util/TreeSet could not be found while writing com/sun/jna/platform/sd. Using COMPUTE_MAXS
Error: java/lang/Class could not be found while writing com/google/gson/IIii/gia3. Using COMPUTE_MAXS
Error: java/lang/Class could not be found while writing com/google/gson/IiiiiII/ek. Using COMPUTE_MAXS
Error: java/util/NoSuchElementException could not be found while writing com/google/gson/nca. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing com/sun/jna/platform/win32/COM/tlb/imp/wba. Using COMPUTE_MAXS
Error: java/io/InputStream could not be found while writing com/sun/jna/platform/win32/COM/tlb/imp/jla. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing com/sun/jna/xga. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing com/sun/jna/platform/win32/COM/tlb/imp/fba. Using COMPUTE_MAXS
Error: java/lang/reflect/Method could not be found while writing com/google/gson/IIii/pda. Using COMPUTE_MAXS
Error: java/lang/RuntimeException could not be found while writing com/sun/jna/platform/win32/lca. Using COMPUTE_MAXS
Error: java/awt/Container could not be found while writing com/sun/jna/platform/dm$X11WindowUtils$3. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/xea. Using COMPUTE_MAXS
Error: java/util/Optional could not be found while writing oshi/software/os/IiiiIIiIIi/IIii/lu. Using COMPUTE_MAXS
Error: jdk/internal/org/objectweb/asm/tree/FieldInsnNode could not be found while writing oxygen/client/IIii/ck. Using COMPUTE_MAXS
Error: jdk/internal/org/objectweb/asm/tree/FieldInsnNode could not be found while writing oxygen/client/IIii/cj. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing com/sun/jna/platform/win32/sha. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/pn$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oxygen/api/containers/qo. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oxygen/api/containers/px. Using COMPUTE_MAXS
Error: jdk/internal/org/objectweb/asm/tree/MethodInsnNode could not be found while writing oxygen/client/IIii/ah. Using COMPUTE_MAXS
Error: java/lang/Exception could not be found while writing oxygen/client/util/kl. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oxygen/client/util/ko. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/sun/jna/platform/win32/fha. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing com/sun/jna/oea. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing walker/cn. Using COMPUTE_MAXS
Error: jdk/internal/org/objectweb/asm/tree/FieldInsnNode could not be found while writing oxygen/client/IIii/gh. Using COMPUTE_MAXS
Error: jdk/internal/org/objectweb/asm/tree/FieldInsnNode could not be found while writing oxygen/client/IIii/jm. Using COMPUTE_MAXS
Error: jdk/internal/org/objectweb/asm/tree/VarInsnNode could not be found while writing oxygen/client/IIii/sn. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing com/sun/jna/jda. Using COMPUTE_MAXS
Error: java/lang/Integer could not be found while writing oshi/driver/IIii/IiiiiII/zga. Using COMPUTE_MAXS
Error: java/awt/Container could not be found while writing com/sun/jna/platform/dm$W32WindowUtils$2. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing com/google/gson/IIii/IiiiIIiIIi/pfa. Using COMPUTE_MAXS
Error: java/lang/Throwable could not be found while writing com/sun/jna/platform/dm$W32WindowUtils$3. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing oshi/software/os/IiiiIIiIIi/IiiiIIiIIi/ys. Using COMPUTE_MAXS
Error: java/awt/Component could not be found while writing com/IiiiIIiIIi/IIii/IIii/cga. Using COMPUTE_MAXS
Error: java/lang/reflect/Type could not be found while writing com/google/gson/IIii/IiiiIIiIIi/pha. Using COMPUTE_MAXS
Error: java/lang/RuntimeException could not be found while writing walker/rl. Using COMPUTE_MAXS
Error: java/lang/NumberFormatException could not be found while writing com/google/gson/IIii/IiiiIIiIIi/IIii/ska. Using COMPUTE_MAXS
Error: java/lang/Class could not be found while writing com/sun/jna/platform/win32/COM/util/lja. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oxygen/api/events/kp. Using COMPUTE_MAXS
Error: java/lang/reflect/Field could not be found while writing com/google/gson/IIii/tfa1. Using COMPUTE_MAXS
Error: java/awt/dnd/DropTargetContext could not be found while writing com/sun/jna/platform/dnd/yja. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing oxygen/api/events/ge/pv. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing com/sun/jna/il. Using COMPUTE_MAXS
`

**Comment by Janmm14** [comment]
Add rt.jar (java stdlib) to your path. This could actually also fix the problem above with `allatori.string.StringEncryptionTransformer`

**Comment by DefSmile** [comment]
> Add rt.jar (java stdlib) to your path. This could actually also fix the problem above with `allatori.string.StringEncryptionTransformer`

Ok I added rt.jar to my jdk and now I get this with LightFlowObfuscationTransformer:
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.javavm.utils.TypeHelper.getTypeByInternalName(TypeHelper.java:99)
	at com.javadeobfuscator.javavm.utils.TypeHelper.parseType(TypeHelper.java:67)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.getSuperclass(JavaClass.java:323)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:92)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:217)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:199)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:40)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by Janmm14** [comment]
You need to add rt.jar to the path configuration of the deobfuscator. You do not need to add rt.jar to your jdk.

**Comment by DefSmile** [comment]
> You need to add rt.jar to the path configuration of the deobfuscator. You do not need to add rt.jar to your jdk.

Ok I did that now, but still get the Null Pointer.
https://i.imgur.com/i0jokmB.png

**Comment by ThisTestUser** [comment]
The issue came from allatori.string.StringEncryptionTransformer. Just use allatori.StringEncryptionTransformer and allatori.FlowObfuscationTransformer.
