### ISSUE TITLE
Could not find invoker

### ISSUE THREAD

**Issue by Matix-Media** [java-deobfuscator/deobfuscator#699]
So, I was looking on the internet and found this deobfuscator. I thought it looked really promising, so I tried it.

I've already run the detector successfully and it detected "com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer".
If've tried running it using a config but the program tells me to create an error on GitHub to paste the error here.

So here is the error:
```
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/Object get(Ljava/lang/Object;)Ljava/lang/Object; @ net/bote/bw/commands/CMD_stats$CMD_stats L(Ljava/lang/Object;SBI)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1250)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1396)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$0(HideAccessObfuscationTransformer.java:121)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:117)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
        at com.javadeobfuscator.deobfuscator.D

eobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

**Comment by Janmm14** [comment]
Add java standard library jar rt.jar to the path configuration of the deobfuscator.

**Comment by Matix-Media** [comment]
I should put it in the directory of the deobfuscator?

**Comment by Matix-Media** [comment]
My libs folder is in my paths and I also put it into the directory containing the deobfuscator.jar but still the same error

**Comment by Janmm14** [comment]
This describes how to add a jar into the deobfuscators path config: https://github.com/java-deobfuscator/deobfuscator/wiki/Getting-Started

**Comment by Matix-Media** [comment]
I use the deobfusecator-ui now, added the path to the rt.jar file, but the same error still appears.

**Comment by Janmm14** [comment]
Then you maybe need to add spigot jar as well to the path.
(adding path is also possible without the ui, described on that page just a little further down)

**Comment by Matix-Media** [comment]
Yeah I know that I can do the same using the cli.

But even after I added the spigot.jar. I get the same error

**Comment by Janmm14** [comment]
what you could try is to run other stringer transformers, try only one at a time and if it works, inspect the result and then try other stringer transformers until obfuscation is gone

**Comment by Matix-Media** [comment]
Ok thank you 👍

**Comment by ThisTestUser** [comment]
You should use stringer.StringEncryptionTransformer before HideAccessTransformer, always.
