### ISSUE TITLE
deobfuscation fails on obfuscators that blank name class files, obfuscator: paramorphism

### ISSUE THREAD

**Issue by stovan12** [java-deobfuscator/deobfuscator#704]
`C:\Users\zarzz\Desktop\deobf>java -jar deobfuscator.jar --config detect.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse  v/ d/ du/ q/ dg/ l.class (is it a class file?)
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:259)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:256)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:330)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
[main] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse  c/ d/ r/ ny/ m/ l.class (is it a class file?)
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:259)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:256)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:330)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
[main] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse  l/ hh/ d/ nt/ s/ l.class (is it a class file?)
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:259)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:256)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:246)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:330)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleSourceFileAttribute: Some obfuscators don't remove the SourceFile attribute by default. This information can be recovered, and is very useful
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found possible SourceFile attribute on com/google/gson/LongSerializationPolicy:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - (Choose one transformer. If there are multiple, it's recommended to try the transformer listed first)
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer`

**Comment by Janmm14** [comment]
Ignore the errors and use the paramorphism transformer

**Comment by stovan12** [comment]
@Janmm14 the paramorphism transformer doesn't seem to be registered as a usable transformer

**Comment by ItzSomebody** [comment]
The exceptions being thrown here are expected. Paramorphism adds encrypted classes into the archive with a `.class` extension so ASM will naturally throw an exception when attempting to parse a non-parseable class.

> @Janmm14 the paramorphism transformer doesn't seem to be registered as a usable transformer

This on the other hand is not. Could you provide further details?

**Comment by ItzSomebody** [comment]
Since there hasn't been a response for almost two months, I'll go ahead and close this.  @stovan12 feel free to comment.
