### ISSUE TITLE
deobf failed

### ISSUE THREAD

**Issue by Not-Hax** [java-deobfuscator/deobfuscator#709]
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/security/MessageDigest$Delegate$CloneableDelegate digest([B)[B @ org/newdawn/slick/tests/DistanceFieldTest lIIIIIIIIIll(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1250)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1396)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer.transform(SuperblaubeereTransformer.java:416)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

I tried deobf with these following Transformers :
```
speacial.SuperblaubeereTransformer
stringer.invokeddynamicTransformer
normalizer.SourceFileClassNormalizer
speacial.FlowObfuscationTransformer
speacial.UselessArithmeticTransformer
speacial.BisBardTransformer
speacial.InvalidClassRemover
speacial.UselessArithmeticTransformer
speacial.RadonTransformer
general.removers.LocalVariableRemover
general.removers.LinenumberRemover
```

**Comment by Not-Hax** [comment]
i added rt to path :/

**Comment by ThisTestUser** [comment]
Add javax.jar to path also.

**Comment by Not-Hax** [comment]
> Add javax.jar to path also.

where is javax.jar :/

**Comment by ItzSomebody** [comment]
I think that `jce.jar` might be more relevant to this one, but I honestly don't remember the way the Java API is split across the library jars. 

> > Add javax.jar to path also.
> 
> where is javax.jar :/

Since you're on Java 9+, the `java.base` jmod should contain those classes, if I recall correctly.

**Comment by Not-Hax** [comment]
> I think that `jce.jar` might be more relevant to this one, but I honestly don't remember the way the Java API is split across the library jars.
> 
> > > Add javax.jar to path also.
> > 
> > 
> > where is javax.jar :/
> 
> Since you're on Java 9+, the `java.base` jmod should contain those classes, if I recall correctly.

im on java 8

**Comment by ItzSomebody** [comment]
Based on the stacktrace posted, that does not seem to be the case. The `java.base` stuff is part of the modules system introduced in Java 9.

Nonetheless, `jce.jar` is what Java 8 users would use.

**Comment by ItzSomebody** [comment]
Since this hasn't been replied to in awhile, I go ahead and close this.  Feel free to comment if this is still an issue.
