### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fatrolls** [java-deobfuscator/deobfuscator#711]
I got this from the `general.peephole.PeepholeOptimizer` transformer.

Ran it against this file: http://www.mediafire.com/file/n7d38rcj6dmcuu3/encryptedFolder.zip/file

```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
org.objectweb.asm.tree.analysis.AnalyzerException: Execution can fall off the end of the code
	at org.objectweb.asm.tree.analysis.Analyzer.findSubroutine(Analyzer.java:322)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:138)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:35)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer.transform(PeepholeOptimizer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Janmm14** [comment]
the gui does indeed run this deobfuscator, so you got it in the right place.

the minecraft transformers are meant for obfuscated complete minecraft client jars and not for just minecraft-related jars.

**Comment by fatrolls** [comment]
Thanks, hope these errors will help the product out in some way.. some of those errors are probably because I used the transformers in the wrong orders I learned about that later in the commonerrors folder. But yeah transformers should probably give u back 0 found instead of crashing and not allowing other transformers to run.

**Comment by ItzSomebody** [comment]
Is this still an issue?  I or someone else could try looking into this if this is still a persisting issue.
