### ISSUE TITLE
Allatori Deobfuscation Error

### ISSUE THREAD

**Issue by H0bbyD3v** [java-deobfuscator/deobfuscator#715]
I tried to deobfuscate [this](https://workupload.com/file/uvVWZAbBpXH)
I used the gui and the detect method and got this error:
`Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ThreadDeath
	at java.base/java.lang.Thread.stop(Thread.java:938)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$2.windowClosing(SwingWindow.java:892)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2068)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2027)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[Thread-8] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-8] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-8] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
`

I am pretty sure it was obfuscated with allatori. thanks for your help if you need any more informations please say so i can upload it.

**Comment by Janmm14** [comment]
If you are sure its obfuscated with allatori, dont run detect on it, but try the different allatori transformers.

Also look here: https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Allatori.md

**Comment by H0bbyD3v** [comment]
I tried to use them, it says all ok but the file isn't deobfuscated at the end

**Comment by fikawka** [comment]
run the deobfuscator again and see if something changed

**Comment by ItzSomebody** [comment]
This has some Allatori demo in it along with what I think is radon 2.  Try using the transformer for radon 2 first then the Allatori string transformers.
