### ISSUE TITLE
SourceFileClassNormalizer | java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by TemaFlux** [java-deobfuscator/deobfuscator#716]
===============asd.yml===============
input: output1.jar
output: output2.jar
transformers:
  - normalizer.SourceFileClassNormalizer:
path:
  - "C:/Programs/Java/jre1.8.0_281/lib/rt.jar"
===============asd.yml===============

===============CONSOLE===============
PS C:\Users\TemaFlux\Downloads> java -jar deobfuscator.jar --config="asd.yml"
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 202 source filenames

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException
        at org.objectweb.asm.Type.getTypeInternal(Type.java:443)
        at org.objectweb.asm.Type.getType(Type.java:177)
        at org.objectweb.asm.commons.Remapper.mapDesc(Remapper.java:55)
        at org.objectweb.asm.commons.ClassRemapper.visitAnnotation(ClassRemapper.java:122)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(HashMap.java:981)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
===============CONSOLE===============

**Comment by ItzSomebody** [comment]
Seems to be related to #710 which also crashes in the exact same manner.  Can you verify the existence of any strange annotations?

**Comment by ThisTestUser** [comment]
The new remover transformers should remove any illegal annotations in the file. However, remember that SourceFileClassNormalizer is only for obfuscators that don't remove the source file names, which probably isn't the case here.
