### ISSUE TITLE
deobf failed

### ISSUE THREAD

**Issue by Not-Hax** [java-deobfuscator/deobfuscator#717]
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.javavm.exceptions.ExecutionException: Cannot set already non-null thread
	at com.javadeobfuscator.javavm.oops.ThreadOop.setThread(ThreadOop.java:67)
	at com.javadeobfuscator.javavm.VirtualMachine.createMainThread(VirtualMachine.java:628)
	at com.javadeobfuscator.javavm.VirtualMachine.fullInitialization(VirtualMachine.java:135)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:168)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

```
```
The Transformers I used :

special.SuperblaubeereTransformer
stringer.InvokedynamicTransformer
normalizer.SourceFileClassNormalizer
special.FlowObfuscationTransformer
special.UselessArithmeticTransformer
special.BisGuardTransformer
special.InvalidClassRemover
special.UselessArithmeticTransformer
special.RadonTransformer
general.removers.LocalVariableRemover
general.removers.LineNumberRemover
zelix.FlowObfuscationTransformer
zelix.ReflectionObfuscationTransformer
zelix.StringEncryptionTransformer
zelix.string.SimpleStringEncryptionTransformer
zelix.string.EnhancedStringEncryptionTransformer
```

**Comment by Not-Hax** [comment]
The whole thing
[Console.txt](https://github.com/java-deobfuscator/deobfuscator/files/6129202/Console.txt)

**Comment by Janmm14** [comment]
@Not-Hax

_**First of all: You ignored laws and #653 and distributed a buyable, copyrighted resource without permission. Remove the link to the downlad and the download itself or @ItzSomebody will do it.**_

Some general tips:
- The order of transformers matter.
- You're throwing far too many transformers at it. Many transformers in your log state that they did not change anything. The first step should always be to run detect on the jar and work from there.
- Do not use `normalizer.SourceFileClassNormalizer`. In general, normalizers should always be the last transformers.
- Look at the [Common errors](https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/) help. Try running without `zelix.string.*` transformers.

**Comment by ItzSomebody** [comment]
All I see here is some ZKM 8.0.8 (flow obfuscated enhanced string encryption, I think) and Stringer stuff.  I would be very surprised if the deobfuscator *didn't* crash with all of those transformers you added to the execution.  @Janmm14's suggestions are good and, yes, please don't upload copyrighted resources.

**Comment by Not-Hax** [comment]
> All I see here is some ZKM 8.0.8 (flow obfuscated enhanced string encryption, I think) and Stringer stuff. I would be very surprised if the deobfuscator _didn't_ crash with all of those transformers you added to the execution. @Janmm14's suggestions are good and, yes, please don't upload copyrighted resources.

ok so i am using these transformers to try to deobf again
```
normalizer.SourceFileClassNormalizer
stringer.StringEncryptionTransformer
stringer.v3.CleanupTransformer
stringer.HideAccessObfuscationTransformer
zelix.StringEncryptionTransformer
zelix.string.EnhancedStringEncryptionTransformer
```
i added rt.jar to path, and these shows up
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Could not find bootstrap
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$4(HideAccessObfuscationTransformer.java:137)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$2(HideAccessObfuscationTransformer.java:127)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:126)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Janmm14** [comment]
@Not-Hax you ignored number3 of tbe general tips i wrote

**Comment by Not-Hax** [comment]
> @Not-Hax you ignored number 3 of the general tips i wrote.
> 
> Also you should not use `stringer.v3.CleanupTransformer` before other stringer transformers. Don't use it or put it near the end.
this time i used these transformers 
```
stringer.v3.CleanupTransformer
stringer.StringEncryptionTransformer
stringer.HideAccessObfuscationTransformer
zelix.StringEncryptionTransformer
zelix.string.EnhancedStringEncryptionTransformer
normalizer.SourceFileClassNormalizer
```
and here is the console
```
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.v3.CleanupTransformer
[Thread-4] INFO com.javadeobfuscator.deobfuscator.transformers.stringer.v3.CleanupTransformer - Removed 8 invokedynamic decryption methods
[Thread-4] INFO com.javadeobfuscator.deobfuscator.transformers.stringer.v3.CleanupTransformer - Removed 8 string encryption classes
[Thread-4] INFO com.javadeobfuscator.deobfuscator.transformers.stringer.v3.CleanupTransformer - Removed 3 hide access decryption classes
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 0 encrypted strings
[Stringer] [StringEncryptionTransformer] Done
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer
[Stringer] [HideAccessTransformer] Starting
[Stringer] [HideAccessTransformer] Found 0 decryptors





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Could not find bootstrap
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$4(HideAccessObfuscationTransformer.java:137)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$2(HideAccessObfuscationTransformer.java:127)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:126)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ItzSomebody** [comment]
Reread Janmm14's last sentence. The cleanup transformer removes invokedynamic bookstraps/resolver classes/decryption classes so when you run other transformers which attempt to remove said obfuscation methods/classes, the deobfuscator can't resolve them and that exception is thrown. In summary, that exception is expected.

**Comment by ItzSomebody** [comment]
Argh, I hit the close button again. My bad.
