### ISSUE TITLE
javafx/util/Callback

### ISSUE THREAD

**Issue by leandr1999** [java-deobfuscator/deobfuscator#72]
How to fix that?

Command:
java -Xmx1024m -jar deobfuscator.jar -input app_original.jar -output app_new.jar -transformer general.SyntheticBridgeTransformer -path "C:\Program Files\Java\jre1.8.0_111\lib\rt.jar" -path "D:\lib\controlsfx.jar" -path ""D:\lib\scala.jar"

Warning! Output file already exists

Reading complete. Loading hierachy

Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: **javafx/util/Callback**
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:240)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by Janmm14** [comment]
`javafx/util/Callback` is not in your libraries. Maybe you need to add some more library jars form your jre.

**Comment by leandr1999** [comment]
I cant finde lib with JavaFx.util.Callback.
Can you help me it?
