### ISSUE TITLE
Deobfuscation Error

### ISSUE THREAD

**Issue by ArdaKurucim** [java-deobfuscator/deobfuscator#724]
```
java.lang.IndexOutOfBoundsException: Trying to set an inexistant local variable 0
        at org.objectweb.asm.tree.analysis.Frame.setLocal(Frame.java:178)
        at org.objectweb.asm.tree.analysis.Analyzer.computeInitialFrame(Analyzer.java:397)
        at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:162)
        at com.javadeobfuscator.deobfuscator.rules.allatori.RuleStringDecryptor.test(RuleStringDecryptor.java:48)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:336)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
My config file has:
```
input: launcher.jar
detect: true
```

**Comment by ArdaKurucim** [comment]
I have no idea which transformers should i use. I never coded java lol.

**Comment by ItzSomebody** [comment]
Reference: https://github.com/java-deobfuscator/deobfuscator/blob/0147c7d2f9565c019a0b36ac4981268e408228de/src/main/java/com/javadeobfuscator/deobfuscator/rules/allatori/RuleStringDecryptor.java#L45-L52

I have found asm's analyzers (which is what the rule uses to try to detect Allatori's string encryption) to not work well sometimes with certain flow obfuscation edge cases.  This is an issue where I would shift the blame more on asm, but perhaps this also motivates the idea of removing reliance on asm's analyzers.

Regarding what to use, check #653.  If it's something that cannot be posted publicly, then you can try emailing me at itzsomebody@protonmail.com.
