### ISSUE TITLE
invisAnno:desc & invisLocalVarAnno;desc ?

### ISSUE THREAD

**Issue by OpticFusion1** [java-deobfuscator/deobfuscator#725]
<invisAnno:desc = ??, values = []> 
<invisLocalVarAnno:desc = ??, values = []>
They're either all empty, or contain bytecode

When trying to detect it crashes with the following error, I'm not sure if it's because of these or what

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.rules.stringer.RuleStringDecryptorWithThread.test(RuleStringDecryptorWithThread.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:257)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
        
Edit:
They're invisible annotations or invisible local variable annotations

**Comment by ItzSomebody** [comment]
That is a very unusual place for an NPE to happen in the deobfuscator.  Assuming this corresponds to the current HEAD, then the NPE originates from the following: https://github.com/java-deobfuscator/deobfuscator/blob/0147c7d2f9565c019a0b36ac4981268e408228de/src/main/java/com/javadeobfuscator/deobfuscator/rules/stringer/RuleStringDecryptorWithThread.java#L36-L39

Does the NPE go away if you delete the annotations?

**Comment by OpticFusion1** [comment]
That is a strange thing, in this case they were either a fuck ton of new lines or method byte code. I'll have to see if i have a jar lying around still, I probably do though

**Comment by Janmm14** [comment]
I got a jar with those newline annotations and ran the latest deobfuscator release via the gui on it and did not got this error (and also no matching transformer, and that's correct)
