### ISSUE TITLE
StackOverflow while trying to deobfuscate allatori string encryption

### ISSUE THREAD

**Issue by MiniDigger** [java-deobfuscator/deobfuscator#73]
```
java -jar deobfuscator-1.0.0.jar -input Minetopia_Custom.jar -output Minetopia_Custom_Cracked.jar -transformer allatori.StringEncryptionTransformer -path "Z:\Programme\JDK 8u51\jre\lib\rt.jar" -path "Z:\Dev\spigot-test-server\craftbukkit-1.10.jar"
Warning! Output file already exists

Reading complete. Loading hierachy


Transforming

Deobfuscation failed. Please open a ticket on GitHub
java.lang.StackOverflowError
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:993)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
[...] 
       at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
        at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:267)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$null$1(StringEncryptionTransformer.java:55)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)
```

sample file can be grabbed from here https://www.spigotmc.org/resources/minetopia-custom-build.29794/update?update=121023
code looks like this
![http://i.minidigger.me/2016/12/javaw_27_21-51-23.png](http://i.minidigger.me/2016/12/javaw_27_21-51-23.png)

can't take a look at it currently so I though I would just drop that here.

**Comment by samczsun** [comment]
I'll take a look at this once https://github.com/java-deobfuscator/javavm is in a decent state

**Comment by Janmm14** [comment]
Try increasing your stack size with `-Xss128M`.

**Comment by MiniDigger** [comment]
ah thanks, that helped, should tried that myself.
so it wasn't an issue with the deobfuscator.

**Comment by samczsun** [comment]
No, it's definitely an issue with the deobfuscator. That code is terribly inefficient.

**Comment by samczsun** [comment]
Closing this even though I said I was going to work on it because the vm has spiraled out of control and is so backlogged you can't even see it. For the sake of getting stuff to work I'm just going to recommend increasing stack size to everyone in the forseeable future
