### ISSUE TITLE
TypeHelper.java:99 throws NullPointer

### ISSUE THREAD

**Issue by kxmpetentes** [java-deobfuscator/deobfuscator#732]
java.lang.NullPointerException
	at com.javadeobfuscator.javavm.utils.TypeHelper.getTypeByInternalName(TypeHelper.java:99)
	at com.javadeobfuscator.javavm.utils.TypeHelper.parseType(TypeHelper.java:67)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.getSuperclass(JavaClass.java:323)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:92)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:217)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:199)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:40)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
As a workaround, try allatori.StringEncryptionTransformer instead.

**Comment by kxmpetentes** [comment]
allatori.StringEncryptionTransformer throws the same exception

**Comment by Janmm14** [comment]
That is impossible.
