### ISSUE TITLE
Stringer StringEncryptionTransformer NPE

### ISSUE THREAD

**Issue by Bonista** [java-deobfuscator/deobfuscator#735]
I am trying to use the Stringer StringEncryptionTransformer but I am getting this error.

`[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 80 encrypted strings

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedFieldProvider.getField(MappedFieldProvider.java:37)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.getField(DelegatingProvider.java:71)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1091)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1300)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1396)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1396)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:78)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.decrypt(StringEncryptionTransformer.java:509)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:105)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
`
Unfortunately, I can not provide sample as it is copyrighted content.

**Comment by ItzSomebody** [comment]
You can try emailing me a copy of the file (itzsomebody@protonmail.com) if you wish.  This one is not very easy to work through without seeing the sample used.

For the record, have you gotten anywhere with this or is this still an issue?
