### ISSUE TITLE
Class cast exception for Zelix ReflectionObfuscationTransformer

### ISSUE THREAD

**Issue by Bonista** [java-deobfuscator/deobfuscator#736]
```[Thread-12] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-12] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-12] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-12] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-12] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
[Allatori] [StringEncryptionTransformer] Starting
[Allatori] [StringEncryptionTransformer] Decrypted 1006 encrypted strings
[Allatori] [StringEncryptionTransformer] Removed 22 decryption methods
[Allatori] [StringEncryptionTransformer] Done
[Thread-12] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer
[Zelix] [StringEncryptionTransformer] Starting
[Zelix] [StringEncryptionTransformer] Decrypted strings from 0 encrypted classes
[Zelix] [StringEncryptionTransformer] Decrypted 0 strings
[Zelix] [StringEncryptionTransformer] Done
[Thread-12] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
[Zelix] [ReflectionObfuscationTransformer] Starting
[Zelix] [ReflectionObfuscationTransformer] Finding reflection obfuscation
[Zelix] [ReflectionObfuscationTransformer] Found 151 reflection obfuscation instructions





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ClassCastException: org.objectweb.asm.tree.IincInsnNode cannot be cast to org.objectweb.asm.tree.LdcInsnNode
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:527)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:73)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
```

**Comment by ItzSomebody** [comment]
Do you have a JAR handy that you can post (provided it's allowed by #653)?
