### ISSUE TITLE
allatori.string.StringEncryptionTransformer

### ISSUE THREAD

**Issue by SlawPing** [java-deobfuscator/deobfuscator#739]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1523)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1488)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:718)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1016)
        at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:167)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by ItzSomebody** [comment]
Did you give the tips in #642 a try?

**Comment by ThisTestUser** [comment]
And it's probably a better idea to use allatori.StringEncryptionTransformer instead, as it is faster and less memory intensive.
