### ISSUE TITLE
DashOのStringDecryption

### ISSUE THREAD

**Issue by Ghost-Kokoro** [java-deobfuscator/deobfuscator#740]
java.lang.RuntimeException: unexpected different size of values SourceResult{values=[0, 15], exceptions=[]} SourceResult{values=[11], exceptions=[]}
	at com.javadeobfuscator.deobfuscator.asm.source.ConstantPropagatingSourceFinder.findSource(ConstantPropagatingSourceFinder.java:57)
	at com.javadeobfuscator.deobfuscator.asm.source.SourceFinder.findSource(SourceFinder.java:81)
	at com.javadeobfuscator.deobfuscator.transformers.dasho.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:88)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by ItzSomebody** [comment]
Do you have a JAR handy that you can post (provided it's allowed via #653)?

**Comment by Ghost-Sakura** [comment]
> Do you have a JAR handy that you can post (provided it's allowed via #653)?

No, the JAR is a Minecraft client which I want to crack, its not allowed to upload.

**Comment by ThisTestUser** [comment]
Judging from a previous issue (#754), it looks like using dasho.FakeExceptionTransformer and dasho.FlowObfuscationTransformer beforehand solves this. That fix worked for some large applications, so I'll assume it works here also (unless there's another obfuscator applied).
