### ISSUE TITLE
Failed serialize while using MethodAnalyzer.analyze

### ISSUE THREAD

**Issue by BackupAccou** [java-deobfuscator/deobfuscator#744]
`java.lang.NoSuchMethodError: com.google.gson.Gson.<init>(Lcom/google/gson/internal/Excluder;Lcom/google/gson/FieldNamingStrategy;Ljava/util/Map;ZZZZZZZLcom/google/gson/LongSerializationPolicy;Ljava/util/List;)V
	at com.google.gson.GsonBuilder.create(GsonBuilder.java:568)
	at com.javadeobfuscator.deobfuscator.analyzer.frame.Frame.<clinit>(Frame.java:166)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:716)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:281)`

Gson version using in the project : 2.6.2
Bytecode:
[https://pastebin.com/aB2RwRWs](https://pastebin.com/aB2RwRWs)

**Comment by BackupAccou** [comment]
Solved.I‘m on a dynamic injection environment.So Gson version incorrect.
