### ISSUE TITLE
Having trouble with BOZAR obfuscator

### ISSUE THREAD

**Issue by LazyCoder73** [java-deobfuscator/deobfuscator#748]
Hi, I'm trying to deobfuscate a file I am 99% sure has been obfuscated using this:

https://github.com/vimasig/Bozar

and am having some issues (not sure if my user error or lack of support for this obfuscator).

A standard decompilation attempt results in obfuscated variable names such as:

``` public ClientThread f;
    public static String[] llIlIll;
    public static Class[] llIllII;
    public static String[] lIIllIlI;
    public static String[] lIIllIll;
    public static int[] lIIlllII;
    public static long \u13e9;
```

and method names such as:
```
public void \u0152\u00eb\u00e7¶\u203a\u00c7¶\u201e\u00e8¹\u00fe\u0161¡°\u00e6\u00edª\u00c7\u00cd\u00e6(final ConfigButtonClicked lllIIIllIllIlIl) {
```

The obfuscation detect step indicated to try this transformer:
 com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer

Attempted that which seemed to have some success:

```[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 30 source filenames
```

Followed by this error

```Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.StackOverflowError
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapPackage(CustomRemapper.java:157)
```

Google drive link to the file I am trying to deobfuscate - https://drive.google.com/file/d/1DEDdfFkwq6awz80iTj4goRKAU7eyHjiO/view?usp=sharing

Any assistance would be greatly appreciated! Thank you

**Comment by gsquaredxc** [comment]
https://github.com/vimasig/Bozar/blob/master/src/main/java/com/vimasig/bozar/obfuscator/transformer/impl/CrasherTransformer.java may be helpful.

**Comment by ItzSomebody** [comment]
Interesting, this crashes Recaf as well (@Col-E, plz fix :pray:).  I'll trust in the meantime that this is compliant with #653 and check back on this as soon as possible.

**Comment by Janmm14** [comment]
SourceFileClassNormalizer will not be any help for this. Do NOT use it. I created #750 to suggest SourceFileClassNormalizer less often wrongly.

For the other crash stuff its enough to open the jar with 7zip and delete the BOZAR folder as well as NAUGHTY NAUGHTY.class

**Comment by Soxs** [comment]
I see you're trying to crack my stuff :D 

the solution is quite simple: try harder

**Comment by xxDark** [comment]
> 
> 
> Interesting, this crashes Recaf as well (@Col-E, plz fix 🙏). I'll trust in the meantime that this is compliant with #653 and check back on this as soon as possible.
![recaf](https://user-images.githubusercontent.com/19853368/117429175-72d7c880-af2f-11eb-8bda-118a62884e47.png)
Recaf is crashing due to an issue with JavaFX, remove crash entry and everything will open as expected

**Comment by Col-E** [comment]
Fixed in Recaf 2.19.6, I added directory truncating.

**Comment by Janmm14** [comment]
I took a look at the provided sample and it does not look like bozar only.

There is some obfuscation at work which creates a new class per virtual method call if its target is within the classes to be obfuscated. Well maybe that was also done manually.
