### ISSUE TITLE
allatori.RuleStringDecryptor fails with "IndexOutOfBoundsException: Trying to set an inexistant local variable 0"

### ISSUE THREAD

**Issue by umtcnyd** [java-deobfuscator/deobfuscator#753]
I was trying to detect the obfuscator of a jar file. My detect.yml file was like this:

```
input: files name.jar
detect: true
```
An ordinary detect.yml file. 
I did the "java -jar deobfuscator.jar --config detect.yml" command, but it threw up bunch of errors, and finally I got a message that told me that deobfuscation failed and I needed to open a ticket with the following error:

```
java.lang.IndexOutOfBoundsException: Trying to set an inexistant local variable 0
        at org.objectweb.asm.tree.analysis.Frame.setLocal(Frame.java:178)
        at org.objectweb.asm.tree.analysis.Analyzer.computeInitialFrame(Analyzer.java:397)
        at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:162)
        at com.javadeobfuscator.deobfuscator.rules.allatori.RuleStringDecryptor.test(RuleStringDecryptor.java:48)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:336)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

I did everything correct. No typos, no wrong usage, no nothing and I am pretty sure of that. Please reply back ASAP.

**Comment by Janmm14** [comment]
oopsie, I forcepushed this one a little too often
