### ISSUE TITLE
SrgToMCP couldn't read the mapping

### ISSUE THREAD

**Issue by Ghost-Kokoro** [java-deobfuscator/deobfuscator#758]
java.lang.RuntimeException: Unexpected srg mapping
	at com.javadeobfuscator.deobfuscator.transformers.minecraft.SrgToMCPTransformer.remap(SrgToMCPTransformer.java:156)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:410)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

//  I am using the srg obfuscation mapping from MCP9.18, to rename methods in a mod.
[Materials.zip](https://github.com/java-deobfuscator/deobfuscator/files/6477903/Materials.zip)

**Comment by ThisTestUser** [comment]
This issue should be fixed in the latest build.
