### ISSUE TITLE
SuperblaubeereTransformer couldn't work.

### ISSUE THREAD

**Issue by Ghost-Kokoro** [java-deobfuscator/deobfuscator#768]
java.lang.IllegalStateException
	at com.javadeobfuscator.deobfuscator.transformers.special..transform(.java:293)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:435)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:392)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**Comment by Ghost-Kokoro** [comment]
I cant upload a zip file due to github or my network, sorry.

**Comment by Janmm14** [comment]
As long as your file is compliant with #653 you could also uplaod it to mega.nz, google drive, dropbox, wetransfer etc. and link it here.

**Comment by Ghost-Kokoro** [comment]
https://drive.google.com/file/d/1W8EzNwxkmtTVro9IMpBqDWu9BPgR4mPK/view?usp=sharing

**Comment by Janmm14** [comment]
Unfortunaly google drive found a virus in that file (by scanning with virustotal) and therefore I am unable to download it.
Please put the file into a password-protected zip. The password should be "virus" or "malicious" or anything else as long as you write the password here along with the new link.

**Comment by Ghost-Kokoro** [comment]
> Unfortunaly google drive found a virus in that file (by scanning with virustotal) and therefore I am unable to download it.
> Please put the file into a password-protected zip. The password should be "virus" or "malicious" or anything else as long as you write the password here along with the new link.

https://drive.google.com/file/d/1fnA7ieVY6SXs6vOLN1BAnOTIbrMwIfBe/view?usp=sharing
Passwordは123です。

**Comment by Janmm14** [comment]
@Ghost-Kokoro The jar file you linked IS NOT compliant with 653, it contains code from mojang.
@ItzSomebody @ThisTestUser @fee1-dead

I think the provided jar file uses Caesium and not Superblaubeere obfuscator.
Since they are similar, the detection feature might detect Caesium as Superblaubeere.

**Comment by Ghost-Kokoro** [comment]
> @Ghost-Kokoro The jar file you linked IS NOT compliant with 653, it contains code from mojang.
> @ItzSomebody @ThisTestUser @fee1-dead
> 
> I think the provided jar file uses Caesium and not Superblaubeere obfuscator.
> Since they are similar, the detection feature might detect Caesium as Superblaubeere.
> 
> Currently this project is not able to deobfuscate Caesium obfuscator. While I have a caesium deobfuscator based on this project privately I have no intention of publishing it.

The jar's author told me he used SuperBlaubeere obfuscator,  but in anyway, thank you.

**Comment by Janmm14** [comment]
> The jar's author told me he used SuperBlaubeere obfuscator, but in anyway, thank you.

Could be that Superblaubeere transformer evolved itself. With those open source obfuscators there are so many similar things around

**Comment by ItzSomebody** [comment]
@Ghost-Kokoro:  Make sure to read #653.  I will go ahead and remove the links to that JAR archive.

Regarding the exception posted in the OP, it originates from the following: https://github.com/java-deobfuscator/deobfuscator/blob/ad200d33bc9697851c31dccf442c046b22f8d2c7/src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/SuperblaubeereTransformer.java#L293

To be honest, I am not entirely sure what's happening here (as I have not inspected the client myself yet), but I think the most likely thing that is happening here is that some processor was run on top of the number pooling.

**Comment by Janmm14** [comment]
Its more likely that an earlier step (number folding/redundant ifs) was not completely successful.

**Comment by Ghost-Kokoro** [comment]
> @Ghost-Kokoro: Make sure to read #653. I will go ahead and remove the links to that JAR archive.
> 
> Regarding the exception posted in the OP, it originates from the following:
> 
> https://github.com/java-deobfuscator/deobfuscator/blob/ad200d33bc9697851c31dccf442c046b22f8d2c7/src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/SuperblaubeereTransformer.java#L293
> 
> To be honest, I am not entirely sure what's happening here (as I have not inspected the client myself yet), but I think the most likely thing that is happening here is that some processor was run on top of the number pooling.

OK, I will get attention of it next time.
Thx.
