### ISSUE TITLE
java.lang.ClassCastException: com.javadeobfuscator.deobfuscator.config.TransformerConfig cannot be cast to com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer$Config

### ISSUE THREAD

**Issue by ZuVEnO** [java-deobfuscator/deobfuscator#769]
There's an error.

```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
[Allatori] [StringEncryptionTransformer] Starting
[Allatori] [StringEncryptionTransformer] Decrypted 716 encrypted strings





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ClassCastException: com.javadeobfuscator.deobfuscator.config.TransformerConfig cannot be cast to com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer$Config
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:181)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:392)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

**Comment by ItzSomebody** [comment]
Ah.  Looks like there's a missing `@TransformerConfig.ConfigOptions(configClass = StringEncryptionTransformer.Config.class)` at https://github.com/java-deobfuscator/deobfuscator/blob/48dcf48cdecab3e58dff14e3c8b62d31e19432ce/src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java#L52.  Oops.  Try adding that in, rebuild the deobfuscator, and see if everything works fine.

**Comment by Janmm14** [comment]
Yeah I noticed my mistake today as well as I did https://github.com/java-deobfuscator/deobfuscator-gui/pull/29

**Comment by ItzSomebody** [comment]
@ZuVEnO:  Issue should be fixed by the latest commit.
