### ISSUE TITLE
error while deobfuscating, cannot deobfuscate superblaubeere

### ISSUE THREAD

**Issue by HENRYMARTIN5** [java-deobfuscator/deobfuscator#776]
Every time I attempt to run a deobfuscation on a file, it throws this error:
```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer
[Special] [SuperblaubeereTransformer] Starting





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at java.base/java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:493)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1394)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer.transform(SuperblaubeereTransformer.java:392)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:455)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:412)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
Please help!

Edit: After running the same thing in a VM, it STILL throws an error.

**Comment by Janmm14** [comment]
It is not needed to run java-deobfuscator in a VM, the program itself makes sure that code of the input and its libs are not directly executed and only emulated safely.

---
It is likely that the obfuscated jar you are trying to deobfuscate was not using superblaubeere obfuscator.
If the detect feature showed you that it was, it might use a fork with some changes to the obfuscation algorithm.

**If the jar file you are trying to deobfuscate is not violating copyrights, see #653**,
feel free to upload it to github or another file sharing site so we can take a look at it. If the changes of obfuscation are small, it is likely that I will update the transformer to support this obfuscation. However if there are bigger changes to the obfuscation, I will personally not publish any changes to the deobfuscator or its transformers and at most give some general tips on what needs to be changed in the deobfuscator.

If you violate #653, the link will be deleted from your comment and I will not publish changes even if they are small.
(I also do not accept private messages with links to copryright-protected jars, I don't directly help in deobfuscation of those)

If the resource you are trying to deobfuscate is copyright-protected, my helping capabilities are limited.
In case you know about java bytecode asm and can figure out why the array its trying to access/write is `null` in the deobfuscator, I might be able to help in discussing potential needed changes to the deobfuscator.
As alternative you could look for another non-copyright-protected jar file obfuscated with the same obfuscator which also gives the same error and upload that sample here.

**Comment by HENRYMARTIN5** [comment]
@Janmm14 The jar i'm trying to deobfuscate is NOT copyrighted, so I'll upload it in a bit.

**Comment by Janmm14** [comment]
@HENRYMARTIN5 Your smaple cannot be decompiled. That forge mod shouldn't even run at all and error about missing classes.

**Comment by HENRYMARTIN5** [comment]
@Janmm14 Hmm... Alright, thanks for your help!
