### ISSUE TITLE
Issue writing to the output jar

### ISSUE THREAD

**Issue by Spotless403** [java-deobfuscator/deobfuscator#777]
When trying to deobfuscate a jar, (I cant upload for copyright reasons) everything seems to go fine until the program attempts to write to the output jar. Instead of writing a deobfuscated version of the file to the output, I get an exact copy. For reference I'm using the normalizer.SourceFileClassNormalizer transformer here.

**Comment by Janmm14** [comment]
The sourcefileclassnormalizer is not a real deobfuscator.
It is just an additional tool that aims to rename classes to the name provided in the SourceFile attribute of the class.
Is this what you want?

Are other transformers suggested as well by the detect function?
Can you show a screenshot of a Krakatau decompile if you have seen String obfuscation, number obfuscation or flow obfuscation?

**Comment by Spotless403** [comment]
Running the original jar through the detect function output that normalizer transformer, so thats what I used. Attempting to decompile with Krakatau throws a syntax error. `Traceback (most recent call last):
  File "C:\Users\spotless\Desktop\Krakatau\decompile.py", line 8, in <module>
    import Krakatau.ssa
  File "C:\Users\spotless\Desktop\Krakatau\Krakatau\ssa\__init__.py", line 1, in <module>
    from .graph import ssaFromVerified
  File "C:\Users\spotless\Desktop\Krakatau\Krakatau\ssa\graph.py", line 10, in <module>
    from . import blockmaker, constraints, objtypes, ssa_jumps, ssa_ops, subproc
  File "C:\Users\spotless\Desktop\Krakatau\Krakatau\ssa\blockmaker.py", line 7, in <module>
    from . import ssa_jumps, ssa_ops, subproc
  File "C:\Users\spotless\Desktop\Krakatau\Krakatau\ssa\ssa_jumps\__init__.py", line 3, in <module>
    from .onexception import OnException
  File "C:\Users\spotless\Desktop\Krakatau\Krakatau\ssa\ssa_jumps\onexception.py", line 2, in <module>
    from ..constraints import ObjectConstraint
  File "C:\Users\spotless\Desktop\Krakatau\Krakatau\ssa\constraints\__init__.py", line 3, in <module>
    from ... import floatutil
  File "C:\Users\spotless\Desktop\Krakatau\Krakatau\floatutil.py", line 16
    sortkey = lambda (s,(m,e)):(s,s*e,s*m)
                     ^
SyntaxError: invalid syntax`

**Comment by Janmm14** [comment]
If the detect funcrion only shows that option, tge obfuscation is one of these:

- only name obfuscstion from proguard, mostly not reversible
- onfuscation which does not have a detector yet, but a transformer
- obfuscation which is completely unsupported by this deobfuscstor so far

**Comment by Spotless403** [comment]
Heres a snippet of one of the class files. They all look like this. A single string and nothing else. Im clearly not very familiar with this, or I would probably better understand what was used to obfuscate it.

![image](https://user-images.githubusercontent.com/82139103/122621723-40031300-d04b-11eb-8092-7d9335f71249.png)

**Comment by Janmm14** [comment]
Either fake classes or class encryption used and one of the classes is a decrypting class loader.

**Comment by Spotless403** [comment]
Is there a methodology you would recommend to reverse this?

**Comment by Janmm14** [comment]
What I would do is to find the entry point and look for class loader usage after checking for folder classes as descibed above.

If its class loader usage, I'd copy the decryprion routine and let it run on jar entries.

**Comment by Spotless403** [comment]
Awesome. Thanks for your help. I will attempt the first method and let you know how it goes.

**Comment by Spotless403** [comment]
When I selected Paramorphism and zelix FlowObfuscation as transformer, it just got stuck on writing and ended up pasting the input into the output. I ran detect regardless and found the same thing as before.  It recommended the normalizer.

**Comment by Janmm14** [comment]
Then its probably not folder classes (do you see folders with .class at the end?) and its the second option.

**Comment by Spotless403** [comment]
There are no folders with the class extension. all of the class files that you would expect to have unique names and code however, are named something similar to "18VG0iZe%" and contain only a single class with a long string of unreadable text.

**Comment by ItzSomebody** [comment]
@Spotless403:  Did you get anywhere with this?

**Comment by Spotless403** [comment]
Not really, I was a little confused. I think the jar is using class encryption, but Im not sure what to do about it.

**Comment by smallshen** [comment]
@Spotless403 this looks like Rocket DRM, which is abyss client I guess.
