### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported class file major version 26472

### ISSUE THREAD

**Issue by huzpsb** [java-deobfuscator/deobfuscator#781]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException: Unsupported class file major version 26472
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:127)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:158)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:372)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$16(SwingWindow.java:1014)
	at java.lang.Thread.run(Unknown Source)

[plugin.zip](https://github.com/java-deobfuscator/deobfuscator/files/6723328/plugin.zip)

**Comment by ItzSomebody** [comment]
```
>>> hex(26472)
'0x6768'
```
You're probably looking at either an encrypted class or some random zip entry filled with nonsensical bytes located somewhere in the libraries you are loading (or some other fluke that does not really come to my mind at the moment -- perhaps someone else can weigh in?).  I'd suggest trying to find the offending library via elimination.

**Comment by Janmm14** [comment]
If you use newest deobfuscator jar, it should not fail and telll you what exactly it couldn't read

**Comment by huzpsb** [comment]
thanks,it worked!
