### ISSUE TITLE
Deobfuscation failing

### ISSUE THREAD

**Issue by NebulaBC** [java-deobfuscator/deobfuscator#783]
```
error:
java.lang.NullPointerException
        at com.javadeobfuscator.javavm.mirrors.JavaField.getOop(JavaField.java:105)
        at com.javadeobfuscator.javavm.nativeimpls.java_lang_Class.lambda$registerNatives$21(java_lang_Class.java:349)
        at com.javadeobfuscator.javavm.hooks.HookGenerator.lambda$generateUnknownHandlingHook$2(HookGenerator.java:84)
        at com.javadeobfuscator.javavm.hooks.HookedMethod.execute(HookedMethod.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1191)
        at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1111)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1044)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1025)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:131)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:455)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:412)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
        Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
                at java.lang.Class.privateGetDeclaredFields(Class.java)
                at java.lang.Class.getDeclaredFields(Class.java:1916)
```

I have tried moving the two obfuscators that detect.yml came up with around in my config, but I get this error each time. I know that I am using java 1.8.0

**Comment by Janmm14** [comment]
Did you try only one of the two transformers?

**Comment by ThisTestUser** [comment]
Use zelix.StringEncryptionTransformer instead.
