### ISSUE TITLE
java.lang.NullPointerException - SuperblaubeereTransformer

### ISSUE THREAD

**Issue by GoatMighty** [java-deobfuscator/deobfuscator#786]
Error:

`java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer.transform(SuperblaubeereTransformer.java:291)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:459)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:416)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`
        
Transformers:
          `com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer`

**Comment by Janmm14** [comment]
Maybe not obfuscated with Superblaubeere,
maybe some unsupported variant of superblaubeere

**Comment by GoatMighty** [comment]
It's obfuscated with superblaubeere :D

**Comment by GoatMighty** [comment]
Can you deobfuscate for me? so it becomes readable pliz?

**Comment by GoatMighty** [comment]
Never mind, its because of jar file :(
