### ISSUE TITLE
I need help... 

### ISSUE THREAD

**Issue by CakeProgress** [java-deobfuscator/deobfuscator#789]
I tried 10 times to remove obfuscation from this jar, but I couldn't, could someone help me?

https://drive.google.com/file/d/13pdY2njN--Pqg2Lgkw35vVBVmUxGmLf-/view?usp=sharing

**Comment by NoMeansNowastaken** [comment]
i tried got this issue:
com.javadeobfuscator.javavm.exceptions.VMException: java.lang.Throwable
	at com.javadeobfuscator.javavm.VirtualMachine.initialize(VirtualMachine.java:910)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:94)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1111)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1052)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.v3.HideAccessTransformer.transform(HideAccessTransformer.java:98)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:459)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:416)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$16(SwingWindow.java:1014)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Throwable
	at com.javadeobfuscator.javavm.exceptions.VMException.<init>(VMException.java:28)
	... 15 more

**Comment by Janmm14** [comment]
You need rt.jar in path and forge 1.6.4 dev environment jar (maybe a newer forge version can do it too for decompilation as forge 1.6.4 dev env doesnt setup itself anymore without problems)

**Comment by Janmm14** [comment]
You also need some mc libs like lwjgl in path.

Circumventing that error however still doesn't cause this jar to get deobfuscated correctly, for some hide access deobfuscations it seems like some number related stuff is failing, this could in theory be something detecting the deobfuscator. not really thrilled right now to dive deep into this.

**Comment by ThisTestUser** [comment]
Deobfuscating older Forge mods is annoying, so here it is: 
[HelperDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/6874288/HelperDeob.zip)
The problem with deobfuscating Forge mods for versions older than 1.13 is that you actually need the SRG version of the Forge JAR, which you can only get by setting up a dev workspace. After 1.13 though, all the JARs are available in the libraries folder if you've launched Forge at least once.
