### ISSUE TITLE
Superblaubeere27 transformer fails with IndexOutOfBounds

### ISSUE THREAD

**Issue by sqlongithub** [java-deobfuscator/deobfuscator#791]
Hello. I tried deobfuscating a jar, and using
```
input: Aurora.jar
detect: true
```
said that Superblaubeere's obfuscator was used, and when I tried to deobfsucate it with
```
input: Aurora.jar
output: output.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer
```
an ArrayIndexOutOfBoundsException occurred. 

Here is the full error log:
```
[Special] [SuperblaubeereTransformer] Starting

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer.transform(SuperblaubeereTransformer.java:345)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:455)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:412)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```

I have attached the jar file, where I have attempted to remove as many Mojang classes as possible.
[Aurora.zip](https://github.com/java-deobfuscator/deobfuscator/files/6776075/Aurora.zip)

**Comment by Janmm14** [comment]
I could not reproduce this bug with the jar file your provided.
SuperblaubeereTransformer worked flawlessly.
