### ISSUE TITLE
Error Detect Obsfucator 

### ISSUE THREAD

**Issue by WhitfieBad** [java-deobfuscator/deobfuscator#795]
i try detect obsfucator for launcher minecraft and cath Exeption

```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - RuleIllegalSignature: Some obfuscators will set the signature of a class/method/field to an illegal value. This may crash naive decompilers/disassemblers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    Found illegal class signature for ru/cristalix/launcher/OOOoo0OOO MOJA OBORONa BAZ0VII SHAVEL ISK0NN0G0 ZaLa
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Recommend transformers:
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - (Choose one transformer. If there are multiple, it's recommended to try the transformer listed first)
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator -    com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.StackOverflowError
        at java.base/java.util.HashMap.putVal(HashMap.java:626)
        at java.base/java.util.HashMap.put(HashMap.java:607)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:204)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)
        at com.javadeobfuscator.deobfuscator.analyzer.FlowAnalyzer.analyze0(FlowAnalyzer.java:216)

Launcher -> 
[CristalixLauncher-3.0.145.zip](https://github.com/java-deobfuscator/deobfuscator/files/6834754/CristalixLauncher-3.0.145.zip)
```
Who knows what kind of obsfukator, for the first time I encounter this obsfucator?

**Comment by Janmm14** [comment]
This particular error is fixable byincreasing the maximum stack size. for example with `-Xss32M`. Won't give you any more information though.

On first glance, obfuscation seems to be ZKM + sth + annoying obfuscation dictionary.

**Comment by ThisTestUser** [comment]
The transformers you should use are Radon and RadonV2. Additionally, you should use the AnnotationRemovers and IllegalSignatureRemover to prevent your decompilier from crashing.

**Comment by WhitfieBad** [comment]
> The transformers you should use are Radon and RadonV2 (download the latest version first). Additionally, you should use the AnnotationRemovers and IllegalSignatureRemover to prevent your decompilier from crashing.

ok i try this

**Comment by ItzSomebody** [comment]
@WhitfieBad:  Any update on this?
