### ISSUE TITLE
java heap space

### ISSUE THREAD

**Issue by E4zily** [java-deobfuscator/deobfuscator#796]
java.lang.OutOfMemoryError: Java heap space
        at org.objectweb.asm.tree.LabelNode.getLabel(LabelNode.java:61)
        at org.objectweb.asm.tree.JumpInsnNode.accept(JumpInsnNode.java:79)
        at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
        at org.objectweb.asm.commons.JSRInlinerAdapter.visitEnd(JSRInlinerAdapter.java:158)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:772)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:316)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:266)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:379)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:92)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

**Comment by Janmm14** [comment]
Please see #642

**Comment by ItzSomebody** [comment]
Closing due to lack of response.
