### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by Pizop** [java-deobfuscator/deobfuscator#797]
```
java.lang.NullPointerException: Cannot invoke "com.javadeobfuscator.deobfuscator.executor.values.JavaValue.copy()" because the return value of "java.util.List.get(int)" is null
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:449)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:769)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1067)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:98)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)

```

**Comment by ThisTestUser** [comment]
This usually means that there's another obfuscator applied after Zelix. Looking at the error, it might be Stringer.

**Comment by ItzSomebody** [comment]
@Pizop:  Any update on this?
