### ISSUE TITLE
Leak a Client

### ISSUE THREAD

**Issue by LavaMensch** [java-deobfuscator/deobfuscator#80]
Hey i am Leaking a Minecraft Hack Client named Necrum i deaktivated 2Killswitches, but at the last one i can't do that. Is it possible to find out where de Client locates?

Exception in thread "Client thread" java.lang.NullPointerException
	at 5301.4206(Unknown Source)
	at 1401.4516(Unknown Source)
	at 1401.7926(Unknown Source)
	at 6441.0138(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)

Thats are the errors i think a local File, wich was created if somebody want the good Obsucated Code write me.

**Comment by Janmm14** [comment]
No issue with the deobfuscator.

**Comment by Eyremba** [comment]
Send us/me the jar file.
