### ISSUE TITLE
Deobfuscation Failed, Superblaubeere

### ISSUE THREAD

**Issue by intexception** [java-deobfuscator/deobfuscator#800]
```
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - The specified output JAR already exists!
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer
[Special] [SuperblaubeereTransformer] Starting
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/String java/lang/Object getClass()Ljava/lang/Class; @ pl/installer/Installer I(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1248)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1394)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer.transform(SuperblaubeereTransformer.java:462)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/String java/lang/Object getClass()Ljava/lang/Class; @ IIIIi IIi(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1248)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1394)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer.transform(SuperblaubeereTransformer.java:462)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/String java/lang/Object getClass()Ljava/lang/Class; @ iIii Ii(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1248)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1394)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer.transform(SuperblaubeereTransformer.java:462)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/String java/lang/Object getClass()Ljava/lang/Class; @ IiIii Iii(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1248)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
        at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1394)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.special.SuperblaubeereTransformer.transform(SuperblaubeereTransformer.java:462)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
[Special] [SuperblaubeereTransformer] Removed 0 number obfuscation instructions
[Special] [SuperblaubeereTransformer] Inlined 0 numbers
[Special] [SuperblaubeereTransformer] Unpooled 0 strings
[Special] [SuperblaubeereTransformer] Inlined 0 if statements
[Special] [SuperblaubeereTransformer] Removed 0 invokedynamics
[Special] [SuperblaubeereTransformer] Errors occurred during decryption of 4 classes:
[Special] [SuperblaubeereTransformer]   - iIii
[Special] [SuperblaubeereTransformer]   - pl/installer/Installer
[Special] [SuperblaubeereTransformer]   - IiIii
[Special] [SuperblaubeereTransformer]   - IIIIi
[Special] [SuperblaubeereTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/io/IOException could not be found while writing IIIIi. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing iIii. Using COMPUTE_MAXS
```

It is using superblaubeere, because it detected it.

**Comment by Janmm14** [comment]
Please try to add `rt.jar` to the path.

**Comment by intexception** [comment]
Where can I find rt.jar?

**Comment by intexception** [comment]
And wdym "add it to the path"

**Comment by ItzSomebody** [comment]
> 
> 
> And wdym "add it to the path"

Read the wiki link Janmm sent, the answer is in there.

> 
> 
> Where can I find rt.jar?

Depends on your platform.  `where.exe` or `which` should be able to find your Java installation location from which you can locate `rt.jar` or `java.base`.
