### ISSUE TITLE
Deobfuscation Failed with ZKM

### ISSUE THREAD

**Issue by PCZ-1337** [java-deobfuscator/deobfuscator#809]
java.lang.ClassCastException: org.objectweb.asm.tree.InsnNode cannot be cast to org.objectweb.asm.tree.LdcInsnNode
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:527)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:73)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
        at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1003)
        at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
use zelix string transformer before reflection transformer, as written here: https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Zelix.md
