### ISSUE TITLE
Error occured while parsing the config file

### ISSUE THREAD

**Issue by Andrei-dot** [java-deobfuscator/deobfuscator#810]
Hi everyone, i'm sorry to ask, its may appear silly but i didn't found any answers at my interrogations, so, when i run my command 
`java -jar .\deobfuscator.java --config .\config.yml`, i just get this error in my console 

```
[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occurred while parsing the configuration file
com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning a simple key
 in 'reader', line 4, column 1:
    allatori.StringEncryptionTransformer
    ^
could not find expected ':'
 in 'reader', line 4, column 37:
    allatori.StringEncryptionTransformer
                                        ^

 at [Source: (File); line: 3, column: 13]
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:346)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:66)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
Caused by: while scanning a simple key
 in 'reader', line 4, column 1:
    allatori.StringEncryptionTransformer
    ^
could not find expected ':'
 in 'reader', line 4, column 37:
    allatori.StringEncryptionTransformer
                                        ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.removePossibleSimpleKey(ScannerImpl.java:514)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchStreamEnd(ScannerImpl.java:588)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:301)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:167)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:343)
```

and here is my config file ; 

```
input: input.jar
output: output.jar
transformers:
allatori.StringEncryptionTransformer
```

**Comment by Janmm14** [comment]
See here how there is a `-` and spaces before each transformer in the sample on the bottom: https://github.com/java-deobfuscator/deobfuscator/wiki/Getting-Started

**Comment by ItzSomebody** [comment]
Closing as this is not an issue with the deobfuscator itself.
