### ISSUE TITLE
BUG deobfuscation detection 

### ISSUE THREAD

**Issue by Natixe** [java-deobfuscator/deobfuscator#813]
When I run the deobfuscation detection this error occurs : 

[main] ERROR com.javadeobfuscator.deobfuscator.DeobfuscatorMain - An error occurred while parsing the configuration file
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "entrée" (class com.javadeobfuscator.deobfuscator.config.Configuration), not marked as ignorable (13 known properties: "output", "detect", "path", "smartRedo", "input", "deleteUselessClasses", "ignoredClasses", "paramorphismV2", "libraries", "transformers", "paramorphism", "debugRulesAnalyzer", "verify"])
 at [Source: (File); line: 1, column: 26] (through reference chain: com.javadeobfuscator.deobfuscator.config.Configuration["entrée"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1151)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:66)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
        
        Any ideas?

**Comment by Janmm14** [comment]
The config.yml file you provided to the program is invalid.

**Comment by ItzSomebody** [comment]
This is not an issue as far as I can see, so I'll be closing this.

@Natixe:  I would recommend taking a look at the [wiki](https://github.com/java-deobfuscator/deobfuscator/wiki) for this project.
