### ISSUE TITLE
Bug with Zelix reflection?

### ISSUE THREAD

**Issue by huzpsb** [java-deobfuscator/deobfuscator#815]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ClassCastException: org.objectweb.asm.tree.LabelNode cannot be cast to org.objectweb.asm.tree.LdcInsnNode
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:527)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:73)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:459)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:416)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$16(SwingWindow.java:1014)
	at java.lang.Thread.run(Unknown Source)

[TritiumNetease.zip](https://github.com/java-deobfuscator/deobfuscator/files/7070333/TritiumNetease.zip)

**Comment by Janmm14** [comment]
Please see https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Zelix.md

**Comment by huzpsb** [comment]
But I tried literally all the possible sequence of all these transformers and they are not working as expected :(

**Comment by Janmm14** [comment]
Well iirc this specific error happens when you did not use zelix StringEncryption before

**Comment by huzpsb** [comment]
Awa,this file is not dmca-protected,as its author uploaded it on (https://gitee.com/LEF-ganga/Tritium)

the detect told me that i'd use string first,but after that I can't use ctrl-flow or reflect properly,while the detect give me a null output :(

(And isn't this a bug that it doesn't work with zkm?

**Comment by Janmm14** [comment]
The detect feature tells me
`RuleMethodParameterChangeStringEncryption: Zelix Klassmaster has several modes of string encryption. This mode is currently not supported.`
This means that this tool cannot deobfuscate that jar file.

**Comment by huzpsb** [comment]
: (
