### ISSUE TITLE
Errors with stringer Reflection transformer

### ISSUE THREAD

**Issue by caledot** [java-deobfuscator/deobfuscator#82]
I'm trying to reverse some classes in a project. Decompiling some of those classes I find some "strange" strings passed as parameter in a method call eg:
`this.af.add(JSON.endsWith((String)"Rgqr`t", (int)(94 + -61)).toLowerCase());` 
or
`this.af.add(JSON.endsWith((String)"\b##!(\t*?9+=", (int)(37 * 33)).toLowerCase());`

This made me to think that in some way the code is obfuscated so i tried to de-obfuscate using JDO.
As i cannot understant what kind of obfuscatin technique was used i tried to pass the .jar to all the deobfuscator using a command like:
`java -jar $pathToDeobfuscator -input $jarsToDeobuscate -output $outFileName -transformer $tranformersString[$i] '-path' "C:\Program Files (x86)\path\to\java\libs\and\input.jar\dependencies\"`

These are my outputs:
ALLATORI:
```
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
```
I suppose that Allatori wasn't used

DASHO gave no output

STRINGER:
`Transforming

[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 0 encrypted strings
[Stringer] [StringEncryptionTransformer] Done`

`Transforming

[Stringer] [InvokedynamicTransformer] Starting
[Stringer] [InvokedynamicTransformer] Finding invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Found 0 invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Done`

`
[Stringer] [ReflectionObfuscationTransformer] Starting
[Stringer] [ReflectionObfuscationTransformer] Found 5 reflection obfuscation calls
Deobfuscation failed. Please open a ticket on GitHub
com.javadeobfuscator.deobfuscator.executor.exceptions.FallingOffCodeException:  @ org/apache/commons/lang/ArrayUtils <clinit>()V
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:310)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$null$10(ReflectionObfuscationTransformer.java:186)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.lambda$decrypt$11(ReflectionObfuscationTransformer.java:118)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.decrypt(ReflectionObfuscationTransformer.java:117)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:67)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)`

The output .jar didn't contain any .class file

ZELIX
`Transforming

Rearranged 45034 goto blocks
Removed 2356 continous gotos
Removed 0 unconditional switches
Error while removing dead code from

ava : java.lang.NullPointerException
In C:\Users\_xxxx_\Desktop\massiveDeobfuscation.ps1:21 car:5
+     java -jar $pathToDeobfuscator -input $jarsToDeobuscate -output $o ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (java.lang.NullPointerException:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:403)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1001)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.execute(MethodAnalyzer.java:1015)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:267)
	at com.javadeobfuscator.deobfuscator.analyzer.MethodAnalyzer.analyze(MethodAnalyzer.java:221)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$null$2(DeadCodeRemover.java:42)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.lambda$transform$3(DeadCodeRemover.java:40)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:39)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.PeepholeOptimizer.transform(PeepholeOptimizer.java:45)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:155)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)`

or errors like:

`Error while fully initializing _className`_
`com.javadeobfuscator.deobfuscator.executor.exceptions.ExecutionException: Unknown value type JavaTop @ com/xxx/xxx/media/mpeg2/MPEG2Utils <clinit>()V
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.value(MethodExecutor.java:200)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:977)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:80)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$11(StringEncryptionTransformer.java:250)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:198)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:170)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)`

`Error: com/something/classNAME failed verification`

Any ideas why did i get those errors?

How can i know what kind of obfuscator was used on the .jars?

**Comment by Eyremba** [comment]
> How can i know what kind of obfuscator was used on the .jars?

By your experience and stupid obfuscators. Kiddys use Allatori in the demo version, so you just see it in the bytecode because of the ugly "xALLATORIxDEMO" strings. Full versions of obfuscators (Like Zelix, Stringer, Allatori Full Version) etc. can only be differed by experience. You just have to know how their "style" is.

**Comment by caledot** [comment]
Is there a way to study their style?

**Comment by Eyremba** [comment]
> Is there a way to study their style?

You have to do this by your own by searching obfuscated jars on the internet.

**Comment by Janmm14** [comment]
ZKM inserts an unused entry into the constant pool of every class it obfuscates like `ZKM8.0.1` for example. Also it is known to insert public static int/boolean fields which are randomly used inside methods to create additional ifs to make decompiler output a big mess or even crash a deompiler like fernflower.
Allatori is known to use stack trace information to decrypt strings.
Stringer is the only big obfuscator I've seen which uses invokedynamic instructions to hide method calls.

**Comment by caledot** [comment]
The code i'm studying contains strings like this "\b##!(\t*?9+=" often passed to a base64.concat method or json.endswith method. Furthermore the code contains various goto -> label instructions. These things brought me thinking that an obfuscation like zkm o stringer was used. But as I use the zkm o stringer deobfuscator i receive an error. I couldn't see any constant like ZKMsomething so is it possibile that a stringer was used? Or maybe a combination of both?

**Comment by Janmm14** [comment]
@caledot The obfuscation you describe causes me to not help you. Don't try to deobfuscate premium plugins with this if authors know about this.

**Comment by samczsun** [comment]
Please open a new issue if this problem still exists.
