### ISSUE TITLE
Deobfuscation Failed [ZELIX]

### ISSUE THREAD

**Issue by OmenDoesStuff** [java-deobfuscator/deobfuscator#821]
Error:
```Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at java.lang.reflect.Array.get(Native Method)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.executeArrayLoad(MethodExecutor.java:98)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:505)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:785)
        at java.util.HashMap$Values.forEach(HashMap.java:981)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:114)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)```

My config:
```input: remixobfuscated.jar
output: remixdeobfuscated.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.smoke.NumberObfuscationTransformer
```
File being deobfuscated: old remix client 1.6.3 with Zelix obfuscation

**Comment by ItzSomebody** [comment]
Take a look at #653 before proceeding any further.  Providing a sample JAR will help (provided it's not going to get this DMCA'd, obviously).

What happens if you remove `com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer` from the list of transformers?

**Comment by OmenDoesStuff** [comment]
If I remember it either runs out or memory of fails, the only one that doesn't is the number transformer
