### ISSUE TITLE
deobfuscation failed

### ISSUE THREAD

**Issue by noom1337** [java-deobfuscator/deobfuscator#827]
java.lang.RuntimeException: Unexpected analyzer exception
	at com.javadeobfuscator.deobfuscator.transformers.special.BinscureTransformer.transform(BinscureTransformer.java:354)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 18: Cannot pop operand off an empty stack.
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:296)
	at com.javadeobfuscator.deobfuscator.transformers.special.BinscureTransformer.transform(BinscureTransformer.java:351)
	... 9 more
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
	at org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:258)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:396)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:188)
	... 10 more

jar: https://github.com/EclipseAFK/Data/releases/download/030421/Hydra.rar

**Comment by ThisTestUser** [comment]
The latest update should fix this issue.
