### ISSUE TITLE
Error with binscure transformer

### ISSUE THREAD

**Issue by josesilveiraa** [java-deobfuscator/deobfuscator#829]
[main] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse FIELD1.class (is it a class file?)
me.coley.cafedude.InvalidClassException: me.coley.cafedude.InvalidClassException: Does not start with 0xCAFEBABE
        at me.coley.cafedude.io.ClassFileReader.read(ClassFileReader.java:150)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:293)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:266)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:379)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
Caused by: me.coley.cafedude.InvalidClassException: Does not start with 0xCAFEBABE
        at me.coley.cafedude.io.ClassFileReader.read(ClassFileReader.java:95)
        ... 6 more

**Comment by ItzSomebody** [comment]
Not an issue. What is happening here is that the deobfuscator is attempting to parse a file that doesn't start with 0xCAFEBABE (the expected magic number for classfiles).  Feel free to add anything if needed.
