### ISSUE TITLE
[GC overhead limit exceeded] Deobfuscation error

### ISSUE THREAD

**Issue by I2rys** [java-deobfuscator/deobfuscator#831]
Whenever I try to deobfuscate this is the error that comes out.

You might ask:
Have you tried using other transformers?
Yes and the result is still the same.

What is the file?
A Minecraft hack client called Jigsaw, I tried deobfuscating it using this for testing & fun only but yeah error.
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.objectweb.asm.ClassWriter.visitMethod(ClassWriter.java:446)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:629)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:458)
        at com.javadeobfuscator.deobfuscator.Deobfuscator$$Lambda$310/120623861.accept(Unknown Source)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:456)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
Error while writing com/google/common/primitives/Bytes
java.lang.OutOfMemoryError: GC overhead limit exceeded
Error while writing AbstractResourcePack
java.lang.OutOfMemoryError: GC overhead limit exceeded
Error while writing com/google/common/collect/HashBiMap
java.lang.OutOfMemoryError: GC overhead limit exceeded
Error while writing BlockStoneSlabNew$ï
java.lang.OutOfMemoryError: GC overhead limit exceeded
Error while writing EntityFlameFX
java.lang.OutOfMemoryError: GC overhead limit exceeded
Error while writing org/apache/http/config/MessageConstraints$Builder
java.lang.OutOfMemoryError: GC overhead limit exceeded
Error while writing BlockGrass
java.lang.OutOfMemoryError: GC overhead limit exceeded


Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded

```

[To_Deobfuscate.zip](https://github.com/java-deobfuscator/deobfuscator/files/7357091/To_Deobfuscate.zip)

**Comment by Janmm14** [comment]
See #642
