### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Midaco54e** [java-deobfuscator/deobfuscator#851]
`[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:99)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:120)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:300)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)`

**Comment by Midaco54e** [comment]
my config.yml
`input: PalaMod-Client.jar
output: palamod-prod-deob.jar
path:
    - D:\jar\Nouveau\palabuildtool\rt.jar
transformers:
    - normalizer.SourceFileClassNormalizer`
