### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by SamHoque** [java-deobfuscator/deobfuscator#855]
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:456)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Unknown Source)
```

```Error: lIllllIlIIIIIlIlIlIIllIlIlIIllIIIIIlllIllIlllIlIlIlIlllIlIIIlIIIlIIIIIllIIIllllllI/IlIlllIlllllIIlllIIlIIIIlIIIIIIIlIlIIlIllllIIlIIIIllllIllIlIllIIlIllIlIIll/lIllllIlIIIIIlIlIlIIllIlIlIIllIIIIIlllIllIlllIlIlIlIlllIlIIIlIIIlIIIIIllIIIllllllI/IlIlllllIIlIIllIIllIIIIlIIIlllIIlIllIlllIIllllIlIIllIIlllIllIIIIlIllll/IlIllllIIIIIlIllIlllllIIIIIlllllIlIIllIIIlllllIllIllIIlIIIllIlllllIIllIllII failed verification
java.lang.IllegalStateException: Emty try catch block handler range
	at org.objectweb.asm.util.CheckMethodAdapter.visitMaxs(CheckMethodAdapter.java:1024)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2642)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:659)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:458)
	at java.base/java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:456)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Config: https://i.imgur.com/lkdtEMi.png

**Comment by ItzSomebody** [comment]
@SamHoque: Any update on this? Also, are you able to provide the input JAR provided it's alright to legal-wise (#653).

**Comment by SamHoque** [comment]
Not sure what the issue was, but I solved it. Thank you
