### ISSUE TITLE
error

### ISSUE THREAD

**Issue by loxop1122** [java-deobfuscator/deobfuscator#860]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
        at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
        at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
        at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
        at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer.transform(SimpleStringEncryptionTransformer.java:74)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

**Comment by ItzSomebody** [comment]
@loxop1122 Did you end up figuring this out?

**Comment by Janmm14** [comment]
A try with the ZelixStringTransformer without `string.` infront might lead to better results.
