### ISSUE TITLE
Could not load module-info

### ISSUE THREAD

**Issue by QwertyYtPL** [java-deobfuscator/deobfuscator#863]
I tried to use these transformers
![obraz](https://user-images.githubusercontent.com/75856137/149631137-eb0a44c7-2965-454e-9438-66c6e2e05bc0.png)
on file:
https://transfer.sh/wTUFPb/obf.jar
using libraries:
https://transfer.sh/zKIHuS/libs.zip
and im getting error:
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException: Could not load module-info
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:556)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:522)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:616)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer.lambda$remap$0(DuplicateRenamer.java:66)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer$$Lambda$86/2094370760.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.DuplicateRenamer.remap(DuplicateRenamer.java:65)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$$Lambda$77/1506914501.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Janmm14** [comment]
Copy jar and delete all module-info.class files

**Comment by QwertyYtPL** [comment]
i cant find that classes

**Comment by QwertyYtPL** [comment]
oh i have found it in META-INF folder
