### ISSUE TITLE
FieldNormalizer: IllegalArgumentException

### ISSUE THREAD

**Issue by QwertyYtPL** [java-deobfuscator/deobfuscator#867]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
```
java.lang.IllegalArgumentException
	at org.objectweb.asm.Type.getTypeInternal(Type.java:443)
	at org.objectweb.asm.Type.getArgumentTypes(Type.java:331)
	at org.objectweb.asm.commons.Remapper.mapMethodDesc(Remapper.java:135)
	at org.objectweb.asm.commons.MethodRemapper.visitInvokeDynamicInsn(MethodRemapper.java:186)
	at org.objectweb.asm.tree.InvokeDynamicInsnNode.accept(InvokeDynamicInsnNode.java:84)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Thread.java:748)
```

im trying to use FieldNormalizer

**Comment by QwertyYtPL** [comment]
on this jarfile: https://transfer.sh/cTHRNQ/file.jar

**Comment by Janmm14** [comment]
> *@QwertyYtPL wrote:*
>
> on this jarfile: *redacted*

You may not upload or link to jars that violate copyright (here copyright of mojang and sp614x), see #653.
Please remove @ItzSomebody 

Judging from the stack trace, the problem might actually be inside ASM. Try proguard as alternative renaming tool.
