### ISSUE TITLE
Deobfuscation Failed

### ISSUE THREAD

**Issue by 3328429240** [java-deobfuscator/deobfuscator#869]
Error occurred while enabling MobLevel v1.0 (Is it up to date?)
java.lang.VerifyError: JVMVRFY012 堆栈形状不一致 类=com/moblevel/c/IiiIiIIIII，方法=IiIIIIIiII(Lorg/bukkit/event/inventory/InventoryClickEvent;)V，pc=14
Exception Details:
  Location:
    com/moblevel/c/IiiIiIIIII.IiIIIIIiII(Lorg/bukkit/event/inventory/InventoryClickEvent;)V @14: JBifnonnull
  Reason:
    A stackmap frame is expected at branch target 19.
	at com.moblevel.MobLevel.onEnable(j:180) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_242]

**Comment by Janmm14** [comment]
And where is the connection to java-deobfuscator?

**Comment by ItzSomebody** [comment]
Closing due to a lack of response from OP.
