### ISSUE TITLE
ZipFile

### ISSUE THREAD

**Issue by 3328429240** [java-deobfuscator/deobfuscator#870]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.io.FileNotFoundException: F:\danji\MineCraft\ￔￓￎ￯\ￎￒﾵￄￊ￀ﾽ￧￐ﾡﾹﾤﾾ￟ﾺￏﾼﾯ\ￎￒﾵￄￊ￀ﾽ￧ﾲ￥ﾼ￾ﾼￓￃￜﾷﾴﾻ￬ￏ�\1.jar (ￏﾵￍﾳￕￒﾲﾻﾵﾽￖﾸﾶﾨﾵￄￎￄﾼ￾ﾡﾣ)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:201)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:379)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
Deobfuscator could not find the file you specified as input file.

**Comment by ItzSomebody** [comment]
Closing due to lack of response from OP.
