### ISSUE TITLE
error in opening zip file

### ISSUE THREAD

**Issue by TalhaDaddy** [java-deobfuscator/deobfuscator#872]
C:\Users\godra\Desktop\sss>java -jar deobfuscator.jar --config detect.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:254)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:379)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:78)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

**Comment by Janmm14** [comment]
These possibilities can lead to this error:
- The input jar file you used is corrupt.
- The input file you chose is no jar file
- The input jar file is selectively corrupted so that the java.exe internal zip reader can read it, but the java zip api cannot.

**Comment by ItzSomebody** [comment]
Closing due to lack of response from OP.
