### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by JabaSkidCode** [java-deobfuscator/deobfuscator#879]
Error :

[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer
[AntiReleak] [InvokedynamicTransformer] Starting
[AntiReleak] [InvokedynamicTransformer] Finding invokedynamic instructions
[AntiReleak] [InvokedynamicTransformer] Found 2689 invokedynamic instructions
[AntiReleak] [InvokedynamicTransformer] Inlining invokedynamic
org/newnh2/client/feature/impl/combat/Criticals

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1037)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
        at com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer.lambda$null$3(InvokedynamicTransformer.java:232)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer.lambda$inlineInvokeDynamic$4(InvokedynamicTransformer.java:179)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer.inlineInvokeDynamic(InvokedynamicTransformer.java:177)
        at com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer.transform(InvokedynamicTransformer.java:70)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
config.yml : 

input: NeverHook.jar
output: NeverHook2.jar
path:
 - "C:/Program Files/Java/jdk1.8.0_231/jre/lib/rt.jar"
detect: false
transformers:
 - antireleak.InvokedynamicTransformer
 - normalizer.SourceFileClassNormalizer

**Comment by JabaSkidCode** [comment]
Who wanna help me? 3>

**Comment by ItzSomebody** [comment]
@JabaSkidCode DId you ever get around to figuring this out?
