### ISSUE TITLE
Which files?

### ISSUE THREAD

**Issue by Bloupix** [java-deobfuscator/deobfuscator#88]
Which files i have to add to -path except of rt.jar?
I still get errors like NoClassInPathException.

Thanks for your help

**Comment by FFY00** [comment]
None, it only requires rt.

What OS are you using?
Paste the output and the command you're using.

**Comment by Bloupix** [comment]
Windows 10 pro 64bit

java -jar deobfuscator-1.0.0.jar -input input.jar -output output_unstr.jar -transformer allatori.StringEncryptionTransformer -path "C:\Program Files\Java\jre1.8.0_25\lib\rt.jar"

Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: com/google/common/base/Predicate
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:240)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:26)

**Comment by FFY00** [comment]
Oh, yeah you need to add all dependencies to the -path argument. I was thinking of a clean jar without any dependencies, nevermind.
