### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Garrry4** [java-deobfuscator/deobfuscator#881]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException: Cannot invoke "com.javadeobfuscator.javavm.mirrors.JavaClass.isPrimitive()" because "this.componentType" is null
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
	at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
	at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
	at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Janmm14** [comment]
Please try to use allatori.StringEncryptionTransformer instead - what issues arise with this transformer?

**Comment by Garrry4** [comment]
give me 5 seconds

**Comment by Garrry4** [comment]
what should i use it instead of
]

**Comment by Garrry4** [comment]
![image](https://user-images.githubusercontent.com/97790503/155888664-6f04f08d-8b88-45e6-ac29-27fda2e48003.png)
 

I already have it on

**Comment by Garrry4** [comment]
Should i drop my properties and config file?

**Comment by Janmm14** [comment]
try `allatori.StringEncryption`

**Comment by Garrry4** [comment]
![image](https://user-images.githubusercontent.com/97790503/155889604-dcee7ef8-7387-4099-b88b-d0cd5795893e.png)
I have it on

**Comment by Garrry4** [comment]
How can i send u my config and properties files

**Comment by Janmm14** [comment]
@Garrry4 There is a transformer selection in there because not every transformer is suitable for every program / obfuscation.

Some transformers like the "normalizers" could also destroy any further attempts at deobfuscation or make the deobfuscated file not run anymore.

Please use the detect feature to let the program detect the probably used obfuscation and then only try with the first recommended transformer.

**Comment by Garrry4** [comment]
Do i just hit detect and then run?

**Comment by Garrry4** [comment]
![image](https://user-images.githubusercontent.com/97790503/155890021-9f3bf1ed-6c6b-435c-b611-a7890d484000.png)

**Comment by Janmm14** [comment]
> Do i just hit detect and then run?

yes

**Comment by Garrry4** [comment]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.nio.file.NoSuchFileException: C:\Users\100ge\Desktop\legit.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:201)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:379)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Thread.java:833)


It cam up with this

**Comment by Garrry4** [comment]
WAIT
i think i fixed

**Comment by Garrry4** [comment]
![image](https://user-images.githubusercontent.com/97790503/155890244-b63ac40c-af51-42bc-8fa9-2bea9c5b4bb5.png)
Came up with this

**Comment by Janmm14** [comment]
ok. now you remove the check at detect and then only use special.Superblaubeere transformer

**Comment by Garrry4** [comment]
Do i just wait and it does its thing?

**Comment by Garrry4** [comment]
It does
thanks for the help
