### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by ThnksCJ** [java-deobfuscator/deobfuscator#883]
```Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException
	at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:249)
	at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:122)
	at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:209)
	at org.objectweb.asm.commons.ClassRemapper.visitMethod(ClassRemapper.java:193)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Thread.java:833)```

this happens when i try to deobf a file

**Comment by Janmm14** [comment]
Normalizers do not provide real deobfuscation.  They only rename classes, methods or fields to Class1, Class2 (or method1, method2) etc.
Leave it out or try IllegalSignatureRemover before
