### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by RealNoahgg** [java-deobfuscator/deobfuscator#884]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException: Cannot invoke "com.javadeobfuscator.javavm.mirrors.JavaClass.isPrimitive()" because "this.componentType" is null
        at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
        at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
        at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
        at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
        at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer.transform(EnhancedStringEncryptionTransformer.java:51)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

**Comment by Janmm14** [comment]
Did you follow the tutorial and used the detect feature before attempting deobfuscation?
What is the output of running this deobfuscator in detect mode?


(As a general solution attempt try to use zelix.StringEncryptionTransformer instead)

**Comment by ItzSomebody** [comment]
Closing due to a lack of response from OP.
