### ISSUE TITLE
StringEncryptionTransformer throw java.io.IOException

### ISSUE THREAD

**Issue by 502647092** [java-deobfuscator/deobfuscator#886]
```
[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in com/germ/germplugin/api/util/DateUtil <init>()V: ﾴ￺ￂ￫ﾹ�ￆￚ￁ￋ
[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in com/germ/germplugin/api/util/DateUtil transformationSecond(I)Ljava/lang/String;:  ￌ￬ 
[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in com/germ/germplugin/api/util/DateUtil transformationSecond(I)Ljava/lang/String;:  ￊﾱ 
[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in com/germ/germplugin/api/util/DateUtil transformationSecond(I)Ljava/lang/String;:  ﾷￖ 
[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in com/germ/germplugin/api/util/DateUtil transformationSecond(I)Ljava/lang/String;:  ￃ￫
[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in com/germ/germplugin/api/util/DateUtil getDate()Ljava/lang/String;: yyyy-MM-dd
[Thread-6] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in com/germmc!/0OOO0OOO0O0OOOOOO00OOO00000OOO000O000000OOOO0OO00O0O0000 ALLATORIxDEMO(Lorg/bukkit/event/inventory/InventoryClickEvent;)V: ￊ�ﾾ￝﾿￢ﾳ￶ￏￖￖￂￃ￼ﾱﾣﾴ￦ﾴ￭ￎ￳ﾣﾬￇ￫￁ﾪￏﾵﾹￜ￀￭ￔﾱﾣﾡ
java.io.IOException: ﾾ￤ﾱ￺ￎ￞￐ﾧﾡﾣ
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at com.javadeobfuscator.javavm.nativeimpls.java_io_FileOutputStream.lambda$registerNatives$1(java_io_FileOutputStream.java:73)
	at com.javadeobfuscator.javavm.hooks.HookedMethod.lambda$bind$0(HookedMethod.java:56)
	at com.javadeobfuscator.javavm.hooks.HookedMethod.execute(HookedMethod.java:84)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1191)
	at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvokeSpecialInstruction.execute(InvokeSpecialInstruction.java:84)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
```

**Comment by ItzSomebody** [comment]
@502647092 Did you end up figuring this out?
