### ISSUE TITLE
I tried to use 2 transformers and this popped up..

### ISSUE THREAD

**Issue by Github3742** [java-deobfuscator/deobfuscator#889]
My Error:

java.lang.IllegalArgumentException: entry name too long
	at java.base/java.util.zip.ZipEntry.<init>(ZipEntry.java:108)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:460)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:456)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
	--------------------------------------------------------------------------------------------------------
My config:
java -jar deobfuscator.jar -input "C:\Users\alexa\Downloads\Java obfuscation\Deobfuscate\banana-obf.jar" -output "C:\Users\amogus\Downloads\Java obfuscation\Deobfuscate\output.jar" -transformer stringer.StringEncryption -transformer stringer.HideAccessObfuscation

I don't know how to fix this. This is my first time trying to deobfuscate a file. (I did it on the gui version, if thats any help)

Thanks for your time :)

**Comment by Janmm14** [comment]
Can't do much here. I suggest trying to use a regular zip program to remove the too long entries in a copy of the file and then trying to use the deobfuscator again.

**Comment by Github3742** [comment]
I fixed it by removing the file in decaf it was a com file with special characters that went for about 50 files
ty for your help
