### ISSUE TITLE
Deobfuscate Spigot-Plugins

### ISSUE THREAD

**Issue by pascal25565** [java-deobfuscator/deobfuscator#89]
I have tryed to deobfuscate a plugin but i get a NoClassInPathException Exception.

`com.javadeobfuscator.deobfuscator.Deobfuscator$NoClassInPathException: org/bukkit/event/Listener
	at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:197)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:240)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:207)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:160)`

**Comment by FFY00** [comment]
You need to add the Spigot jar to the classpath.

**Comment by pascal25565** [comment]
Its not working...

**Comment by FFY00** [comment]
Paste the command that you using.

**Comment by maxim19116** [comment]
You need to modify rt.jar

**Comment by Janmm14** [comment]
No need to modify rt.jar, you can add multiple `-path` arguments.
