### ISSUE TITLE
Deobfuscation failed: provided error

### ISSUE THREAD

**Issue by MaddoxOSRS** [java-deobfuscator/deobfuscator#890]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
        at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
        at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
        at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
        at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
        at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

input: NUtils-0.0.5.jar
output: cleaned.jar
transformers:
  - allatori.StringEncryptionTransformer
  - allatori.string.StringEncryptionTransformer

**Comment by Janmm14** [comment]
try without `allatori.string.StringEncryptionTransformer`

**Comment by ItzSomebody** [comment]
Closing due to a lack of response from OP.
