### ISSUE TITLE
Error using binscure tranformer

### ISSUE THREAD

**Issue by XeonLyfe** [java-deobfuscator/deobfuscator#892]
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/util/concurrent/ConcurrentHashMap ()V @ dev/nuker/pyro/dc ()V
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1348)
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1298)
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1298)
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
at com.javadeobfuscator.deobfuscator.transformers.special.BinscureTransformer.transform(BinscureTransformer.java:899)
at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
btw as a hint there is already a pyroclient-deobf project on github, just google it (5 months old tho)
otherwise i will create a pr soon to add concurrenthashmap to jvmmethodprovider

**Comment by XeonLyfe** [comment]
thank you, the obfuscator was updated and that may be why, also im deobfuscating something else that uses binscure now.

https://github.com/master7720/binscure
