### ISSUE TITLE
Deobfuscating with detect.yml error

### ISSUE THREAD

**Issue by SvenGoormans** [java-deobfuscator/deobfuscator#893]
Hello! I'm getting following error. Any idea how to get this working?
```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Detecting known obfuscators
java.lang.IllegalArgumentException
        at org.objectweb.asm.Type.getTypeInternal(Type.java:443)
        at org.objectweb.asm.Type.getArgumentTypes(Type.java:331)
        at org.objectweb.asm.Type.getArgumentTypes(Type.java:285)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.basicType(TransformerHelper.java:298)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.basicType(TransformerHelper.java:286)
        at com.javadeobfuscator.deobfuscator.rules.stringer.RuleStringDecryptorV3.test(RuleStringDecryptorV3.java:39)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:387)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:78)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
java.lang.IllegalArgumentException
        at org.objectweb.asm.Type.getTypeInternal(Type.java:443)
        at org.objectweb.asm.Type.getArgumentTypes(Type.java:331)
        at com.javadeobfuscator.deobfuscator.rules.dasho.RuleStringDecryptor.test(RuleStringDecryptor.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:387)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:78)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - All detectors have been run. If you do not see anything listed, check if your file only contains name obfuscation.
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Do note that some obfuscators do not have detectors.
```

**Comment by Janmm14** [comment]
Looks like one or multiple illegal classes exists in your input jar.

**Comment by SvenGoormans** [comment]
Any idea how to 'fix' this?

**Comment by Janmm14** [comment]
> Any idea how to 'fix' this?

I have pushed a "fi"x for this to #888 - the exception will be ignored

Clone my fork and switch to that branch and build it yourself if you want to test it right now and not when ppl with push access get to accept my PR
