### ISSUE TITLE
stringer. Hideaccessobfuscation problem

### ISSUE THREAD

**Issue by 3328429240** [java-deobfuscator/deobfuscator#894]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/Object fgg/nck/fx get(Ljava/lang/Object;)Ljava/lang/Object; @ cf/huzpsb/tickk/player$player e(Ljava/lang/Object;I)Ljava/lang/String;
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1248)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1394)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$1(HideAccessObfuscationTransformer.java:124)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:120)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Janmm14** [comment]
Did you add `rt.jar` to the path?

**Comment by 3328429240** [comment]
Yes, I've joined it, but it's still such a mistake!

**Comment by 3328429240** [comment]
> Did you add `rt.jar` to the path?
> 
> It should be enough to use the one from java 8 installation dir libs folder. (for Java 9+ extract rt.jar with this tool: https://github.com/Storyyeller/jrt-extractor )
Yes, I've joined it, but it's still such a mistake!

**Comment by ItzSomebody** [comment]
@3328429240 Did you end up figuring this out?

**Comment by Julienraptor01** [comment]
i have the same problem

```
[Thread-11] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-11] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-11] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-11] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-11] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer
[Stringer] [HideAccessTransformer] Starting
[Stringer] [HideAccessTransformer] Found 2 decryptors





Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/Object vxp/yfm/o get(Ljava/lang/Object;)Ljava/lang/Object; @ Quiet/i z(Ljava/lang/Object;I)Ljava/lang/String;
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1248)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1394)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$1(HideAccessObfuscationTransformer.java:124)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:120)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.lang.Thread.run(Unknown Source)
```

if it's needed i can share the jar i'm trying to deobf and the decompiled version using fernflower
(i think the program i'm trying to deobf is a RAT and that's why i'm trying to deobf it)

**Comment by Janmm14** [comment]
@Julienraptor01 did you try the solution i wrote?

**Comment by Julienraptor01** [comment]
> @Julienraptor01 did you try the solution i wrote?

How do i do that ?
I'm using Oracle JDK 17.0.5
And i think i understand what you ask to do
but what do you mean adding it to the path ?
I need to add it into the deobfuscator or into some system path ?

**Comment by Janmm14** [comment]
@Julienraptor01 Here at the bottom it shows u how to add "path" files to the config:
https://github.com/java-deobfuscator/deobfuscator/wiki/Getting-Started

You could also use the [gui](https://github.com/java-deobfuscator/deobfuscator-gui), you can add path files there too.
