### ISSUE TITLE
Deobfuscation failed. Please open a ticket

### ISSUE THREAD

**Issue by NaferSama62** [java-deobfuscator/deobfuscator#895]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ThreadDeath
	at java.base/java.lang.Thread.stop(Thread.java:942)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$2.windowClosing(SwingWindow.java:892)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2078)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2037)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[Thread-1] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-1] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-1] ERROR com.javadeobfuscator.deobfuscator.Deobfuscator - Could not parse PimaDevSecurity___O_____g__7V_____G_gl4_UG_ka___j_Ilz_PmM___muO_i__RLQ_S__1_3PF_F5yGZxDPr___XdQPW__b__7v___F__1_0_Y_l__XH_sD_9fgg_6C__J___Z_m_lb8i___4DZ______X_HWtm__k_Zd_c_x4dE__ZH_AQ_____a_rh_____B_T7Mo_O_0____l_1jax.class (is it a class file?)
me.coley.cafedude.InvalidClassException: me.coley.cafedude.InvalidClassException: Does not start with 0xCAFEBABE
	at me.coley.cafedude.io.ClassFileReader.read(ClassFileReader.java:150)

**Comment by ItzSomebody** [comment]
@NaferSama62 Did you end up figuring this out?  I have a feeling this was likely due to a crypted class or junk bytes written to an entry with a suffix of `.class`.
