### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

### ISSUE THREAD

**Issue by Yefimc** [java-deobfuscator/deobfuscator#899]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException: Cannot invoke "com.javadeobfuscator.javavm.mirrors.JavaClass.isPrimitive()" because "this.componentType" is null
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
	at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
	at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
	at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Yefimc** [comment]
I’ve tried #897 but it has not worked for me

**Comment by Janmm14** [comment]
@Yefimc 
The comment on 897 and the stack trace here show that it is still using `allatori.string.StringEncryption`.

**Comment by Janmm14** [comment]
@Yefimc 
The tutorial you followed [here](https://github.com/java-deobfuscator/deobfuscator-gui/issues/53#issuecomment-1107706139)  is completely flawed. (cant understand the language but the video was enough)

One should NEVER select all transformers.

1. You select NO transformer, but check the "Detect`"checkbox and run the transformer. Then it will tell you which transformer will likely work.
2. You close the output window. You uncheck "Detect" and select only the transformer it suggested. Now run the deobfuscator again.
