### ISSUE TITLE
bootstrapClassNode" is null

### ISSUE THREAD

**Issue by zidziyad** [java-deobfuscator/deobfuscator#902]
[Stringer] [InvokedynamicTransformer] Starting
[Stringer] [InvokedynamicTransformer] Finding invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Found 1224 invokedynamic instructions
[Stringer] [InvokedynamicTransformer] Inlining invokedynamic

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException: Cannot read field "methods" because "bootstrapClassNode" is null
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.lambda$null$3(InvokedynamicTransformer.java:140)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.lambda$inlineInvokeDynamic$4(InvokedynamicTransformer.java:132)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.inlineInvokeDynamic(InvokedynamicTransformer.java:131)
        at com.javadeobfuscator.deobfuscator.transformers.stringer.InvokedynamicTransformer.transform(InvokedynamicTransformer.java:58)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

**Comment by ItzSomebody** [comment]
This one looks like deobfuscator couldn't find Stringer's bootstrap class. Did you figure out what ended up happening @zidziyad?
