### ISSUE TITLE
how fix

### ISSUE THREAD

**Issue by bonkowo** [java-deobfuscator/deobfuscator#907]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 848: Incompatible stack heights
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:292)
	at com.javadeobfuscator.deobfuscator.transformers.general.peephole.DeadCodeRemover.transform(DeadCodeRemover.java:35)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Incompatible stack heights
	at org.objectweb.asm.tree.analysis.Frame.merge(Frame.java:700)
	at org.objectweb.asm.tree.analysis.Analyzer.merge(Analyzer.java:610)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:206)
	... 10 more

**Comment by Janmm14** [comment]
This looks like you just selected every transformer. Do never do that. Instead follow the wiki where it tells you to first run the deobfuscator with detect feature. If what it detects is not general.SourceFileClassTransformer, it has either found which obfuscation is used and recommends the _single_ transformer you should select or it is some obfuscation this deobfuscator does not support.


Input seems to be wrong either due to previous transformers doing illegitimate stuff or because inpit was always wrong or input has fake classes.

**Comment by ItzSomebody** [comment]
Closing due to lack of response from OP.
