### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

### ISSUE THREAD

**Issue by Not-Hax** [java-deobfuscator/deobfuscator#911]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException
	at org.objectweb.asm.Type.getTypeInternal(Type.java:443)
	at org.objectweb.asm.Type.getArgumentTypes(Type.java:331)
	at org.objectweb.asm.commons.Remapper.mapMethodDesc(Remapper.java:135)
	at org.objectweb.asm.commons.ClassRemapper.visitMethod(ClassRemapper.java:187)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Thread.java:750)

**Comment by Not-Hax** [comment]
tried #474, not working

**Comment by ItzSomebody** [comment]
This doesn't look like it's in the scope of #474. Did you end up figuring out what the issue was @Not-Hax?
