### ISSUE TITLE
NoSuchMethodHandlerException

### ISSUE THREAD

**Issue by zhusun890** [java-deobfuscator/deobfuscator#912]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for java/lang/Object lrc/mth/nm get(Ljava/lang/Object;)Ljava/lang/Object; @ NMSL/asniod/wefwgew/qfqfewf/f/wgtgwf/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/ergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/f/wgtgwergvf/gvedh/tyhryr/ytjuyjyr/jnyj67ikjh/gndfbgr5/g2fdsvr43/yh35/htdg/br/wg/35/4t/g/w/rgt/34/gt/tre/h54ghrwgvw2/grtegwg43/gerwg3h/tbgerghthrt/hy5j57j5y6/sadqwdqwd/shabi/n j(Ljava/lang/Object;I)Ljava/lang/String;
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1248)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.executor.defined.MappedMethodProvider.invokeMethod(MappedMethodProvider.java:54)
	at com.javadeobfuscator.deobfuscator.executor.providers.DelegatingProvider.invokeMethod(DelegatingProvider.java:35)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1394)
	at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:76)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.lambda$transform$1(HideAccessObfuscationTransformer.java:124)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.stringer.HideAccessObfuscationTransformer.transform(HideAccessObfuscationTransformer.java:120)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
You need to add java's rt.jar to the path.

If you did that, try to select stringer's StringEncryptionTransformer before!
