### ISSUE TITLE
java.lang.IllegalArgumentException: entry name too long

### ISSUE THREAD

**Issue by mrlolua19** [java-deobfuscator/deobfuscator#914]
I was deobfuscating with special.Superblaubeere. I can't attach the file sadly
java.lang.IllegalArgumentException: entry name too long
	at java.base/java.util.zip.ZipEntry.<init>(ZipEntry.java:108)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:460)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:456)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Janmm14** [comment]
try to delete suspiciously long entries with a program like 7zip or try import & export in recaf before

**Comment by ItzSomebody** [comment]
Closing due to lack of response from OP.
