### ISSUE TITLE
Failed to open input file

### ISSUE THREAD

**Issue by catears124** [java-deobfuscator/deobfuscator#915]
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:254)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:379)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:78)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

Ive tried to follow the readme but it couldnt detect the obfuscation (with the detect.yml)

**Comment by ItzSomebody** [comment]
You're gonna have issues even getting to the detection stage if you can't even open the file.  Check #653 and upload a sample if you can.

There are a ton a reasons why something like this can happen.

**Comment by Janmm14** [comment]
"recaf 3" has built in some zip file reading improvements. import file into recaf 3 and export as jar again, then try java-deobfuscator.
