### ISSUE TITLE
A little problem i'm having with zelix.string.SimpleStringEncryptionTransformer

### ISSUE THREAD

**Issue by al4sk4s** [java-deobfuscator/deobfuscator#916]
Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.javavm.exceptions.ExecutionException: UnsatisfiedLinkError: java/lang/ClassLoader$NativeLibrary load(Ljava/lang/String;ZZ)V
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1209)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.VirtualMachine.fullInitialization(VirtualMachine.java:140)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:270)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.string.SimpleStringEncryptionTransformer.transform(SimpleStringEncryptionTransformer.java:74)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
		at java.lang.ClassLoader.loadLibrary0(Unknown Source)
		at java.lang.ClassLoader.loadLibrary(Unknown Source)
		at java.lang.Runtime.loadLibrary0(Unknown Source)
		at java.lang.System.loadLibrary(Unknown Source)
		at java.lang.System.initializeSystemClass(Unknown Source)

**Comment by greenozon** [comment]
@al4sk4s  does your target use JavaFX? I've seen recently that  jfxrt.jar  refers to 2 native dlls:  javafx_iio.dll and javafx_font.dll
maybe it's all about it?

**Comment by greenozon** [comment]
Above dlls are not final set, here are all...
![image](https://user-images.githubusercontent.com/765343/180603893-07610ae5-6e40-43a1-9d52-8a2edcae060c.png)

**Comment by Janmm14** [comment]
In this case I'd suggest trying to use zelix StringTransformer which does not have "`string.` in name, maybe it can better ignore such an error.
