### ISSUE TITLE
Zulu missing erro

### ISSUE THREAD

**Issue by awesome26-dev** [java-deobfuscator/deobfuscator#922]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException: Cannot invoke "com.javadeobfuscator.javavm.mirrors.JavaClass.isPrimitive()" because "this.componentType" is null
        at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
        at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
        at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
        at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
        at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
        at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

Error Code: https://haste.devstorage.eu/dcYQh1XzVx

**Comment by Janmm14** [comment]
Try to use transformer without `string.`

**Comment by awesome26-dev** [comment]
How thne?

--------------

input: input.jar
output: output.jar
transformers:
  - allatori.string.StringEncryptionTransformer
  - allatori.StringEncryptionTransformer

**Comment by Janmm14** [comment]
you remove the line where the transformers name includes `string.` and try again.

**Comment by awesome26-dev** [comment]
Likes this?

-----------------

input: input.jar
output: output.jar
transformers:

allatori.StringEncryptionTransformer
allatori.StringEncryptionTransformer

----------------
or this 
--------------

input: input.jar
output: output.jar

**Comment by awesome26-dev** [comment]
Ahh i have this, thanks!
