### ISSUE TITLE
Deobfuscation failed. 

### ISSUE THREAD

**Issue by KuoKongQingYun** [java-deobfuscator/deobfuscator#926]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.nio.BufferUnderflowException
        at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:707)
        at java.base/java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:435)
        at me.coley.cafedude.io.InstructionReader.read(InstructionReader.java:275)
        at me.coley.cafedude.transform.IllegalStrippingTransformer.transform(IllegalStrippingTransformer.java:112)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:291)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:269)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:378)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:78)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

[files](https://www.99.wf/unpacked_files.zip)

It should be obfuscated by allatori,because it has ALLATORIxDEMO method.

**Comment by Janmm14** [comment]
Some class file seems corrupt.

**Comment by KuoKongQingYun** [comment]
> Some class file seems to be corrupt. As bandaid you can try to look for it manually and remove it
Thank you.
I found the jar is protected by a javaagent just now,so I need resolve it first.
