### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported class file major version 62

### ISSUE THREAD

**Issue by awholemystery** [java-deobfuscator/deobfuscator#927]
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
[SourceFileClassNormalizer] Recovered 18913 source filenames
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
[Allatori] [StringEncryptionTransformer] Starting
[Allatori] [StringEncryptionTransformer] Decrypted 18240 encrypted strings
[Allatori] [StringEncryptionTransformer] Removed 0 decryption methods
[Allatori] [StringEncryptionTransformer] Done
[Thread-4] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error while writing fr/paladium/libs/okhttp3/internal/ws/RealWebSocket
java.lang.IllegalArgumentException: Unsupported class file major version 62
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:295)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.pullFromRuntime(Deobfuscator.java:511)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:487)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:571)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:540)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:634)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.isAssignableFrom(Deobfuscator.java:745)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass0(Deobfuscator.java:721)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass1(Deobfuscator.java:705)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass(Deobfuscator.java:698)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:650)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:457)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:455)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Thread.java:833)
Error while writing com/google/common/util/concurrent/MoreExecutors
java.lang.IllegalArgumentException: Unsupported class file major version 62
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:295)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.pullFromRuntime(Deobfuscator.java:511)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:487)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:571)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:540)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:634)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.isAssignableFrom(Deobfuscator.java:745)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass0(Deobfuscator.java:721)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass1(Deobfuscator.java:705)
	at com.javadeobfuscator.deobfuscator.Deobfuscator$CustomClassWriter.getCommonSuperClass(Deobfuscator.java:698)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm.Frame.merge(Frame.java:1244)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.toByteArray(Deobfuscator.java:650)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.lambda$start$9(Deobfuscator.java:457)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:455)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.base/java.lang.Thread.run(Thread.java:833)
Error while writing org/apache/http/impl/DefaultBHttpServerConnection
java.lang.IllegalArgumentException: Unsupported class file major version 62
here is the zipfile with the config, the plugin and the librairies that he need (i can't upload it to github): https://www.mediafire.com/file/3gqlcv4c584supc/plugin.zip/file
and here is also the log file because it is way too long to upload it on github: https://www.mediafire.com/file/w8e8acf4e9argo1/log.txt/file
thank you very much!

**Comment by sitanshuforever** [comment]
I am getting the same error. but with major version 64. 
"java.lang.IllegalArgumentException: Unsupported class file major version 64
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:298)"


Anything workarounds ?

**Comment by Janmm14** [comment]
@sitanshuforever Fix: https://github.com/java-deobfuscator/deobfuscator/pull/959
This is a regular task, updating the asm version at least every time a new java version releases.

**Comment by sitanshuforever** [comment]
Thanks for the update !! However, since the release build is not updated with the same, i tried to build via intellij and was getting error related to sun library which has been used in the project. It will be helpful if there is any documentation for building too.

**Comment by Janmm14** [comment]
> Thanks for the update !! However, since the release build is not updated with the same, i tried to build via intellij and was getting error related to sun library which has been used in the project. It will be helpful if there is any documentation for building too.

Use jdk8. (Or just delete the reflectiveprovider class or however thats named before you build.)
