### ISSUE TITLE
Deobfuscation Allatori fail

### ISSUE THREAD

**Issue by Sley67** [java-deobfuscator/deobfuscator#931]
Hello, I have a problem with de-obfuscation of jar files

### Here config files
```
input: MyInput.jar
output: MyOutput.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
```

```
com.javadeobfuscator.javavm.exceptions.ExecutionException: UnsatisfiedLinkError: java/lang/ClassLoader$NativeLibrary load(Ljava/lang/String;ZZ)V
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1209)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
        at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
        at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
        at com.javadeobfuscator.javavm.VirtualMachine.fullInitialization(VirtualMachine.java:140)
        at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:270)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
        Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
                at java.lang.ClassLoader.loadLibrary0(Unknown Source)
                at java.lang.ClassLoader.loadLibrary(Unknown Source)
                at java.lang.Runtime.loadLibrary0(Unknown Source)
                at java.lang.System.loadLibrary(Unknown Source)
                at java.lang.System.initializeSystemClass(Unknown Source)
```

**Comment by Janmm14** [comment]
The recommendation is actually to just use the first transformer the detect feature suggests. And if it does not work to replace it with the second one it suggests.

So please try again with just the first transformer.

**Comment by Sley67** [comment]
> The recommendation is actually to just use the first transformer the detect feature suggests. And if it does not work to replace it with the second one it suggests. We can see here that the second one fails.
> 
> So please try again with just the first transformer.



Thank you, Is it possible to counter this error ?

```
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer
[Allatori] [StringEncryptionTransformer] Starting
[Allatori] [StringEncryptionTransformer] Decrypted 16434 encrypted strings
[Allatori] [StringEncryptionTransformer] Removed 172 decryption methods
[Allatori] [StringEncryptionTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: com/mojang/authlib/GameProfile could not be found while writing net/minecraft/client/m/w/EzoxZy????????????????????????????????????. Using COMPUTE_MAXS
Error: io/netty/buffer/ByteBuf could not be found while writing fr/krakozia/client/a/EzoxZy?????????????????????????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: com/mojang/authlib/minecraft/MinecraftProfileTexture could not be found while writing net/minecraft/client/z/EzoxZy???. Using COMPUTE_MAXS
Error: com/mojang/authlib/GameProfile could not be found while writing net/minecraft/s/z/EzoxZy????????????????????????????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: io/netty/buffer/ByteBuf could not be found while writing net/minecraft/client/p/EzoxZy??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: com/mojang/authlib/exceptions/AuthenticationUnavailableException could not be found while writing net/minecraft/client/q/EzoxZy???????????????. Using COMPUTE_MAXS
Error: io/netty/channel/ChannelFuture could not be found while writing net/minecraft/e/EzoxZy?????????????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: io/netty/buffer/ByteBuf could not be found while writing net/minecraft/j/r/EzoxZy??????????????????????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: io/netty/buffer/ByteBuf could not be found while writing fr/krakozia/client/m/EzoxZy????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: io/netty/buffer/ByteBuf could not be found while writing net/minecraft/z/EzoxZy???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: tv/twitch/ErrorCode could not be found while writing net/minecraft/client/w/EzoxZy????????????????????????????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: io/netty/buffer/ByteBuf could not be found while writing net/minecraft/client/p/EzoxZy???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: org/lwjgl/opengl/Drawable could not be found while writing net/minecraft/x/EzoxZy???. Using COMPUTE_MAXS
Error: io/netty/buffer/ByteBuf could not be found while writing net/minecraft/e/EzoxZy????????????????????????????????????????????????. Using COMPUTE_MAXS
Error: io/netty/buffer/ByteBuf could not be found while writing fr/krakozia/client/l/EzoxZy????????????????????????????????????. Using COMPUTE_MAXS
Error: joptsimple/ArgumentAcceptingOptionSpec could not be found while writing net/minecraft/client/main/Main. Using COMPUTE_MAXS
Error: tv/twitch/chat/ChatUserList could not be found while writing net/minecraft/client/w/EzoxZy??????????????????????????????????????????????????????. Using COMPUTE_MAXS
```

**Comment by Janmm14** [comment]
That type of  error should more e like a warning. Stuff will still work.
