### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported class file major version 62

### ISSUE THREAD

**Issue by BKirev** [java-deobfuscator/deobfuscator#933]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

```
java.lang.IllegalArgumentException: Unsupported class file major version 62
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:295)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.pullFromRuntime(Deobfuscator.java:511)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.assureLoaded(Deobfuscator.java:487)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachy(Deobfuscator.java:571)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadHierachyAll(Deobfuscator.java:540)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.getClassTree(Deobfuscator.java:634)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.lambda$remap$0(FieldNormalizer.java:39)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer.remap(FieldNormalizer.java:38)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.transformers.DelegatingTransformer.transform(DelegatingTransformer.java:28)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
 ```
        
Config:

```
input: classes-dex2jar.jar
output: output.jar
transformers:
  - normalizer.ClassNormalizer: {}
    normalizer.FieldNormalizer: {}
```

**Comment by ItzSomebody** [comment]
This one is caused by the deobfuscator running on an old version of the bytecode parser that doesn't support Java 18.  Should be able to fix it by bumping the ASM libs to the more recent versions

**Comment by theoparis** [comment]
I would recommend using something like renovatebot in the future so that users don't have to make their own prs to update dependencies.
