### ISSUE TITLE
Jackson NoClassDefFoundError

### ISSUE THREAD

**Issue by v-byte-cpu** [java-deobfuscator/deobfuscator#939]
Hi there! latest deobfuscator.jar always crashes with an error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:655)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:567)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:59)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```

There is no problem with the previous release version https://github.com/java-deobfuscator/deobfuscator/releases/tag/1.5.2

**Comment by Janmm14** [comment]
Just fyi we currently use github actions for a rolling release. new release overrides old one.
Might look at this soon.

**Comment by Janmm14** [comment]
ah seems like only 1 part of multiple jackson libs was updated
