### ISSUE TITLE
Allatori Deobfuscation Failed

### ISSUE THREAD

**Issue by HP888** [java-deobfuscator/deobfuscator#94]
Hi! I try to decode the plugin encoded by allatori, I used this command: java -jar deob.jar -input ms_Core.jar -output ms_Core-deobfuscated.jar -transformer allatori.StringEncryptionTransformer -path "C:\Program Files\Java\jre1.8.0_102\lib\rt.jar" -path "C:\Program Files\Java\jre1.8.0_102\lib\jce.jar" -path "C:\Users\David\Desktop\javadeob\ms_Api.jar" -path "C:\Users\David\Desktop\javadeob\BossBarAPI_v2.4.1.jar" -path "C:\Users\David\Desktop\javadeob\ProtocolLib.jar" -path "C:\Users\David\Desktop\javadeob\PaperSpigot.jar" -path "C:\Users\David\Desktop\javadeob\PermissionsEx-1.22.10.jar" -path "C:\Users\David\Desktop\javadeob\TagAPI.jar" -path "C:\Users\David\Desktop\javadeob\Vault-1.4.1.jar"
 and still is encoded but less.
Any ideas to fix?

EDIT:
This kind of thing pops up when you type a command:
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/utils/GUIUtil g(Lorg/bukkit/entity/Player;)V pl/HUBIX157/core/u
tils/Util h(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/utils/GUIUtil h(Ljava
/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/utils/GUIUtil g(Lorg/bukkit/entity/Player;)V pl/HUBIX157/core/u
tils/Util h(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/utils/GUIUtil h(Ljava
/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/utils/GUIUtil g(Lorg/bukkit/entity/Player;)V pl/HUBIX157/core/u
tils/Util h(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/utils/GUIUtil h(Ljava
/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/utils/GUIUtil g(Lorg/bukkit/entity/Player;)V pl/HUBIX157/core/u
tils/Util h(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/utils/GUIUtil h(Ljava
/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/utils/GUIUtil B(Lorg/bukkit/entity/Player;)V pl/HUBIX157/core/u
tils/Util h(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/utils/GUIUtil h(Ljava
/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/utils/GUIUtil a(Lorg/bukkit/entity/Player;)V pl/HUBIX157/core/u
tils/Util h(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/utils/GUIUtil h(Ljava
/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/utils/GUIUtil h(Lorg/bukkit/entity/Player;)V pl/HUBIX157/core/u
tils/Util h(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/utils/GUIUtil h(Ljava
/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/utils/GUIUtil ALLATORIxDEMO(Lorg/bukkit/entity/Player;)V pl/HUB
IX157/core/utils/Util h(Ljava/lang/String;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/utils/GUIUtil h(Ljava
/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/listeners/StowniarkaListener onBreakgeneator(Lorg/bukkit/event/
block/BlockBreakEvent;)V pl/HUBIX157/core/utils/Util ALLATORIxDEMO(Ljava/lang/St
ring;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/listeners/StowniarkaL
istener ALLATORIxDEMO(Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/cmd/tools/ListCommand onExecute(Lorg/bukkit/command/CommandSend
er;[Ljava/lang/String;)Z pl/HUBIX157/core/utils/Util ALLATORIxDEMO(Ljava/lang/St
ring;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/cmd/tools/ListCommand
 ALLATORIxDEMO(Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)
Error while decrypting Allatori string.
Are you sure you're deobfuscating something obfuscated by Allatori?
pl/HUBIX157/core/cmd/tools/ListCommand onExecute(Lorg/bukkit/command/CommandSend
er;[Ljava/lang/String;)Z pl/HUBIX157/core/utils/Util ALLATORIxDEMO(Ljava/lang/St
ring;)Ljava/lang/String;
com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerExcepti
on: Could not find invoker for org/bukkit/ChatColor translateAlternateColorCodes
(CLjava/lang/String;)Ljava/lang/String; @ pl/HUBIX157/core/cmd/tools/ListCommand
 ALLATORIxDEMO(Ljava/lang/String;)Ljava/lang/String;
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:1183)
        at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(Met
hodExecutor.java:80)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$null$1(StringEncryptionTransformer.java:76)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.lambda$transform$2(StringEncryptionTransformer.java:54)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncrypt
ionTransformer.transform(StringEncryptionTransformer.java:53)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.jav
a:170)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMa
in.java:102)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorM
ain.java:26)

Transforming complete. Writing to file

And more...

**Comment by Janmm14** [comment]
Did you found any still obfuscated strings? This is not neccessarily a bug.

**Comment by FFY00** [comment]
Looks like you're missing some dependencies. Try to add a old version of spigot or bukkit to the classpath.

**Comment by HP888** [comment]
Same problem, any ideas?

**Comment by Janmm14** [comment]
> Same problem, any ideas?
>
>_from @HP888_

Exactly same problem? Then you are missing also a fitting bukkit/spigot jar.

**Comment by FFY00** [comment]
Classpath definitely missing. What spigot/bukkit jars are you adding to the classpath?

**Comment by HP888** [comment]
I adding to classpath this engine: spigot-1.7.10-SNAPSHOT-b1657

Plugin classpath:
<classpath>
<classpathentry kind="src" path="src"/>
<classpathentry kind="var" path="JRE_LIB"/>
<classpathentry kind="lib" path="C:/Users/HUBIX/Desktop/folder/plugins/PermissionsEx.jar"/>
<classpathentry kind="lib" path="C:/Users/HUBIX/Desktop/folder/plugins/TagAPI.jar"/>
<classpathentry kind="lib" path="C:/Users/HUBIX/Desktop/spigot-1.7.10-SNAPSHOT-b1657.jar" sourcepath="/ms_Drop"/>
<classpathentry kind="lib" path="C:/Users/HUBIX/Desktop/ms_Api.jar"/>
<classpathentry kind="output" path="bin"/>
</classpath>

**Comment by FFY00** [comment]
Upload the jar.

**Comment by HP888** [comment]
http://www45.zippyshare.com/v/ioCwcVj7/file.html There are files needed to decode the plugin, ms_Core to the plugin to be decoded.

**Comment by FFY00** [comment]
This using an different version of bukkit and I can identify it.

In the class org.bukkit.ChatColor the method "translateAlternateColorCodes" is defined by translateAlternateColorCodes(String) and in all the other bukkit versions I checked it's defined by translateAlternateColorCodes(char, String).

**Comment by HP888** [comment]
Can you decode this plugin for me? Thanks.

**Comment by FFY00** [comment]
No, sorry. I don't have the correct bukkit version.

**Comment by HP888** [comment]
Where can I download it?

**Comment by FFY00** [comment]
I don't know what version it is so I can't answer that.

**Comment by samczsun** [comment]
Please open a new issue if this still isn't resolved
