### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported class file major version 61

### ISSUE THREAD

**Issue by PyICoder** [java-deobfuscator/deobfuscator#940]
I get this error when I try on a jar
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.IllegalArgumentException: Unsupported class file major version 61
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:106)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:127)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:327)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:120)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:113)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:50)
```
It has to do with the Java version I think, but I tried running the deobfuscator with Java 8 (my default) and Java 17 but both result in this error, I know that Java 17 uses major version 61 so what would be the issue here?

**Comment by PyICoder** [comment]
Figured it out, saw the other issue on the old asm and figured I was using the old version, only issue that still stands is the jackson issue which already mentioned in someones issue.
