### ISSUE TITLE
error on detect obfuscator java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Swallatudo2** [java-deobfuscator/deobfuscator#950]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
	at org.apache.commons.io.IOUtils.byteArray(IOUtils.java:338)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:2405)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:268)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:378)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$$Lambda$85/19244125.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
Start the gui with custom java command to allow more ram usage.
If that still doesn't solve it, the input file might contain a zip-bomb, create a copy of the input file and remove zip-bomb with 7zip or so and then try the deobfuscator.

**Comment by Swallatudo2** [comment]
> 

how i can start with custom java command?

**Comment by Janmm14** [comment]
1. Open console / bash / cmd
2. Use `java` command with custom max ram argument and the jar argument to start deobfuscator-gui.

Google is a good way to find out details, but if you don't know these yet, I'm afraid this deobfuscator probably won't help you much anyway.
