### ISSUE TITLE
java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by jurgenhaas** [java-deobfuscator/deobfuscator#951]
Running on Ubuntu 20.04 LTS with Java 17:

```
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing)
```

The exception I see is this:

```
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:257)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:378)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:78)
	at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
```

The config file looks like this:

```
input: jh.xml
detect: true
```

The command I'm running is `java -jar deobfuscator.jar --config detect.yml`

**Comment by Janmm14** [comment]
Input zip file could not be read. Try loading it in recaf_v3 and use exported jar file with deobfuscator.
If that does not help, input file is corrupted.

**Comment by jurgenhaas** [comment]
Just to be clear, the input file is an XML file, not a zip, right?

I've validated the XML file, at least its syntax is correct.

**Comment by jurgenhaas** [comment]
Never mind, I was completely off road here, sorry. Turns out, this repo is being suggested by search engines when you're searching for "LastPass deobfuscator" and I tried just that. Now realizing that this is not at all what this is all about.
