### ISSUE TITLE
Deobf Spigot Plugin Help

### ISSUE THREAD

**Issue by AJ4real** [java-deobfuscator/deobfuscator#955]
Trying to deobfuscate a spigot plugin, and am getting this exception:
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Unexpected class mapping
        at com.javadeobfuscator.deobfuscator.transformers.minecraft.SrgToMCPTransformer.remap(SrgToMCPTransformer.java:119)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:37)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
        at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```
The fields and methods csv was pulled from 1.19.3 MDK, and the [TSRG file](https://raw.githubusercontent.com/MinecraftForge/MCPConfig/master/versions/release/1.19.3/joined.tsrg) I'm using is from [MCP Config](https://github.com/MinecraftForge/MCPConfig); The transformer expects there to be 2 entries in the class line, but there are 3? 

Is there a different joined file I should be using?

**Comment by Janmm14** [comment]
That transformer and that srg file is meant for the minecraft client, not for spigot plugins.

Additionally deobfuscating premium spigot plugins or other copyrighted material is not and will not be supported here.

(But even for the minecraft client I would prefer using recaf instead of this deobfuscator)
