### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

### ISSUE THREAD

**Issue by MarkGG8181** [java-deobfuscator/deobfuscator#958]
Hello, so I am deobfuscating a Minecraft client using the Deobfuscator-GUI and I ran into some errors using it:
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Unknown Source)
	at java.lang.String.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3707)
	at org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3675)
	at org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:3656)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2441)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1016)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$$Lambda$85/2028830493.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
First you should try to use the allatori string transformer with the shorter name. 

Start the gui with custom command where you set higher -Xmx like 2G, 4G or so.
