### ISSUE TITLE
Deobf failed

### ISSUE THREAD

**Issue by MarkGG8181** [java-deobfuscator/deobfuscator#960]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.util.ConcurrentModificationException
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:455)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.lang.Thread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/86848614/230156348-b12b9e8a-dd9c-4b2e-933e-dacbed49b44b.png)
these are my settings

**Comment by Janmm14** [comment]
Never use normalizers before deobfuscation transformers lke zelix stringencryption.
I suggest you try with just the zelix transformer first and look whether that already did the trick.
When zelix is being used, the sourcefileclassnormalizer is usually not going to help at all.
