### ISSUE TITLE
Deobf failed 

### ISSUE THREAD

**Issue by N1K0LAAAA** [java-deobfuscator/deobfuscator#961]
C:\Users\Nikola\Desktop\Neuer Ordner (3)>java -Xss1024m -jar deobfuscator.jar --config config.yaml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer
[Zelix] [StringEncryptionTransformer] Starting

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Unexpected opcode! Mode 0, opcode 167 at lIIlllllIlIlIlIIIllllIIlIlIllllIllIllIlIlIIlIllIIIIllllIIlIIlllIIIlIlllIl/IlIIllllIIIIlIlllIllIIIIlIlIIlIIIlllllIIlIlIllIIIlIIIIlllIIllIIIlIIllIII/IIIIlIIlIIlIllIlIIlIllIlIlllllIIlIlllIlIlIIIlllIIlIIlllllllIIlIIIlIIllllIll/llIIIIllIIIlIllIIIlIIlIlIlllIlllIIIlllIIIIIIllIlIlllIllIlIllIlIlIIllIIlIll
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:779)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:114)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

**Comment by Janmm14** [comment]
one of these options:
- not zelix
- too new version of zelix
- another obfuscator afterwards which needs to be handled first

I am currently not that interested in deobfuscation, so i likely won't work on this. In case you think about sharing the source jar make sure you are allowed to share it legally.
