### ISSUE TITLE
StringIndexOutOfBounds Exception

### ISSUE THREAD

**Issue by liticane** [java-deobfuscator/deobfuscator#964]
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at org.objectweb.asm.Type.getObjectType(Type.java:253)
        at org.objectweb.asm.commons.Remapper.mapType(Remapper.java:79)
        at org.objectweb.asm.commons.Remapper.mapType(Remapper.java:99)
        at org.objectweb.asm.commons.MethodRemapper.visitMethodInsn(MethodRemapper.java:166)
        at org.objectweb.asm.tree.MethodInsnNode.accept(MethodInsnNode.java:115)
        at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:749)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:468)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$transform$0(AbstractNormalizer.java:47)
        at java.util.HashMap$Values.forEach(HashMap.java:982)
        at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
```

**Comment by Janmm14** [comment]
What transformer did you use?

**Comment by liticane** [comment]
> What transformer did you use?

I used `com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer`

**Comment by Janmm14** [comment]
My guess right now would be an intentionally wrong class file.

In general: In case you are not just dealing with identifier name obfuscation, the SourceFileClassNormalizer will not be useful (as first transformer).

**Comment by liticane** [comment]
It didn't find any other transformers though...

**Comment by Janmm14** [comment]
this tool is not almighty. new transformers not present. not enough people showing interest, so ppl like me prefer to keep changes and new transformers private.
i dont do this for cracking/leaking, i do this for analysis of malware and i dont want obfuscators to evolve.
