### ISSUE TITLE
com.javadeobfuscator.javavm.exceptions.ExecutionException

### ISSUE THREAD

**Issue by GamerPlands** [java-deobfuscator/deobfuscator#965]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
com.javadeobfuscator.javavm.exceptions.ExecutionException: Unexpected value: JavaUnknown(type=Ljava/lang/String;,cause=Invocation on org/bukkit/ChatColor translateAlternateColorCodes(CLjava/lang/String;)Ljava/lang/String;)
	at com.javadeobfuscator.javavm.values.JavaWrapper.asObject(JavaWrapper.java:161)
	at com.javadeobfuscator.javavm.VirtualMachine.convertJavaObjectToString(VirtualMachine.java:471)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:90)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.lang.Thread.run(Thread.java:750)

**Comment by Janmm14** [comment]
use `allatori.StringEncryptionTransformer` instead of `allatori.string.StringEncryptionTransformer`
