### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by KiritoIsMid** [java-deobfuscator/deobfuscator#969]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1597)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1488)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1495)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1299)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1262)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:842)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:257)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:378)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:78)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
        
        
        
        
        heres a little code snippet
        
        
        DGDATA03bf27c98m}‹~……:S•7bx‹avƒ|:SuKBHPEKrB9g‹ƒ|…y…pzˆŠˆˆ7PrHEJAFtD;fv‰‹o~†x…„}lz„9R;KCF9D;†~„‚:S<KILO|€x{yOLNLJGJQ}K|yzPL7B9y‡{‹|7P9fhya_ec”KFJJPKJz{JIzON{}LNNvN}}QNGzK}Sx“9D;€‹`\;T78”D;cVf_ŒŽ„ˆ:S<wLI|L}wzxI|JIwxPR€JG}~|NxwxyQ}FM9D;fz

**Comment by Janmm14** [comment]
attempt to use recaf v3: open jar followed directly by export jar.
try exported jar with deobfuscator.
