### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

### ISSUE THREAD

**Issue by neilhuang007** [java-deobfuscator/deobfuscator#971]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

```
java.lang.NullPointerException: Cannot invoke "com.javadeobfuscator.javavm.mirrors.JavaClass.isPrimitive()" because "this.componentType" is null
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:178)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:219)
	at com.javadeobfuscator.javavm.hooks.HookGenerator.generateUnknownHandlingHook(HookGenerator.java:73)
	at com.javadeobfuscator.javavm.nativeimpls.sun_misc_URLClassPath.registerNatives(sun_misc_URLClassPath.java:28)
	at com.javadeobfuscator.javavm.VirtualMachine.registerNatives(VirtualMachine.java:500)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:124)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
	at com.javadeobfuscator.deobfuscator.transformers.dasho.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:39)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```

this is the jar file
(redacted)

**Comment by Janmm14** [comment]
@ItzSomebody Please close and remove zip due to #653 (Minecraft, paid mod).

**Comment by ItzSomebody** [comment]
Thanks
