### ISSUE TITLE
Getting a runtimeException: Unexpected opcode.

### ISSUE THREAD

**Issue by ArikSquad** [java-deobfuscator/deobfuscator#982]
I tried pretty much everything, so here i am

Config: 
```yml
input: input.jar
output: output.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer
 ```

The exception;
```
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Unexpected opcode! Mode 0, opcode 167 at AromaShield/J
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:779)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:114)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)
```

**Comment by Janmm14** [comment]
it may be you go a sample obfuscated with any somewhat recent zkm version, this owuld be unsupported by the existing zelix transformers.

in case you think you got a sample with an older zkm obfuscation, try to run general peephole optimizer before zelix string, maybe it works, maybe it won't.

in general this project is considered dead as there are not enough people willing to play cat&mice **with open cards** vs (commercial) obfuscators.
