### ISSUE TITLE
deobfuscator error

### ISSUE THREAD

**Issue by safe6Sec** [java-deobfuscator/deobfuscator#991]
com.javadeobfuscator.javavm.exceptions.ExecutionException: UnsatisfiedLinkError: java/lang/ClassLoader$NativeLibrary load(Ljava/lang/String;ZZ)V
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1209)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.instructions.InvocationInstruction.execute(InvocationInstruction.java:96)
	at com.javadeobfuscator.javavm.VirtualMachine.execute(VirtualMachine.java:1265)
	at com.javadeobfuscator.javavm.VirtualMachine.internalExecute(VirtualMachine.java:1196)
	at com.javadeobfuscator.javavm.VirtualMachine.fullInitialization(VirtualMachine.java:140)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:270)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: com.javadeobfuscator.javavm.exceptions.ConvertedException: java.lang.Throwable: null
		at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1841)
		at java.lang.Runtime.loadLibrary0(Runtime.java)
		at java.lang.System.loadLibrary(System.java:1122)
		at java.lang.System.initializeSystemClass(System.java:1197)

**Comment by Janmm14** [comment]
Try use transformers not in subpackages first. Otherwise execute with java 8 and rt.jar in path for javavm compat.
