### ISSUE TITLE
ZKM String deobf fails.

### ISSUE THREAD

**Issue by SamHoque** [java-deobfuscator/deobfuscator#992]
[Thread-27] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-27] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-27] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-27] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-27] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer
[Zelix] [StringEncryptionTransformer] Starting

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Unexpected opcode! Mode 0, opcode 167 at lllIlIIIIllIlIIIIIIlIIIIIIIIlllIIIlllIIlIIlIlIlIIllllIIlIlIllIIlIlIIIIIlIIIl/llIIlIllllIIIlllIlIlIIIIIllIIlIlIIlIIIIIlIlllIlIIIIIIIlIIIlIIlIllllIlII/IIIIIIllIlIllIIIlIlIIllIIIIlllllIIlllIlllIlllIIlIlIIIllIllIlIllIIIlIIllllIlIlllI/lIIIlllIIllIlIlIIlIlIIIIllllIlIIIIIIllIIllIIlIIIlllIIllIIlllIlIIlllIlI
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:779)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:114)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
Read https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Zelix.md
newer zkm not supported and no plans exist in updating any transformers here to support new things
