### ISSUE TITLE
a NullPointerException error

### ISSUE THREAD

**Issue by SharkPika** [java-deobfuscator/deobfuscator#994]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.NullPointerException
	at com.javadeobfuscator.javavm.utils.TypeHelper.getTypeByInternalName(TypeHelper.java:99)
	at com.javadeobfuscator.javavm.utils.TypeHelper.parseType(TypeHelper.java:67)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.getSuperclass(JavaClass.java:323)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.<init>(JavaClass.java:92)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:217)
	at com.javadeobfuscator.javavm.mirrors.JavaClass.forName(JavaClass.java:199)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:40)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:88)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$21(SwingWindow.java:1108)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ItzSomebody** [comment]
Going to close this issue due to a general lack of needed information to debug (and also since no one has responded in over a month). If you're still getting an issue, can you try to also attach a sample that causes the NPE to arise?
