### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:

### ISSUE THREAD

**Issue by ethebee1** [java-deobfuscator/deobfuscator#995]
java.lang.ClassCastException: class org.objectweb.asm.tree.JumpInsnNode cannot be cast to class org.objectweb.asm.tree.LdcInsnNode (org.objectweb.asm.tree.JumpInsnNode and org.objectweb.asm.tree.LdcInsnNode are in unnamed module of loader 'app')
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.inlineReflection(ReflectionObfuscationTransformer.java:570)
        at com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer.transform(ReflectionObfuscationTransformer.java:102)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)
        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)

**Comment by Janmm14** [comment]
Error likely due to attempt to use zelix string transformer before reflection transformer. This is a [common error](https://github.com/java-deobfuscator/deobfuscator/blob/master/commonerrors/Zelix.md).

If the zelix string encryption fails or does not deobfucate most strings, the zelix version used is too new for this project.
This project is no longer maintained, so the transformer will not be updated to support newer zelix obfuscation.
