### ISSUE TITLE
Gets exception with com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer

### ISSUE THREAD

**Issue by iocmet** [java-deobfuscator/deobfuscator#996]
`java.lang.ArrayIndexOutOfBoundsException: 4`
`        at` `com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer.lambda$null$3(InvokedynamicTransformer.java:223)`
`        at java.util.ArrayList.forEach(Unknown Source)`
`        at` `com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer.lambda$inlineInvokeDynamic$4(InvokedynamicTransformer.java:179)`
`        at java.util.HashMap$Values.forEach(Unknown Source)`
`        at` `com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer.inlineInvokeDynamic(InvokedynamicTransformer.java:177)`
`        at` `com.javadeobfuscator.deobfuscator.transformers.antireleak.InvokedynamicTransformer.transform(InvokedynamicTransformer.java:70)`
`        at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)`
`        at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)`
`        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:106)`
`        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.run(DeobfuscatorMain.java:99)`
`        at com.javadeobfuscator.deobfuscator.DeobfuscatorMain.main(DeobfuscatorMain.java:36)`
[config.zip](https://github.com/java-deobfuscator/deobfuscator/files/14974842/config.zip)

**Comment by Janmm14** [comment]
Using a transformer on a file which was not obfuscated with the obfuscator the transformer is intended for, exceptions (and theoretically also wrongfully altered code) can appear.
